struct __declspec(align(8)) _SYSTEM_PROCESSOR_PERFORMANCE_INFORMATION
{
LARGE_INTEGER_0 IdleTime;
LARGE_INTEGER_0 KernelTime;
LARGE_INTEGER_0 UserTime;
LARGE_INTEGER_0 Reserved1[2];
ULONG Reserved2;
};
