enum MIB_TCP_STATE : __int32
{
MIB_TCP_STATE_CLOSED = 0x1,
MIB_TCP_STATE_LISTEN = 0x2,
MIB_TCP_STATE_SYN_SENT = 0x3,
MIB_TCP_STATE_SYN_RCVD = 0x4,
MIB_TCP_STATE_ESTAB = 0x5,
MIB_TCP_STATE_FIN_WAIT1 = 0x6,
MIB_TCP_STATE_FIN_WAIT2 = 0x7,
MIB_TCP_STATE_CLOSE_WAIT = 0x8,
MIB_TCP_STATE_CLOSING = 0x9,
MIB_TCP_STATE_LAST_ACK = 0xA,
MIB_TCP_STATE_TIME_WAIT = 0xB,
MIB_TCP_STATE_DELETE_TCB = 0xC,
};
