enum _TASKDIALOG_COMMON_BUTTON_FLAGS : __int32
{
TDCBF_OK_BUTTON = 0x1,
TDCBF_YES_BUTTON = 0x2,
TDCBF_NO_BUTTON = 0x4,
TDCBF_CANCEL_BUTTON = 0x8,
TDCBF_RETRY_BUTTON = 0x10,
TDCBF_CLOSE_BUTTON = 0x20,
};
