struct IDirect3DVolume9Vtbl
{
HRESULT (__stdcall *QueryInterface)(IDirect3DVolume9 *This, const IID *const riid, void **ppvObj); ///<
                                                                                                   ///<
                                                                                                   ///< 2026-10-03 stage-texture-com-contract host evidence: texture2D/cube/volume root plus2aliases report shared count3 across all4tested pools, retaining parent identity through GetContainer after parent release. Private data is per endpoint, not shared. Managed ROOT priority stores values; surface aliases always read/set0. Root QI supports IUnknown/Resource9/BaseTexture9/specific interface; surface QI supports IUnknown/Surface9 but rejects Resource9 despite C++ inheritance. Volume QI supports IUnknown/Volume9. Alias GetContainer(Device9) rejects; standalone surface GetContainer(IUnknown/Device9) returns device. Private-data IUNKNOWN retains on set/get and releases on removal. Zero-byte SetPrivateData returns E_OUTOFMEMORY; missing key stays missing, existing key becomes size0. Failed Reset on managed2D returns levels/type/priority0; GetLevelDesc/GetDesc reject and preserve descriptor output; GetSurfaceLevel lost failure leaves output unchanged, whereas bad-level failure while operational writesnull. QI/GetDevice/GetContainer/private data remain available. Software/HW-VP metadata comparison is archived. Owned D3D9TextureInterfaces frontend implements these contracts, aggregate retirement/inventory and required backend data callbacks; tests pass but real Store/data callbacks and live factory activation remain unfinished. No native resource allocation by this frontend; no deployment.
ULONG (__stdcall *AddRef)(IDirect3DVolume9 *This); ///<
                                                   ///<
                                                   ///< 2026-10-03 stage-texture-com-contract host evidence: texture2D/cube/volume root plus2aliases report shared count3 across all4tested pools, retaining parent identity through GetContainer after parent release. Private data is per endpoint, not shared. Managed ROOT priority stores values; surface aliases always read/set0. Root QI supports IUnknown/Resource9/BaseTexture9/specific interface; surface QI supports IUnknown/Surface9 but rejects Resource9 despite C++ inheritance. Volume QI supports IUnknown/Volume9. Alias GetContainer(Device9) rejects; standalone surface GetContainer(IUnknown/Device9) returns device. Private-data IUNKNOWN retains on set/get and releases on removal. Zero-byte SetPrivateData returns E_OUTOFMEMORY; missing key stays missing, existing key becomes size0. Failed Reset on managed2D returns levels/type/priority0; GetLevelDesc/GetDesc reject and preserve descriptor output; GetSurfaceLevel lost failure leaves output unchanged, whereas bad-level failure while operational writesnull. QI/GetDevice/GetContainer/private data remain available. Software/HW-VP metadata comparison is archived. Owned D3D9TextureInterfaces frontend implements these contracts, aggregate retirement/inventory and required backend data callbacks; tests pass but real Store/data callbacks and live factory activation remain unfinished. No native resource allocation by this frontend; no deployment.
ULONG (__stdcall *Release)(IDirect3DVolume9 *This); ///<
                                                    ///<
                                                    ///< 2026-10-03 stage-texture-com-contract host evidence: texture2D/cube/volume root plus2aliases report shared count3 across all4tested pools, retaining parent identity through GetContainer after parent release. Private data is per endpoint, not shared. Managed ROOT priority stores values; surface aliases always read/set0. Root QI supports IUnknown/Resource9/BaseTexture9/specific interface; surface QI supports IUnknown/Surface9 but rejects Resource9 despite C++ inheritance. Volume QI supports IUnknown/Volume9. Alias GetContainer(Device9) rejects; standalone surface GetContainer(IUnknown/Device9) returns device. Private-data IUNKNOWN retains on set/get and releases on removal. Zero-byte SetPrivateData returns E_OUTOFMEMORY; missing key stays missing, existing key becomes size0. Failed Reset on managed2D returns levels/type/priority0; GetLevelDesc/GetDesc reject and preserve descriptor output; GetSurfaceLevel lost failure leaves output unchanged, whereas bad-level failure while operational writesnull. QI/GetDevice/GetContainer/private data remain available. Software/HW-VP metadata comparison is archived. Owned D3D9TextureInterfaces frontend implements these contracts, aggregate retirement/inventory and required backend data callbacks; tests pass but real Store/data callbacks and live factory activation remain unfinished. No native resource allocation by this frontend; no deployment.
HRESULT (__stdcall *GetDevice)(IDirect3DVolume9 *This, IDirect3DDevice9 **ppDevice);
HRESULT (__stdcall *SetPrivateData)(IDirect3DVolume9 *This, const GUID *const refguid, const void *pData, DWORD SizeOfData, DWORD Flags); ///<
                                                                                                                                          ///<
                                                                                                                                          ///< 2026-10-03 stage-texture-com-contract host evidence: texture2D/cube/volume root plus2aliases report shared count3 across all4tested pools, retaining parent identity through GetContainer after parent release. Private data is per endpoint, not shared. Managed ROOT priority stores values; surface aliases always read/set0. Root QI supports IUnknown/Resource9/BaseTexture9/specific interface; surface QI supports IUnknown/Surface9 but rejects Resource9 despite C++ inheritance. Volume QI supports IUnknown/Volume9. Alias GetContainer(Device9) rejects; standalone surface GetContainer(IUnknown/Device9) returns device. Private-data IUNKNOWN retains on set/get and releases on removal. Zero-byte SetPrivateData returns E_OUTOFMEMORY; missing key stays missing, existing key becomes size0. Failed Reset on managed2D returns levels/type/priority0; GetLevelDesc/GetDesc reject and preserve descriptor output; GetSurfaceLevel lost failure leaves output unchanged, whereas bad-level failure while operational writesnull. QI/GetDevice/GetContainer/private data remain available. Software/HW-VP metadata comparison is archived. Owned D3D9TextureInterfaces frontend implements these contracts, aggregate retirement/inventory and required backend data callbacks; tests pass but real Store/data callbacks and live factory activation remain unfinished. No native resource allocation by this frontend; no deployment.
HRESULT (__stdcall *GetPrivateData)(IDirect3DVolume9 *This, const GUID *const refguid, void *pData, DWORD *pSizeOfData);
HRESULT (__stdcall *FreePrivateData)(IDirect3DVolume9 *This, const GUID *const refguid);
HRESULT (__stdcall *GetContainer)(IDirect3DVolume9 *This, const IID *const riid, void **ppContainer); ///<
                                                                                                      ///<
                                                                                                      ///< 2026-10-03 stage-texture-com-contract host evidence: texture2D/cube/volume root plus2aliases report shared count3 across all4tested pools, retaining parent identity through GetContainer after parent release. Private data is per endpoint, not shared. Managed ROOT priority stores values; surface aliases always read/set0. Root QI supports IUnknown/Resource9/BaseTexture9/specific interface; surface QI supports IUnknown/Surface9 but rejects Resource9 despite C++ inheritance. Volume QI supports IUnknown/Volume9. Alias GetContainer(Device9) rejects; standalone surface GetContainer(IUnknown/Device9) returns device. Private-data IUNKNOWN retains on set/get and releases on removal. Zero-byte SetPrivateData returns E_OUTOFMEMORY; missing key stays missing, existing key becomes size0. Failed Reset on managed2D returns levels/type/priority0; GetLevelDesc/GetDesc reject and preserve descriptor output; GetSurfaceLevel lost failure leaves output unchanged, whereas bad-level failure while operational writesnull. QI/GetDevice/GetContainer/private data remain available. Software/HW-VP metadata comparison is archived. Owned D3D9TextureInterfaces frontend implements these contracts, aggregate retirement/inventory and required backend data callbacks; tests pass but real Store/data callbacks and live factory activation remain unfinished. No native resource allocation by this frontend; no deployment.
HRESULT (__stdcall *GetDesc)(IDirect3DVolume9 *This, D3DVOLUME_DESC *pDesc); ///<
                                                                             ///<
                                                                             ///< 2026-10-03 stage-texture-com-contract host evidence: texture2D/cube/volume root plus2aliases report shared count3 across all4tested pools, retaining parent identity through GetContainer after parent release. Private data is per endpoint, not shared. Managed ROOT priority stores values; surface aliases always read/set0. Root QI supports IUnknown/Resource9/BaseTexture9/specific interface; surface QI supports IUnknown/Surface9 but rejects Resource9 despite C++ inheritance. Volume QI supports IUnknown/Volume9. Alias GetContainer(Device9) rejects; standalone surface GetContainer(IUnknown/Device9) returns device. Private-data IUNKNOWN retains on set/get and releases on removal. Zero-byte SetPrivateData returns E_OUTOFMEMORY; missing key stays missing, existing key becomes size0. Failed Reset on managed2D returns levels/type/priority0; GetLevelDesc/GetDesc reject and preserve descriptor output; GetSurfaceLevel lost failure leaves output unchanged, whereas bad-level failure while operational writesnull. QI/GetDevice/GetContainer/private data remain available. Software/HW-VP metadata comparison is archived. Owned D3D9TextureInterfaces frontend implements these contracts, aggregate retirement/inventory and required backend data callbacks; tests pass but real Store/data callbacks and live factory activation remain unfinished. No native resource allocation by this frontend; no deployment.
HRESULT (__stdcall *LockBox)(IDirect3DVolume9 *This, D3DLOCKED_BOX *pLockedVolume, const D3DBOX *pBox, DWORD Flags); ///<
                                                                                                                     ///<
                                                                                                                     ///< 2026-10-03 stage-owned-texture-mapping:1980native texture/cube/volume map cases and459surface cases. CPU2D/cube paths accept ignored hints incl tested unknown bit1, READONLY|DISCARD and bounded empty/unaligned-BC rectangles; volume and DEFAULT paths validate flags/ranges. DEFAULT ordinary textures reject locks; DYNAMIC accepts qualified maps. DEFAULT cube DISCARD rejects; dynamic2D/volume null top-level DISCARD succeeds; lower2D/cube DEFAULT DISCARD rejects. Duplicate same-subresource locks reject without breaking first Unlock; separate mips can lock together. Failed operational locks zero mapping outputs. DEFAULT standalone DONOTWAIT is valid but observed WASSTILLDRAWING while pending. RT row pitch has provider padding (64 vs owned minimum32 in8x8ARGB case), not portable fixed ABI. OwnedTextureMapping now uses Store sessions/owned row buffers, exact upload regions, CPU flag normalization, owner-supplied busy status, worker/race exclusion and reset replay; WARP pixels and legacy native-lock CPU regression pass. BeginOwnedLock rejects overlap before poisoning a lease; legacy native BeginLock remains unchanged. Empty CPU map has no write authority; out-of-bounds/reversed inputs reject. Component is not wired to live COM/factory callbacks yet. No renderer DLL build/deployment.
HRESULT (__stdcall *UnlockBox)(IDirect3DVolume9 *This); ///<
                                                        ///<
                                                        ///< 2026-10-03 stage-owned-texture-mapping:1980native texture/cube/volume map cases and459surface cases. CPU2D/cube paths accept ignored hints incl tested unknown bit1, READONLY|DISCARD and bounded empty/unaligned-BC rectangles; volume and DEFAULT paths validate flags/ranges. DEFAULT ordinary textures reject locks; DYNAMIC accepts qualified maps. DEFAULT cube DISCARD rejects; dynamic2D/volume null top-level DISCARD succeeds; lower2D/cube DEFAULT DISCARD rejects. Duplicate same-subresource locks reject without breaking first Unlock; separate mips can lock together. Failed operational locks zero mapping outputs. DEFAULT standalone DONOTWAIT is valid but observed WASSTILLDRAWING while pending. RT row pitch has provider padding (64 vs owned minimum32 in8x8ARGB case), not portable fixed ABI. OwnedTextureMapping now uses Store sessions/owned row buffers, exact upload regions, CPU flag normalization, owner-supplied busy status, worker/race exclusion and reset replay; WARP pixels and legacy native-lock CPU regression pass. BeginOwnedLock rejects overlap before poisoning a lease; legacy native BeginLock remains unchanged. Empty CPU map has no write authority; out-of-bounds/reversed inputs reject. Component is not wired to live COM/factory callbacks yet. No renderer DLL build/deployment.
};
