int __userpurge EffectItem_BuildDisplayString_::CheckRangeType@<eax>(
        char a1@<bl>,
        int a2,
        int a3,
        int a4,
        int a5,
        int a6,
        int a7,
        int a8,
        int a9,
        char a10,
        int a11,
        int a12,
        int a13,
        int a14,
        int a15,
        int a16,
        int a17,
        int a18,
        int a19,
        int a20,
        int a21,
        int a22,
        int a23,
        int a24,
        int a25,
        int a26,
        int a27,
        int a28,
        int a29,
        int a30,
        int a31,
        int a32,
        int a33,
        int a34,
        int a35,
        int a36,
        int a37,
        int a38,
        int a39,
        int a40,
        int a41,
        int a42,
        int a43,
        char a44,
        char a45)
{
  if ( a44 != a1 )
    return EffectItem_BuildDisplayString_::Done(a2, a3, a4, a5, a6, a7);
  if ( a45 == a1 )
    return EffectItem_BuildDisplayString_::DefaultRange(a2, a3, a4, a5, a6, a7, a8, a9, a10);
  return EffectItem_BuildDisplayString_::StrikeRange(a2, a3, a4, a5, a6, a7, a8, a9, a10);
}
