enum ASSOCDATA : __int32
{
ASSOCDATA_MSIDESCRIPTOR = 0x1,
ASSOCDATA_NOACTIVATEHANDLER = 0x2,
ASSOCDATA_QUERYCLASSSTORE = 0x3,
ASSOCDATA_HASPERUSERASSOC = 0x4,
ASSOCDATA_EDITFLAGS = 0x5,
ASSOCDATA_VALUE = 0x6,
ASSOCDATA_MAX = 0x7,
};
