enum _D3DKMT_VIDPNSOURCEOWNER_TYPE : __int32
{
D3DKMT_VIDPNSOURCEOWNER_UNOWNED = 0x0,
D3DKMT_VIDPNSOURCEOWNER_SHARED = 0x1,
D3DKMT_VIDPNSOURCEOWNER_EXCLUSIVE = 0x2,
D3DKMT_VIDPNSOURCEOWNER_EXCLUSIVEGDI = 0x3,
D3DKMT_VIDPNSOURCEOWNER_EMULATED = 0x4,
};
