struct $69D6AE3989DB793CDBCAC0CEA1C97D23
{
HMODULE hModule __offset(OFF64|AUTO);
HIC (*fnICOpen)(DWORD, DWORD, UINT) __offset(OFF64|AUTO);
LRESULT_0 (*fnICClose)(HIC) __offset(OFF64|AUTO);
LRESULT_0 (*fnICSendMessage)(HIC, UINT, DWORD_PTR, DWORD_PTR) __offset(OFF64|AUTO);
DWORD (*fnICDecompress)(HIC, DWORD, LPBITMAPINFOHEADER, LPVOID, LPBITMAPINFOHEADER, LPVOID) __offset(OFF64|AUTO);
};
