enum mwMediumArmor_MorrowindSkillIndex
{
MW_SKILL_Block = 0x0,
MW_SKILL_Armorer = 0x1,
MW_SKILL_MediumArmor = 0x2,
MW_SKILL_HeavyArmor = 0x3,
MW_SKILL_BluntWeapon = 0x4,
MW_SKILL_LongBlade = 0x5,
MW_SKILL_Axe = 0x6,
MW_SKILL_Spear = 0x7,
MW_SKILL_Athletics = 0x8,
MW_SKILL_Enchant = 0x9,
MW_SKILL_Destruction = 0xA,
MW_SKILL_Alteration = 0xB,
MW_SKILL_Illusion = 0xC,
MW_SKILL_Conjuration = 0xD,
MW_SKILL_Mysticism = 0xE,
MW_SKILL_Restoration = 0xF,
MW_SKILL_Alchemy = 0x10,
MW_SKILL_Unarmored = 0x11,
MW_SKILL_Security = 0x12,
MW_SKILL_Sneak = 0x13,
MW_SKILL_Acrobatics = 0x14,
MW_SKILL_LightArmor = 0x15,
MW_SKILL_ShortBlade = 0x16,
MW_SKILL_Marksman = 0x17,
MW_SKILL_Mercantile = 0x18,
MW_SKILL_Speechcraft = 0x19,
MW_SKILL_HandToHand = 0x1A,
};
