enum tagPOINTER_DEVICE_TYPE : __int32
{
POINTER_DEVICE_TYPE_INTEGRATED_PEN = 0x1,
POINTER_DEVICE_TYPE_EXTERNAL_PEN = 0x2,
POINTER_DEVICE_TYPE_TOUCH = 0x3,
POINTER_DEVICE_TYPE_TOUCH_PAD = 0x4,
POINTER_DEVICE_TYPE_MAX = 0xFFFFFFFF,
};
