int __usercall MagicCaster_ApplyActiveMagicItem_::EffectLoop_CheckEnchantment@<eax>(
        int a1@<ebp>,
        int a2@<esi>,
        TESObjectREFR *ebx0@<ebx>,
        int a4@<edi>,
        int a5,
        int a6,
        int a7,
        int a8,
        int a9,
        int a10,
        int a11,
        int a12,
        int a13,
        int a14,
        int a15,
        float a16,
        int a17,
        int a18,
        int a19,
        __int64 a20,
        int a21,
        int a22,
        int a23,
        int a24,
        int a25,
        int a26,
        int a27,
        int a28,
        int a29,
        int a30,
        int a31,
        int a32,
        int a33,
        int a34,
        int a35)
{
  int v35; // eax

  v35 = (*(int (__thiscall **)(int))(*(_DWORD *)a2 + 0x30))(a2);
  if ( (*(int (__thiscall **)(int))(*(_DWORD *)v35 + 0x18))(v35) == 6
    && a34
    && !EnchantmentItem_EffectAllowedFromEnch__((unsigned __int8 *)a34, 0, *(_DWORD *)(a1 + 0x1C), 0) )
  {
    return MagicCaster_ApplyActiveMagicItem_::EffectLoop_Next(
             a4,
             a2,
             ebx0,
             a5,
             a6,
             a7,
             a8,
             a9,
             a10,
             a11,
             a12,
             a13,
             a14,
             a15,
             SLODWORD(a16),
             a17,
             a18,
             a19,
             a20,
             a21,
             a22,
             a23,
             a24,
             a25,
             a26,
             a27,
             a28,
             a29,
             a30,
             a31,
             a32,
             a33,
             a34,
             a35);
  }
  else
  {
    return MagicCaster_ApplyActiveMagicItem_::EffectLoop_CreateActiveEffect(
             a1,
             a2,
             ebx0,
             a5,
             a6,
             a7,
             a8,
             a9,
             a10,
             a11,
             a12,
             a13,
             a14,
             a15,
             a16,
             a17,
             a18,
             a19,
             a20,
             a21,
             a22,
             a23,
             a24,
             a25,
             a26,
             a27,
             a28,
             a29,
             a30,
             a31,
             a32,
             a33,
             a34,
             a35);
  }
}
