int __usercall Actor_AttackHandling_::NotEnoughChargeMsg@<eax>(
        char a1@<bpl>,
        PlayerCharacter *a2@<edi>,
        double a3@<st2>,
        int a4,
        int a5,
        int a6,
        int a7,
        int a8,
        int a9,
        __int16 a10,
        int a11,
        int a12,
        int a13,
        int a14,
        int a15,
        int a16,
        float a17,
        int a18,
        int a19,
        int a20,
        int a21,
        int a22,
        int a23,
        int a24,
        int a25,
        int a26,
        int a27,
        int a28,
        int a29,
        int a30,
        int a31,
        int a32,
        int a33,
        int a34,
        int a35,
        int a36,
        int a37,
        int a38,
        int a39,
        int a40,
        int a41,
        int a42,
        int a43,
        int a44)
{
  if ( HIBYTE(a13) )
  {
    if ( a2 == TESDataHandler_g_PlayerRef )
      sub_663E80((int)TESDataHandler_g_PlayerRef, a1, a3);
  }
  return Actor_AttackHandling_::SneakAttackCheck(
           a4,
           a5,
           a6,
           a7,
           a8,
           a9,
           a10,
           a11,
           a12,
           a13,
           a14,
           a15,
           a16,
           a17,
           a18,
           a19,
           a20,
           a21,
           a22,
           a23,
           a24,
           a25,
           a26,
           a27,
           a28,
           a29,
           a30,
           a31,
           a32,
           a33,
           a34,
           a35,
           a36,
           a37,
           a38,
           a39,
           a40,
           a41,
           a42,
           a43,
           a44);
}
