int __usercall MagicCaster_ApplyActiveMagicItem_::EffectLoop_T3InedbibleIngred_@<eax>(
        char a1@<al>,
        int ebp0@<ebp>,
        int edi0@<edi>,
        int esi0@<esi>,
        char ch0@<ch>,
        TESObjectREFR *ebx0@<ebx>,
        int a7,
        int a8,
        int a9,
        int a10,
        int a11,
        int a12,
        int a13,
        int a14,
        float a15,
        float a16,
        int a17,
        int a18,
        int a19,
        int a20,
        int a21,
        __int64 a22,
        int a23,
        int a24,
        int a25,
        int a26,
        int a27,
        int a28,
        int a29,
        int a30,
        int a31,
        int a32,
        int a33,
        int a34,
        int a35,
        int a36,
        int a37)
{
  if ( a1 ) /*0x69b3c9*/
    return MagicCaster_ApplyActiveMagicItem_::EffectLoop_T3InedbibleIngred( /*0x69b3ca*/
             ebp0,
             edi0,
             esi0,
             ch0,
             ebx0,
             a7,
             a8,
             a9,
             a10,
             a11,
             a12,
             a13,
             a14,
             a15,
             a16,
             a17,
             a18,
             a19,
             a20,
             a21,
             a22,
             a23,
             a24,
             a25,
             a26,
             a27,
             a28,
             a29,
             a30,
             a31,
             a32,
             a33,
             a34,
             a35,
             a36,
             a37);
  else
    return MagicCaster_ApplyActiveMagicItem_::EffectLoop_T4InedbibleIngred( /*0x69b3c9*/
             ebp0,
             edi0,
             esi0,
             ebx0,
             a7,
             a8,
             a9,
             a10,
             a11,
             a12,
             a13,
             a14,
             a15,
             a16,
             a17,
             a18,
             a19,
             a20,
             a21,
             a22,
             a23,
             a24,
             a25,
             a26,
             a27,
             a28,
             a29,
             a30,
             a31,
             a32,
             a33,
             a34,
             a35,
             a36,
             a37);
}
