int __usercall Actor_AttackHandling_::ApplyNormalWeaponResistance@<eax>(
        char a1@<bl>,
        int edi0@<edi>,
        int esi0@<esi>,
        int a4,
        int a5,
        int a6,
        int a7,
        int a8,
        int a9,
        int a10,
        int a11,
        int a12,
        int a13,
        int a14,
        int a15,
        int a16,
        int a17,
        int a18,
        int a19,
        int a20,
        int a21,
        int a22,
        int a23)
{
  float v24; // [esp+18h] [ebp+18h]

  if ( !a1 || (unsigned int)(a11 - 1) > 0x62 )
    return Actor_AttackHandling_::ApplyWeaponDamage_Check_(a4, a5, a6, a7, a8, a9, a10, a11, a12, a13, a14, a15);
  if ( !a15 && !a12 )
    return Actor_AttackHandling_::ApplyWeaponDamage_Check(
             0,
             edi0,
             esi0,
             a4,
             a5,
             a6,
             a7,
             a8,
             *(float *)&a9,
             a10,
             a11,
             0,
             a13,
             a14,
             0,
             a16,
             a17,
             a18,
             a19,
             a20,
             a21,
             a22,
             a23);
  v24 = (1.0 - (double)a11 / fCostant_100) * *(float *)&a9;
  return Actor_AttackHandling_::ApplyWeaponDamage_Check(
           a15,
           edi0,
           esi0,
           a4,
           a5,
           a6,
           a7,
           a8,
           v24,
           a10,
           a11,
           a12,
           a13,
           a14,
           a15,
           a16,
           a17,
           a18,
           a19,
           a20,
           a21,
           a22,
           a23);
}
