enum ConcRT_EventType : __int32
{
CONCRT_EVENT_GENERIC = 0x0,
CONCRT_EVENT_START = 0x1,
CONCRT_EVENT_END = 0x2,
CONCRT_EVENT_BLOCK = 0x3,
CONCRT_EVENT_UNBLOCK = 0x4,
CONCRT_EVENT_YIELD = 0x5,
CONCRT_EVENT_ATTACH = 0x6,
CONCRT_EVENT_DETACH = 0x7,
};
