enum $713E3BE81FB0694EA46B1AE113AA4753 : __int32
{
DSPROPERTY_DIRECTSOUNDDEVICE_WAVEDEVICEMAPPING_A = 0x1,
DSPROPERTY_DIRECTSOUNDDEVICE_DESCRIPTION_1 = 0x2,
DSPROPERTY_DIRECTSOUNDDEVICE_ENUMERATE_1 = 0x3,
DSPROPERTY_DIRECTSOUNDDEVICE_WAVEDEVICEMAPPING_W = 0x4,
DSPROPERTY_DIRECTSOUNDDEVICE_DESCRIPTION_A = 0x5,
DSPROPERTY_DIRECTSOUNDDEVICE_DESCRIPTION_W = 0x6,
DSPROPERTY_DIRECTSOUNDDEVICE_ENUMERATE_A = 0x7,
DSPROPERTY_DIRECTSOUNDDEVICE_ENUMERATE_W = 0x8,
};
