struct IEnumCATEGORYINFOVtbl
{
HRESULT_0 (*QueryInterface)(IEnumCATEGORYINFO_0 *, const IID *const, void **);
ULONG (*AddRef)(IEnumCATEGORYINFO_0 *);
ULONG (*Release)(IEnumCATEGORYINFO_0 *);
HRESULT_0 (*Next)(IEnumCATEGORYINFO_0 *, ULONG, CATEGORYINFO *, ULONG *);
HRESULT_0 (*Skip)(IEnumCATEGORYINFO_0 *, ULONG);
HRESULT_0 (*Reset)(IEnumCATEGORYINFO_0 *);
HRESULT_0 (*Clone)(IEnumCATEGORYINFO_0 *, IEnumCATEGORYINFO_0 **);
};
