enum RADIOBUTTONSTATES : __int32
{
RADIOBUTTONStateFiller0 = 0x0,
RBS_UNCHECKEDNORMAL = 0x1,
RBS_UNCHECKEDHOT = 0x2,
RBS_UNCHECKEDPRESSED = 0x3,
RBS_UNCHECKEDDISABLED = 0x4,
RBS_CHECKEDNORMAL = 0x5,
RBS_CHECKEDHOT = 0x6,
RBS_CHECKEDPRESSED = 0x7,
RBS_CHECKEDDISABLED = 0x8,
};
