enum TRACKBARPARTS : __int32
{
TRACKBARPartFiller0 = 0x0,
TKP_TRACK = 0x1,
TKP_TRACKVERT = 0x2,
TKP_THUMB = 0x3,
TKP_THUMBBOTTOM = 0x4,
TKP_THUMBTOP = 0x5,
TKP_THUMBVERT = 0x6,
TKP_THUMBLEFT = 0x7,
TKP_THUMBRIGHT = 0x8,
TKP_TICS = 0x9,
TKP_TICSVERT = 0xA,
};
