enum DOS_PATHNAME_TYPE : __int32
{
INVALID_PATH = 0x0,
UNC_PATH = 0x1,
ABSOLUTE_DRIVE_PATH = 0x2,
RELATIVE_DRIVE_PATH = 0x3,
ABSOLUTE_PATH = 0x4,
RELATIVE_PATH = 0x5,
DEVICE_PATH = 0x6,
UNC_DOT_PATH = 0x7,
};
