int __thiscall EffectItem_Initialize(
        _DWORD *this,
        _DWORD *a2,
        int a3,
        int a4,
        int a5,
        int a6,
        int a7,
        int a8,
        int a9,
        int a10,
        int a11,
        int a12,
        int a13,
        int a14,
        int a15,
        int a16,
        int a17,
        int a18,
        int a19,
        int a20,
        int a21,
        int a22,
        int a23,
        int a24,
        int a25)
{
  *(this + 7) = a2;
  *this = a2[0x26];
  *(this + 2) = 0;
  *(this + 3) = 0;
  *(this + 1) = 0;
  return EffectItem_Initialize_::InitData(
           a2,
           (int)this,
           0,
           (int)a2,
           a3,
           a4,
           a5,
           a6,
           a7,
           a8,
           a9,
           a10,
           a11,
           a12,
           a13,
           a14,
           a15,
           a16,
           a17,
           a18,
           a19,
           a20,
           a21,
           a22,
           a23,
           a24,
           a25);
}
