enum ACTCTX_REQUESTED_RUN_LEVEL : __int32
{
ACTCTX_RUN_LEVEL_UNSPECIFIED = 0x0,
ACTCTX_RUN_LEVEL_AS_INVOKER = 0x1,
ACTCTX_RUN_LEVEL_HIGHEST_AVAILABLE = 0x2,
ACTCTX_RUN_LEVEL_REQUIRE_ADMIN = 0x3,
ACTCTX_RUN_LEVEL_NUMBERS = 0x4,
};
