enum INTERNET_SCHEME : __int32
{
INTERNET_SCHEME_PARTIAL = 0xFFFFFFFE,
INTERNET_SCHEME_UNKNOWN = 0xFFFFFFFF,
INTERNET_SCHEME_DEFAULT = 0x0,
INTERNET_SCHEME_FTP = 0x1,
INTERNET_SCHEME_GOPHER = 0x2,
INTERNET_SCHEME_HTTP = 0x3,
INTERNET_SCHEME_HTTPS = 0x4,
INTERNET_SCHEME_FILE = 0x5,
INTERNET_SCHEME_NEWS = 0x6,
INTERNET_SCHEME_MAILTO = 0x7,
INTERNET_SCHEME_SOCKS = 0x8,
INTERNET_SCHEME_JAVASCRIPT = 0x9,
INTERNET_SCHEME_VBSCRIPT = 0xA,
INTERNET_SCHEME_RES = 0xB,
INTERNET_SCHEME_FIRST = 0x1,
INTERNET_SCHEME_LAST = 0xB,
};
