enum apc_type : __int32
{
APC_NONE = 0x0,
APC_USER = 0x1,
APC_ASYNC_IO = 0x2,
APC_VIRTUAL_ALLOC = 0x3,
APC_VIRTUAL_FREE = 0x4,
APC_VIRTUAL_QUERY = 0x5,
APC_VIRTUAL_PROTECT = 0x6,
APC_VIRTUAL_FLUSH = 0x7,
APC_VIRTUAL_LOCK = 0x8,
APC_VIRTUAL_UNLOCK = 0x9,
APC_MAP_VIEW = 0xA,
APC_UNMAP_VIEW = 0xB,
APC_CREATE_THREAD = 0xC,
APC_DUP_HANDLE = 0xD,
APC_BREAK_PROCESS = 0xE,
};
