enum FDIERROR : __int32
{
FDIERROR_NONE = 0x0,
FDIERROR_CABINET_NOT_FOUND = 0x1,
FDIERROR_NOT_A_CABINET = 0x2,
FDIERROR_UNKNOWN_CABINET_VERSION = 0x3,
FDIERROR_CORRUPT_CABINET = 0x4,
FDIERROR_ALLOC_FAIL = 0x5,
FDIERROR_BAD_COMPR_TYPE = 0x6,
FDIERROR_MDI_FAIL = 0x7,
FDIERROR_TARGET_FILE = 0x8,
FDIERROR_RESERVE_MISMATCH = 0x9,
FDIERROR_WRONG_CABINET = 0xA,
FDIERROR_USER_ABORT = 0xB,
};
