struct _DSPROPERTY_DIRECTSOUNDDEVICE_DESCRIPTION_1_DATA
{
GUID DeviceId;
CHAR DescriptionA[256];
WCHAR_0 DescriptionW[256];
CHAR ModuleA[260];
WCHAR_0 ModuleW[260];
DIRECTSOUNDDEVICE_TYPE Type;
DIRECTSOUNDDEVICE_DATAFLOW DataFlow;
ULONG WaveDeviceId;
ULONG Devnode;
};
