enum tag_SCRIPT_JUSTIFY : __int32
{
SCRIPT_JUSTIFY_NONE = 0x0,
SCRIPT_JUSTIFY_ARABIC_BLANK = 0x1,
SCRIPT_JUSTIFY_CHARACTER = 0x2,
SCRIPT_JUSTIFY_RESERVED1 = 0x3,
SCRIPT_JUSTIFY_BLANK = 0x4,
SCRIPT_JUSTIFY_RESERVED2 = 0x5,
SCRIPT_JUSTIFY_RESERVED3 = 0x6,
SCRIPT_JUSTIFY_ARABIC_NORMAL = 0x7,
SCRIPT_JUSTIFY_ARABIC_KASHIDA = 0x8,
SCRIPT_JUSTIFY_ARABIC_ALEF = 0x9,
SCRIPT_JUSTIFY_ARABIC_HA = 0xA,
SCRIPT_JUSTIFY_ARABIC_RA = 0xB,
SCRIPT_JUSTIFY_ARABIC_BA = 0xC,
SCRIPT_JUSTIFY_ARABIC_BARA = 0xD,
SCRIPT_JUSTIFY_ARABIC_SEEN = 0xE,
SCRIPT_JUSTIFY_ARABIC_SEEN_M = 0xF,
};
