enum _TASKDIALOG_NOTIFICATIONS : __int32
{
TDN_CREATED = 0x0,
TDN_NAVIGATED = 0x1,
TDN_BUTTON_CLICKED = 0x2,
TDN_HYPERLINK_CLICKED = 0x3,
TDN_TIMER = 0x4,
TDN_DESTROYED = 0x5,
TDN_RADIO_BUTTON_CLICKED = 0x6,
TDN_DIALOG_CONSTRUCTED = 0x7,
TDN_VERIFICATION_CLICKED = 0x8,
TDN_HELP = 0x9,
TDN_EXPANDO_BUTTON_CLICKED = 0xA,
};
