0xA26DA0: mov     ecx, offset off_B28E00
0xA26DA5: mov     off_B28E00, offset ??_7?$NiTPointerListBase@V?$NiTPointerAllocator@I@@I@@6B@; const NiTPointerListBase<NiTPointerAllocator<uint>,uint>::`vftable' ...
0xA26DAF: call    NiTPointerList__FreeAllNodes
0xA26DB4: mov     off_B28E00, offset ??_7?$NiTListBase@V?$NiTPointerAllocator@I@@I@@6B@; const NiTListBase<NiTPointerAllocator<uint>,uint>::`vftable' ...
0xA26DBE: retn
