struct IEnumSTATPROPSETSTGVtbl
{
HRESULT_0 (*QueryInterface)(IEnumSTATPROPSETSTG_0 *, const IID *const, void **);
ULONG (*AddRef)(IEnumSTATPROPSETSTG_0 *);
ULONG (*Release)(IEnumSTATPROPSETSTG_0 *);
HRESULT_0 (*Next)(IEnumSTATPROPSETSTG_0 *, ULONG, STATPROPSETSTG *, ULONG *);
HRESULT_0 (*Skip)(IEnumSTATPROPSETSTG_0 *, ULONG);
HRESULT_0 (*Reset)(IEnumSTATPROPSETSTG_0 *);
HRESULT_0 (*Clone)(IEnumSTATPROPSETSTG_0 *, IEnumSTATPROPSETSTG_0 **);
};
