enum DBREASONENUM : __int32
{
DBREASON_ROWSET_FETCHPOSITIONCHANGE = 0x0,
DBREASON_ROWSET_RELEASE = 0x1,
DBREASON_COLUMN_SET = 0x2,
DBREASON_COLUMN_RECALCULATED = 0x3,
DBREASON_ROW_ACTIVATE = 0x4,
DBREASON_ROW_RELEASE = 0x5,
DBREASON_ROW_DELETE = 0x6,
DBREASON_ROW_FIRSTCHANCE = 0x7,
DBREASON_ROW_INSERT = 0x8,
DBREASON_ROW_RESYNCH = 0x9,
DBREASON_ROW_UNDOCHANGE = 0xA,
DBREASON_ROW_UNDOINSERT = 0xB,
DBREASON_ROW_UNDODELETE = 0xC,
DBREASON_ROW_UPDATE = 0xD,
DBREASON_ROWSET_CHANGED = 0xE,
};
