enum DISPLAYCONFIG_SCALING : __int32
{
DISPLAYCONFIG_SCALING_IDENTITY = 0x1,
DISPLAYCONFIG_SCALING_CENTERED = 0x2,
DISPLAYCONFIG_SCALING_STRETCHED = 0x3,
DISPLAYCONFIG_SCALING_ASPECTRATIOCENTEREDMAX = 0x4,
DISPLAYCONFIG_SCALING_CUSTOM = 0x5,
DISPLAYCONFIG_SCALING_PREFERRED = 0x80,
DISPLAYCONFIG_SCALING_FORCE_UINT32 = 0xFFFFFFFF,
};
