enum __bitmask BSShaderFeatureMask
{
BSSM_FEATURE_AMBIENT = 0x1,
BSSM_FEATURE_DIFFUSE = 0x2,
BSSM_FEATURE_TEXTURE = 0x4,
BSSM_FEATURE_SPECULAR = 0x8,
BSSM_FEATURE_SHADOW_MAP = 0x10,
BSSM_FEATURE_CANOPY_SHADOW = 0x20,
};
