enum sortkey_special_script : __int32
{
SORTKEY_UNSORTABLE = 0x0,
SORTKEY_DIACRITIC = 0x1,
SORTKEY_EXPANSION = 0x2,
SORTKEY_JAPANESE = 0x3,
SORTKEY_JAMO = 0x4,
SORTKEY_CJK = 0x5,
SORTKEY_PUNCTUATION = 0x6,
SORTKEY_SYMBOL_1 = 0x7,
SORTKEY_SYMBOL_2 = 0x8,
SORTKEY_SYMBOL_3 = 0x9,
SORTKEY_SYMBOL_4 = 0xA,
SORTKEY_SYMBOL_5 = 0xB,
SORTKEY_SYMBOL_6 = 0xC,
};
