int __usercall Actor_AttackHandling_::CalcArmorRating_@<eax>(
        int esi0@<esi>,
        double st7_0@<st0>,
        int ebp0@<ebp>,
        int edi0@<edi>,
        double st6_0@<st1>,
        int a6,
        int a7,
        int a8,
        int a9,
        int a10,
        int a11,
        int a12,
        int a13,
        int a14,
        int a15,
        int a16,
        int a17,
        int a18,
        float a19,
        float a20)
{
  return Actor_AttackHandling_::CalcArmorRating(
           esi0,
           st7_0,
           ebp0,
           edi0,
           st6_0,
           a6,
           a7,
           a8,
           a9,
           a10,
           a11,
           a12,
           a13,
           a14,
           a15,
           a16,
           a17,
           a18,
           a19,
           a20);
}
