int __usercall Actor_AttackHandling_::CalcArmorRating_@<eax>(
        int esi0@<esi>,
        int ebp0@<ebp>,
        int edi0@<edi>,
        double a4@<st2>,
        int a5,
        int a6,
        int a7,
        int a8,
        int a9,
        float a10,
        int a11,
        int a12,
        int a13,
        int a14,
        int a15,
        int a16,
        float a17,
        float a18,
        float a19)
{
  return Actor_AttackHandling_::CalcArmorRating(
           esi0,
           ebp0,
           edi0,
           a4,
           a5,
           a6,
           a7,
           a8,
           a9,
           a10,
           a11,
           a12,
           a13,
           a14,
           a15,
           a16,
           a17,
           a18,
           a19);
}
