enum HEADERITEMSTATES_0 : __int32
{
HIS_NORMAL_0 = 0x1,
HIS_HOT_0 = 0x2,
HIS_PRESSED_0 = 0x3,
HIS_SORTEDNORMAL = 0x4,
HIS_SORTEDHOT = 0x5,
HIS_SORTEDPRESSED = 0x6,
HIS_ICONNORMAL = 0x7,
HIS_ICONHOT = 0x8,
HIS_ICONPRESSED = 0x9,
HIS_ICONSORTEDNORMAL = 0xA,
HIS_ICONSORTEDHOT = 0xB,
HIS_ICONSORTEDPRESSED = 0xC,
};
