enum exception_type : __int32
{
EXCEPTION_BAD_ALLOC = 0x0,
EXCEPTION_SCHEDULER_RESOURCE_ALLOCATION_ERROR = 0x1,
EXCEPTION_IMPROPER_LOCK = 0x2,
EXCEPTION_INVALID_SCHEDULER_POLICY_KEY = 0x3,
EXCEPTION_INVALID_SCHEDULER_POLICY_VALUE = 0x4,
EXCEPTION_INVALID_SCHEDULER_POLICY_THREAD_SPECIFICATION = 0x5,
EXCEPTION_IMPROPER_SCHEDULER_ATTACH = 0x6,
EXCEPTION_IMPROPER_SCHEDULER_DETACH = 0x7,
};
