enum gpos_lookup_type : __int32
{
GPOS_LOOKUP_ADJUST_SINGLE = 0x1,
GPOS_LOOKUP_ADJUST_PAIR = 0x2,
GPOS_LOOKUP_ATTACH_CURSIVE = 0x3,
GPOS_LOOKUP_ATTACH_MARK_TO_BASE = 0x4,
GPOS_LOOKUP_ATTACH_MARK_TO_LIGATURE = 0x5,
GPOS_LOOKUP_ATTACH_MARK_TO_MARK = 0x6,
GPOS_LOOKUP_POSITION_CONTEXT = 0x7,
GPOS_LOOKUP_POSITION_CONTEXT_CHAINED = 0x8,
GPOS_LOOKUP_POSITION_EXTENSION = 0x9,
};
