enum PresentationInterval : __int32
{
PRESENT_INTERVAL_IMMEDIATE = 0x0,
PRESENT_INTERVAL_ONE = 0x1,
PRESENT_INTERVAL_TWO = 0x2,
PRESENT_INTERVAL_THREE = 0x3,
PRESENT_INTERVAL_FOUR = 0x4,
PRESENT_INTERVAL_NUM = 0x5,
};
