enum PROGRESSPARTS_0 : __int32
{
PP_BAR_0 = 0x1,
PP_BARVERT_0 = 0x2,
PP_CHUNK_0 = 0x3,
PP_CHUNKVERT_0 = 0x4,
PP_FILL = 0x5,
PP_FILLVERT = 0x6,
PP_PULSEOVERLAY = 0x7,
PP_MOVEOVERLAY = 0x8,
PP_PULSEOVERLAYVERT = 0x9,
PP_MOVEOVERLAYVERT = 0xA,
PP_TRANSPARENTBAR = 0xB,
PP_TRANSPARENTBARVERT = 0xC,
};
