enum SCROLLBARPARTS : __int32
{
SBP_ARROWBTN = 0x1,
SBP_THUMBBTNHORZ = 0x2,
SBP_THUMBBTNVERT = 0x3,
SBP_LOWERTRACKHORZ = 0x4,
SBP_UPPERTRACKHORZ = 0x5,
SBP_LOWERTRACKVERT = 0x6,
SBP_UPPERTRACKVERT = 0x7,
SBP_GRIPPERHORZ = 0x8,
SBP_GRIPPERVERT = 0x9,
SBP_SIZEBOX = 0xA,
};
