enum DISPLAYCONFIG_MODE_INFO_TYPE : __int32
{
DISPLAYCONFIG_MODE_INFO_TYPE_SOURCE = 0x1,
DISPLAYCONFIG_MODE_INFO_TYPE_TARGET = 0x2,
DISPLAYCONFIG_MODE_INFO_TYPE_DESKTOP_IMAGE = 0x3,
DISPLAYCONFIG_MODE_INFO_TYPE_FORCE_UINT32 = 0xFFFFFFFF,
};
