struct TESEffectShaderData
{
unsigned __int8 cFlags;
unsigned __int8 padding_01[3];
unsigned int eTextureBlendModeSource;
unsigned int eTextureBlendOperation;
unsigned int eTextureZTestFunction;
unsigned int iFillColor;
float fFillAlphaFadeInTime;
float fFillAlphaFullTime;
float fFillAlphaFadeOutTime;
float fFillAlphaPersistentPercent;
float fFillAlphaPulseAmplitude;
float fFillAlphaPulseFrequency;
float fFillTextureUAnimSpeed;
float fFillTextureVAnimSpeed;
float fEdgeExponentValue;
unsigned int iEdgeColor;
float fEdgeAlphaFadeInTime;
float fEdgeAlphaFullTime;
float fEdgeAlphaFadeOutTime;
float fEdgeAlphaPersistentPercent;
float fEdgeAlphaPulseAmplitude;
float fEdgeAlphaPulseFrequency;
float fFillAlphaFullPercent;
float fEdgeAlphaFullPercent;
unsigned int eTextureBlendModeDest;
unsigned int eParticleBlendModeSource;
unsigned int eParticleBlendOperation;
unsigned int eParticleZTestFunction;
unsigned int eParticleBlendModeDest;
float fParticleFadeInTime;
float fParticleFullTime;
float fParticleFadeOutTime;
float fParticleFull;
float fParticlePersistent;
float fParticleLifetime;
float fParticleLifeVar;
float fParticleNormalSpeed;
float fParticleNormalAcc;
NiPoint3 ParticleVelocity;
NiPoint3 ParticleAcceleration;
float fParticleScale1;
float fParticleScale2;
float fParticleScale1Time;
float fParticleScale2Time;
unsigned int iParticleColor1;
unsigned int iParticleColor2;
unsigned int iParticleColor3;
float fParticleColor1Alpha;
float fParticleColor2Alpha;
float fParticleColor3Alpha;
float fParticleColor1Time;
float fParticleColor2Time;
float fParticleColor3Time;
};
