struct __cppobj NiDX9RenderStateVtbl
{
NiRefObjectVtbl super;
void (__thiscall *UpdateRenderState)(NiDX9RenderState this, const NiPropertyState *pkNew);
void (__thiscall *SetAlpha)(NiDX9RenderState this, void *AlphaProperty);
void (__thiscall *SetDither)(NiDX9RenderState this, void *DitherProperty);
void (__thiscall *SetFog)(NiDX9RenderState this, void *FogProperty);
void (__thiscall *SetMaterial)(NiDX9RenderState this, void *u1);
void (__thiscall *SetShadeMode)(NiDX9RenderState this, void *ShadeProperty);
void (__thiscall *SetSpecular)(NiDX9RenderState this, void *SpecularProperty);
void (__thiscall *SetStencil)(NiDX9RenderState this, void *StencilProperty);
void (__thiscall *SetWireframe)(NiDX9RenderState this, void *WireframeProperty);
void (__thiscall *SetZBuffer)(NiDX9RenderState this, void *ZBufferProperty);
void (__thiscall *RestoreAlpha)(NiDX9RenderState this);
void (__thiscall *SetVertexBlending)(NiDX9RenderState this, UInt16 u1);
void (__thiscall *SetNormalization)(NiDX9RenderState this, void *u1);
void (__thiscall *func_0E)(NiDX9RenderState this, UInt32 u1);
float (__thiscall *GetVar088)(NiDX9RenderState this);
void (__thiscall *func_10)(NiDX9RenderState this, float u1);
void (__thiscall *func_11)(NiDX9RenderState this, float u1, float u2);
UInt8 (__thiscall *GetLeftHanded)(NiDX9RenderState this);
void (__thiscall *func_13)(NiDX9RenderState this, UInt8 u1);
void (__thiscall *func_14)(NiDX9RenderState this, UInt32 u1);
void (__thiscall *InitializeRenderStates)(NiDX9RenderState this);
void (__thiscall *BackUpAllStates)(NiDX9RenderState this);
void (__thiscall *RestoreRenderState)(NiDX9RenderState this, D3DRENDERSTATETYPE state);
void (__thiscall *RestoreAllRenderStates)(NiDX9RenderState this);
void (__thiscall *SetRenderState)(NiDX9RenderState this, D3DRENDERSTATETYPE state, UInt32 value, UInt8 BackUp);
UInt32 (__thiscall *GetRenderState)(NiDX9RenderState this, D3DRENDERSTATETYPE state);
void (__thiscall *ClearPixelShaders)(NiDX9RenderState this);
void (__thiscall *BackUpPixelShader)(NiDX9RenderState this);
void (__thiscall *func_1D)(NiDX9RenderState this);
void (__thiscall *SetPixelShader)(NiDX9RenderState this, IDirect3DPixelShader9 *PixelShader, UInt8 BackUp);
IDirect3DPixelShader9 *(__thiscall *GetPixelShader)(NiDX9RenderState this);
void (__thiscall *RestorePixelShader)(NiDX9RenderState this);
void (__thiscall *RemovePixelShader)(NiDX9RenderState this, IDirect3DPixelShader9 *PixelShader);
void (__thiscall *SetVertexShader)(NiDX9RenderState this, IDirect3DVertexShader9 *pShader, UInt8 BackUp);
IDirect3DVertexShader9 *(__thiscall *GetVertexShader)(NiDX9RenderState this);
void (__thiscall *RestoreVertexShader)(NiDX9RenderState this);
void (__thiscall *RemoveVertexShader)(NiDX9RenderState *self, IDirect3DVertexShader9 *shader);
void (__thiscall *SetFVF)(NiDX9RenderState this, UInt32 FVF, UInt8 BackUp);
UInt32 (__thiscall *GetFVF)(NiDX9RenderState this);
void (__thiscall *RestoreFVF)(NiDX9RenderState this);
void (__thiscall *ClearFVF)(NiDX9RenderState this, UInt32 FVF);
void (__thiscall *SetVertexDeclaration)(NiDX9RenderState this, IDirect3DVertexDeclaration9 *pDecl, UInt8 BackUp);
IDirect3DVertexDeclaration9 *(__thiscall *GetVertexDeclaration)(NiDX9RenderState this);
void (__thiscall *RestoreVertexDeclaration)(NiDX9RenderState this);
void (__thiscall *ClearVertexDeclatation)(NiDX9RenderState this, IDirect3DVertexDeclaration9 *pDecl);
void (__thiscall *func_02E)(NiDX9RenderState this);
void (__thiscall *func_02F)(NiDX9RenderState this);
void (__thiscall *func_030)(NiDX9RenderState this);
void (__thiscall *func_031)(NiDX9RenderState this);
void (__thiscall *SetTextureStageState)(NiDX9RenderState this, UInt32 Stage, D3DTEXTURESTAGESTATETYPE Type, UInt32 Value, UInt8 BackUp);
UInt32 (__thiscall *GetTextureStageState)(NiDX9RenderState this, UInt32 Stage, D3DTEXTURESTAGESTATETYPE Type);
HRESULT (__thiscall *SetSamplerState)(NiDX9RenderState this, UInt32 Sampler, D3DSAMPLERSTATETYPE Type, UInt32 Value, UInt8 BackUp);
UInt32 (__thiscall *GetSamplerState)(NiDX9RenderState this, UInt32 Sampler, D3DSAMPLERSTATETYPE Type);
void (__thiscall *RestoreSamplerState)(NiDX9RenderState this, UInt32 Sampler, D3DSAMPLERSTATETYPE Type);
void (__thiscall *ClearTextureList)(NiDX9RenderState this);
void (__thiscall *SetTexture)(NiDX9RenderState this, UInt32 Sampler, IDirect3DBaseTexture9 *pTexture);
IDirect3DBaseTexture9 *(__thiscall *GetTexture)(NiDX9RenderState this, UInt32 Sampler);
void (__thiscall *RemoveTexture)(NiDX9RenderState this, IDirect3DBaseTexture9 *pTexture);
void (__thiscall *SetSoftwareVertexProcessing)(NiDX9RenderState *self, unsigned __int8 enabled);
unsigned __int8 (__thiscall *GetSoftwareVertexProcessing)(NiDX9RenderState *self);
void (__thiscall *SetVar_0FF4)(NiDX9RenderState this, UInt8 u1);
UInt8 (__thiscall *GetVar_0FF4)(NiDX9RenderState this);
void (__thiscall *SetVar_0FF5)(NiDX9RenderState this, UInt8 u1);
UInt8 (__thiscall *GetVar_0FF5)(NiDX9RenderState this);
void (__thiscall *Reset)(NiDX9RenderState this);
void (__thiscall *func_042)(NiDX9RenderState this);
};
