int __usercall MagicCaster_ApplyActiveMagicItem_::EffectLoop_T2InedbibleIngred@<eax>(
        int a1@<ebp>,
        int a2@<edi>,
        int a3@<esi>,
        char al0@<al>,
        char ch0@<ch>,
        TESObjectREFR *ebx0@<ebx>,
        int a7,
        int a8,
        int a9,
        int a10,
        int a11,
        int a12,
        int a13,
        int a14,
        float a15,
        float a16,
        int a17,
        int a18,
        int a19,
        int a20,
        int a21,
        __int64 a22,
        int a23,
        int a24,
        int a25,
        int a26,
        int a27,
        int a28,
        int a29,
        int a30,
        int a31,
        int a32,
        int a33,
        int a34,
        int a35,
        int a36,
        int a37)
{
  float v38; // [esp+0h] [ebp-20h]
  float v39; // [esp+4h] [ebp-1Ch]
  float v40; // [esp+10h] [ebp-10h]
  float v41; // [esp+14h] [ebp-Ch]
  float v42; // [esp+18h] [ebp-8h]

  if ( al0 )
    return MagicCaster_ApplyActiveMagicItem_::EffectLoop_T3InedbibleIngred(
             a1,
             a2,
             a3,
             ch0,
             ebx0,
             a7,
             a8,
             a9,
             a10,
             a11,
             a12,
             a13,
             a14,
             SLODWORD(a15),
             SLODWORD(a16),
             a17,
             *(float *)&a18,
             a19,
             a20,
             a21,
             a22,
             SHIDWORD(a22),
             a23,
             a24,
             a25,
             a26,
             a27,
             a28,
             a29,
             a30,
             a31,
             a32,
             a33,
             a34,
             *(float *)&a35,
             a36,
             a37);
  if ( (ch0 & 1) == 0 )
    return MagicCaster_ApplyActiveMagicItem_::EffectLoop_T3InedbibleIngred_(
             0,
             a1,
             a2,
             a3,
             ch0,
             ebx0,
             a7,
             a8,
             a9,
             a10,
             a11,
             a12,
             a13,
             a14,
             SLODWORD(a15),
             SLODWORD(a16),
             a17,
             *(float *)&a18,
             a19,
             a20,
             a21,
             a22,
             SHIDWORD(a22),
             a23,
             a24,
             a25,
             a26,
             a27,
             a28,
             a29,
             a30,
             a31,
             a32,
             a33,
             a34,
             *(float *)&a35,
             a36,
             a37);
  __asm { fst     [esp+10h+var_8]; float }
  __asm
  {
    fst     [esp+10h+var_C]; float
    fstp    [esp+10h+var_10]; float
  }
  __asm { fld     [esp+14h+arg_74] }
  __asm
  {
    fstp    [esp+20h+var_1C]; float
    fld     [esp+20h+arg_2C]
    fstp    [esp+20h+var_20]; float
  }
  Calc_T2PotionStrength(&a15, v38, v39, 6, 0, v40, v41, v42, 0);
  return MagicCaster_ApplyActiveMagicItem_::EffectLoop_InedbibleIngredFinish(
           a1,
           a2,
           a3,
           ebx0,
           a7,
           a8,
           a9,
           a10,
           a11,
           a12,
           a13,
           a14,
           a15,
           a16,
           a17,
           a18,
           a19,
           a20,
           a21,
           a22,
           a23,
           a24,
           a25,
           a26,
           a27,
           a28,
           a29,
           a30,
           a31,
           a32,
           a33,
           a34,
           a35,
           a36,
           a37);
}
