enum _D3DQUERYTYPE
{
D3DQUERYTYPE_VCACHE = 0x4,
D3DQUERYTYPE_RESOURCEMANAGER = 0x5,
D3DQUERYTYPE_VERTEXSTATS = 0x6,
D3DQUERYTYPE_EVENT = 0x8,
D3DQUERYTYPE_OCCLUSION = 0x9,
D3DQUERYTYPE_TIMESTAMP = 0xA,
D3DQUERYTYPE_TIMESTAMPDISJOINT = 0xB,
D3DQUERYTYPE_TIMESTAMPFREQ = 0xC,
D3DQUERYTYPE_PIPELINETIMINGS = 0xD,
D3DQUERYTYPE_INTERFACETIMINGS = 0xE,
D3DQUERYTYPE_VERTEXTIMINGS = 0xF,
D3DQUERYTYPE_PIXELTIMINGS = 0x10,
D3DQUERYTYPE_BANDWIDTHTIMINGS = 0x11,
D3DQUERYTYPE_CACHEUTILIZATION = 0x12,
D3DQUERYTYPE_MEMORYPRESSURE = 0x13,
};
