enum _PS_ATTRIBUTE_NUM : __int32
{
PsAttributeParentProcess = 0x0,
PsAttributeDebugPort = 0x1,
PsAttributeToken = 0x2,
PsAttributeClientId = 0x3,
PsAttributeTebAddress = 0x4,
PsAttributeImageName = 0x5,
PsAttributeImageInfo = 0x6,
PsAttributeMemoryReserve = 0x7,
PsAttributePriorityClass = 0x8,
PsAttributeErrorMode = 0x9,
PsAttributeStdHandleInfo = 0xA,
PsAttributeHandleList = 0xB,
PsAttributeGroupAffinity = 0xC,
PsAttributePreferredNode = 0xD,
PsAttributeIdealProcessor = 0xE,
PsAttributeUmsThread = 0xF,
PsAttributeMitigationOptions = 0x10,
PsAttributeProtectionLevel = 0x11,
PsAttributeSecureProcess = 0x12,
PsAttributeJobList = 0x13,
PsAttributeChildProcessPolicy = 0x14,
PsAttributeAllApplicationPackagesPolicy = 0x15,
PsAttributeWin32kFilter = 0x16,
PsAttributeSafeOpenPromptOriginClaim = 0x17,
PsAttributeBnoIsolation = 0x18,
PsAttributeDesktopAppPolicy = 0x19,
PsAttributeChpe = 0x1A,
PsAttributeMax = 0x1B,
};
