// local variable allocation has failed, the output may be wrong!
int __userpurge TESLeveledList_CalcLeveledForm_::CalcForEachItemInCount@<eax>(
        TESObject *a1@<ebx>,
        unsigned __int16 a2@<si>,
        unsigned __int8 *a3@<ebp>,
        int a4,
        int a5,
        int a6,
        TESObject *a7,
        int a8,
        int a9,
        int a10,
        int a11,
        int a12,
        int a13,
        int a14,
        int a15,
        int a16,
        int a17,
        TESObject *a18,
        int a19,
        TESObject *a20,
        int a21)
{
  if ( a2 <= (int)a1 ) /*0x46ce85*/
    return TESLeveledList_CalcLeveledForm_::SetReturnValues( /*0x46ce85*/
             (int)a1,
             (int)a3,
             a4,
             a5,
             a6,
             (int)a7,
             a8,
             a9,
             a10,
             a11,
             a12,
             a13,
             a14,
             a15,
             a16,
             a17,
             (int)a18,
             a19,
             (int)a20,
             a21);
  else
    return TESLeveledList_CalcLeveledForm_::CalcForEachItemInCount_Loop( /*0x46ce8f*/
             a1,
             a3,
             a4,
             a5,
             a6,
             a7,
             a8,
             a9,
             a2,
             a11,
             a12,
             *(TESContainer *)&a13,
             a17,
             a18,
             a19,
             a20,
             a21);
}
