struct _TEB64
{
NT_TIB64 Tib;
ULONG64 EnvironmentPointer;
CLIENT_ID64 ClientId;
ULONG64 ActiveRpcHandle;
ULONG64 ThreadLocalStoragePointer;
ULONG64 Peb;
ULONG LastErrorValue;
ULONG CountOfOwnedCriticalSections;
ULONG64 CsrClientThread;
ULONG64 Win32ThreadInfo;
ULONG User32Reserved[26];
ULONG UserReserved[5];
__declspec(align(8)) ULONG64 WOW32Reserved;
ULONG CurrentLocale;
ULONG FpSoftwareStatusRegister;
ULONG64 ReservedForDebuggerInstrumentation[16];
ULONG64 SystemReserved1[30];
char PlaceholderCompatibilityMode;
char PlaceholderReserved[11];
DWORD ProxiedProcessId;
ACTIVATION_CONTEXT_STACK64 ActivationContextStack;
UCHAR WorkingOnBehalfOfTicket[8];
LONG ExceptionCode;
__declspec(align(8)) ULONG64 ActivationContextStackPointer;
ULONG64 InstrumentationCallbackSp;
ULONG64 InstrumentationCallbackPreviousPc;
ULONG64 InstrumentationCallbackPreviousSp;
ULONG TxFsContext;
BOOLEAN InstrumentationCallbackDisabled;
ULONG64 GdiTebBatch[157];
CLIENT_ID64 RealClientId;
ULONG64 GdiCachedProcessHandle;
ULONG GdiClientPID;
ULONG GdiClientTID;
ULONG64 GdiThreadLocaleInfo;
ULONG64 Win32ClientInfo[62];
ULONG64 glDispatchTable[233];
ULONG64 glReserved1[29];
ULONG64 glReserved2;
ULONG64 glSectionInfo;
ULONG64 glSection;
ULONG64 glTable;
ULONG64 glCurrentRC;
ULONG64 glContext;
ULONG LastStatusValue;
UNICODE_STRING64 StaticUnicodeString;
WCHAR_0 StaticUnicodeBuffer[261];
__declspec(align(8)) ULONG64 DeallocationStack;
ULONG64 TlsSlots[64];
LIST_ENTRY64 TlsLinks;
ULONG64 Vdm;
ULONG64 ReservedForNtRpc;
ULONG64 DbgSsReserved[2];
ULONG HardErrorDisabled;
__declspec(align(8)) ULONG64 Instrumentation[16];
ULONG64 WinSockData;
ULONG GdiBatchCount;
ULONG Spare2;
ULONG GuaranteedStackBytes;
__declspec(align(8)) ULONG64 ReservedForPerf;
ULONG64 ReservedForOle;
ULONG WaitingOnLoaderLock;
__declspec(align(8)) ULONG64 Reserved5[3];
ULONG64 TlsExpansionSlots;
ULONG64 DeallocationBStore;
ULONG64 BStoreLimit;
ULONG ImpersonationLocale;
ULONG IsImpersonating;
ULONG64 NlsCache;
ULONG64 ShimData;
ULONG HeapVirtualAffinity;
__declspec(align(8)) ULONG64 CurrentTransactionHandle;
ULONG64 ActiveFrame;
ULONG64 FlsSlots;
ULONG64 PreferredLanguages;
ULONG64 UserPrefLanguages;
ULONG64 MergedPrefLanguages;
ULONG MuiImpersonation;
USHORT CrossTebFlags;
USHORT SameTebFlags;
ULONG64 TxnScopeEnterCallback;
ULONG64 TxnScopeExitCallback;
ULONG64 TxnScopeContext;
ULONG LockCount;
LONG WowTebOffset;
ULONG64 ResourceRetValue;
ULONG64 ReservedForWdf;
ULONGLONG ReservedForCrt;
GUID EffectiveContainerId;
};
