struct /*VFT*/ BaseProcess_vtbl
{
void (__thiscall *Destructor)(BaseProcess *__hidden this);
void (__thiscall *Copy)(BaseProcess *__hidden this, BaseProcess *oth);
UInt32 (__thiscall *GetProcessLevel)(BaseProcess *__hidden this);
void (__thiscall *Unk_03)(BaseProcess *__hidden this, Actor *act, UInt32 arg1);
void (__thiscall *ManagePackProcedure)(BaseProcess *__hidden this, Actor *arg0);
void (__thiscall *Unk_05)(BaseProcess *__hidden this, UInt32 arg0, UInt32 arg1);
bool (__thiscall *Unk_06)(BaseProcess *__hidden this, UInt32 arg0, UInt32 arg1);
void (__thiscall *SetCurHour)(BaseProcess *__hidden this, float hour);
void (__thiscall *Unk_08)(BaseProcess *__hidden this);
bool (__thiscall *Unk_09)(BaseProcess *__hidden this);
float (__thiscall *GetCurHour)(BaseProcess *__hidden this);
UInt32 (__thiscall *GetCurPackedDate)(BaseProcess *__hidden this);
void (__thiscall *SetCurPackedDate)(BaseProcess *__hidden this, UInt32 arg0);
UInt32 (__thiscall *GetCurDay)(BaseProcess *__hidden this);
UInt32 (__thiscall *GetCurMonth)(BaseProcess *__hidden this);
UInt32 (__thiscall *GetCurYear)(BaseProcess *__hidden this);
void (__thiscall *Unk_10)(BaseProcess *__hidden this, UInt32 arg0);
UInt32 (__thiscall *Unk_11)(BaseProcess *__hidden this);
void (__thiscall *Unk_12)(BaseProcess *__hidden this, UInt32 arg0);
void (__thiscall *Unk_13)(BaseProcess *__hidden this);
UInt32 (__thiscall *Unk_14)(BaseProcess *__hidden this);
void (__thiscall *Unk_15)(BaseProcess *__hidden this, UInt32 arg0);
void (__thiscall *Unk_16)(BaseProcess *__hidden this, UInt32 arg0, UInt32 arg1);
void (__thiscall *Unk_17)(BaseProcess *__hidden this);
void (__thiscall *Unk_18)(BaseProcess *__hidden this, UInt32 arg0);
bool (__thiscall *Unk_19)(BaseProcess *__hidden this);
void (__thiscall *Unk_1A)(BaseProcess *__hidden this, UInt32 arg0);
bool (__thiscall *Unk_1B)(BaseProcess *__hidden this, UInt32 arg0, UInt32 arg1);
void (__thiscall *Unk_1C)(BaseProcess *__hidden this, UInt32 arg0, UInt32 arg1, UInt32 arg2);
UInt32 (__thiscall *Unk_1D)(BaseProcess *__hidden this, UInt32 arg0);
UInt32 (__thiscall *Unk_1E)(BaseProcess *__hidden this, UInt32 arg0);
float (__thiscall *Unk_1F)(BaseProcess *__hidden this, UInt32 arg0);
void (__thiscall *Unk_20)(BaseProcess *__hidden this, UInt32 arg0, UInt32 arg1);
void (__thiscall *Unk_21)(BaseProcess *__hidden this, UInt32 arg0, UInt32 arg1, UInt32 arg2);
bool (__thiscall *Unk_22)(BaseProcess *__hidden this);
void (__thiscall *Unk_23)(BaseProcess *__hidden this, UInt32 arg0);
void (__thiscall *Unk_24)(BaseProcess *__hidden this, UInt32 arg0);
void (__thiscall *Unk_25)(BaseProcess *__hidden this);
void (__thiscall *UpdateUnk088)(BaseProcess *__hidden this);
float (__thiscall *GetUnk088)(BaseProcess *__hidden this);
void (__thiscall *SetUnk088)(BaseProcess *__hidden this, float arg0);
void (__thiscall *Unk_29)(BaseProcess *__hidden this);
void *(__thiscall *SetDetected)(BaseProcess *__hidden this, Actor *detectedActor, UInt8 detectionState, bool hasLOS, SInt32 detectionLevel);
bool (__thiscall *Unk_2B)(BaseProcess *__hidden this);
void (__thiscall *Unk_2C)(BaseProcess *__hidden this, UInt32 arg0);
void (__thiscall *Unk_2C_1_2)(BaseProcess *__hidden this);
void (__thiscall *Unk_2D)(BaseProcess *__hidden this, UInt32 arg0);
void (__thiscall *SetProcedureCompleted)(BaseProcess *this, bool completed);
bool (__thiscall *IsProcedureCompleted)(BaseProcess *__hidden this);
void (__thiscall *Unk_30)(BaseProcess *__hidden this, UInt32 arg0);
bool (__thiscall *Unk_31)(BaseProcess *__hidden this);
TESObjectREFR *(__thiscall *GetUnk02C)(BaseProcess *__hidden this);
void (__thiscall *SetUnk02C)(BaseProcess *__hidden this, TESObjectREFR *obj);
UInt32 (__thiscall *Unk_34)(BaseProcess *__hidden this);
void (__thiscall *Unk_35)(BaseProcess *__hidden this, UInt32 arg0);
void (__thiscall *Unk_36)(BaseProcess *__hidden this, UInt32 arg0);
UInt32 (__thiscall *Unk_37)(BaseProcess *__hidden this);
void (__thiscall *Unk_38)(BaseProcess *__hidden this, UInt32 arg0);
UInt32 (__thiscall *Unk_39)(BaseProcess *__hidden this, UInt32 arg0);
EntryData *(__thiscall *GetEquippedWeaponData)(BaseProcess *__hidden this, bool arg0);
EntryData *(__thiscall *GetEquippedLightData)(BaseProcess *__hidden this, bool arg0);
EntryData *(__thiscall *GetEquippedAmmoData)(BaseProcess *__hidden this, bool arg0);
EntryData *(__thiscall *GetEquippedShieldData)(BaseProcess *__hidden this, bool arg0);
UInt32 (__thiscall *GetAV)(BaseProcess *__hidden this, UInt32 arg0, UInt32 arg1);
UInt32 (__thiscall *SetAV)(BaseProcess *__hidden this, UInt32 arg0);
UInt32 (__thiscall *SetEquippedWeaponData)(BaseProcess *__hidden this, EntryData *arg0);
UInt32 (__thiscall *SetEquippedLightData)(BaseProcess *__hidden this, EntryData *arg0);
UInt32 (__thiscall *setEquippedAmmoData)(BaseProcess *__hidden this, EntryData *arg0);
UInt32 (__thiscall *SetEquippedShieldData)(BaseProcess *__hidden this, EntryData *arg0);
bool (__thiscall *Unk_44)(BaseProcess *__hidden this, UInt32 arg0);
UInt32 (__thiscall *Unk_45)(BaseProcess *__hidden this, UInt32 arg0);
UInt32 (__thiscall *Unk_46)(BaseProcess *__hidden this, UInt32 arg0);
UInt32 (__thiscall *Unk_47)(BaseProcess *__hidden this, UInt32 arg0);
UInt32 (__thiscall *Unk_48)(BaseProcess *__hidden this, UInt32 arg0);
UInt32 (__thiscall *Unk_49)(BaseProcess *__hidden this, UInt32 arg0);
UInt32 (__thiscall *Unk_4A)(BaseProcess *__hidden this, UInt32 arg0);
UInt32 (__thiscall *Unk_4B)(BaseProcess *__hidden this, UInt32 arg0);
UInt32 (__thiscall *Unk_4C)(BaseProcess *__hidden this, UInt32 arg0);
bool (__thiscall *Unk_4D)(BaseProcess *__hidden this);
bool (__thiscall *Unk_4E)(BaseProcess *__hidden this);
UInt8 (__thiscall *GetUnk084)(BaseProcess *__hidden this);
void (__thiscall *SetUnk084)(BaseProcess *__hidden this, UInt8 arg0);
bool (__thiscall *GetUnk01E)(BaseProcess *__hidden this);
void (__thiscall *SetUnk01E)(BaseProcess *__hidden this, UInt32 arg0);
void (__thiscall *Unk_53)(BaseProcess *__hidden this, UInt32 arg0, UInt32 arg1, UInt32 arg2, UInt32 arg3);
void (__thiscall *SetUnk024)(BaseProcess *__hidden this, UInt32 arg);
void (__thiscall *Unk_55)(BaseProcess *__hidden this);
void (__thiscall *Unk_56)(BaseProcess *__hidden this);
void (__thiscall *Unk_57)(BaseProcess *__hidden this);
void (__thiscall *GetUnk028)(BaseProcess *__hidden this, float arg);
float (__thiscall *SetUnk028)(BaseProcess *__hidden this);
void (__thiscall *Unk_5A)(BaseProcess *__hidden this);
void (__thiscall *Unk_5B)(BaseProcess *__hidden this);
void (__thiscall *Unk_5C)(BaseProcess *__hidden this);
void (__thiscall *SetCurrentPackage)(BaseProcess *__hidden this, TESPackage *package);
void (__thiscall *SetCurrentPackProcedure)(BaseProcess *__hidden this, eProcedure proceudre);
eProcedure (__thiscall *GetCurrentPackProcedure)(BaseProcess *__hidden this);
TESPackage *(__thiscall *GetCurrentPackage)(BaseProcess *__hidden this);
void (__thiscall *Unk_61)(BaseProcess *__hidden this, UInt32 arg0);
bhkCharacterProxy **(__thiscall *GetCharProxy)(BaseProcess *__hidden this, bhkCharacterProxy **characterProxy);
void (__thiscall *Unk_63)(BaseProcess *__hidden this, void *obj);
void (__thiscall *Unk_64)(BaseProcess *__hidden this);
void (__thiscall *Unk_65)(BaseProcess *__hidden this);
void (__thiscall *Unk_66)(BaseProcess *__hidden this);
void (__thiscall *Unk_67)(BaseProcess *__hidden this);
void (__thiscall *SayTopic)(BaseProcess *__hidden this, Actor *speaker, TESTopic *topic, bool bForceSubtitles, UInt32 unk3, UInt32 unk4);
void (__thiscall *Unk_69)(BaseProcess *__hidden this);
void (__thiscall *Unk_6A)(BaseProcess *__hidden this);
void (__thiscall *Unk_6B)(BaseProcess *__hidden this);
void (__thiscall *Unk_6C)(BaseProcess *__hidden this);
void (__thiscall *Unk_6D)(BaseProcess *__hidden this);
void (__thiscall *Unk_6E)(BaseProcess *__hidden this);
void (__thiscall *Unk_6F)(BaseProcess *__hidden this);
void (__thiscall *Unk_70)(BaseProcess *__hidden this);
bool (__thiscall *GetLOS)(BaseProcess *__hidden this, UInt32 arg0, TESObjectREFR *target);
void (__thiscall *Unk_72)(BaseProcess *__hidden this);
void (__thiscall *Unk_73)(BaseProcess *__hidden this);
void (__thiscall *Unk_74)(BaseProcess *__hidden this);
void (__thiscall *Unk_75)(BaseProcess *__hidden this);
void (__thiscall *Unk_76)(BaseProcess *__hidden this);
void (__thiscall *Unk_77)(BaseProcess *__hidden this);
void (__thiscall *Unk_78)(BaseProcess *__hidden this);
void (__thiscall *Unk_79)(BaseProcess *__hidden this);
void (__thiscall *Unk_7A)(BaseProcess *__hidden this);
void (__thiscall *Unk_7B)(BaseProcess *__hidden this);
void (__thiscall *Unk_7C)(BaseProcess *__hidden this);
void (__thiscall *Unk_7D)(BaseProcess *__hidden this);
void (__thiscall *Unk_7E)(BaseProcess *__hidden this);
void (__thiscall *Unk_7F)(BaseProcess *__hidden this);
void (__thiscall *Unk_80)(BaseProcess *__hidden this);
void (__thiscall *Unk_81)(BaseProcess *__hidden this);
void (__thiscall *Unk_82)(BaseProcess *__hidden this);
UInt8 (__thiscall *GetIsAlerted)(BaseProcess *__hidden this);
void (__thiscall *SetIsAlerted)(BaseProcess *__hidden this, UInt8 arg);
void (__thiscall *Unk_85)(BaseProcess *__hidden this);
void (__thiscall *Unk_86)(BaseProcess *__hidden this);
void (__thiscall *Unk_87)(BaseProcess *__hidden this);
void (__thiscall *Unk_88)(BaseProcess *__hidden this);
void (__thiscall *Unk_89)(BaseProcess *__hidden this);
void (__thiscall *Unk_8A)(BaseProcess *__hidden this);
void (__thiscall *Unk_8B)(BaseProcess *__hidden this);
void (__thiscall *Unk_8C)(BaseProcess *__hidden this);
void (__thiscall *Unk_8D)(BaseProcess *__hidden this);
void (__thiscall *Unk_8E)(BaseProcess *__hidden this);
void (__thiscall *Unk_8F)(BaseProcess *__hidden this);
void (__thiscall *Unk_90)(BaseProcess *__hidden this);
UInt8 (__thiscall *GetUnk020)(BaseProcess *__hidden this);
void (__thiscall *SetUnk020)(BaseProcess *__hidden this, UInt8 arg);
void (__thiscall *Unk_93)(BaseProcess *__hidden this);
void (__thiscall *Unk_94)(BaseProcess *__hidden this);
void (__thiscall *Unk_95)(BaseProcess *__hidden this);
void (__thiscall *Unk_96)(BaseProcess *__hidden this);
void (__thiscall *Unk_97)(BaseProcess *__hidden this);
void (__thiscall *Unk_98)(BaseProcess *__hidden this);
void (__thiscall *Unk_99)(BaseProcess *__hidden this);
void (__thiscall *Unk_9A)(BaseProcess *__hidden this);
void (__thiscall *Unk_9B)(BaseProcess *__hidden this);
void (__thiscall *Unk_9C)(BaseProcess *__hidden this);
void (__thiscall *Unk_9D)(BaseProcess *__hidden this);
void (__thiscall *Unk_9E)(BaseProcess *__hidden this);
void (__thiscall *Unk_9F)(BaseProcess *__hidden this);
void (__thiscall *Unk_A0)(BaseProcess *__hidden this);
void (__thiscall *Unk_A1)(BaseProcess *__hidden this);
void (__thiscall *Unk_A2)(BaseProcess *__hidden this);
void (__thiscall *Unk_A3)(BaseProcess *__hidden this);
void (__thiscall *Unk_A4)(BaseProcess *__hidden this);
void (__thiscall *Unk_A5)(BaseProcess *__hidden this);
void (__thiscall *Unk_A6)(BaseProcess *__hidden this);
void (__thiscall *Unk_A7)(BaseProcess *__hidden this);
void (__thiscall *Unk_A8)(BaseProcess *__hidden this);
void (__thiscall *Unk_A9)(BaseProcess *__hidden this);
MagicItem *(__thiscall *GetQueuedMagicItem)(BaseProcess *__hidden this);
void (__thiscall *Unk_AB)(BaseProcess *__hidden this);
void (__thiscall *Unk_AC)(BaseProcess *__hidden this);
void (__thiscall *Unk_AD)(BaseProcess *__hidden this);
void (__thiscall *Unk_AE)(BaseProcess *__hidden this);
UInt32 (__thiscall *GetMovementFlags)(BaseProcess *__hidden this);
void (__thiscall *Unk_B0)(BaseProcess *__hidden this);
void (__thiscall *Unk_B1)(BaseProcess *__hidden this);
void (__thiscall *Unk_B2)(BaseProcess *__hidden this);
void (__thiscall *GetCurrentAction)(BaseProcess *__hidden this);
BSAnimGroupSequence *(__thiscall *GetCurrentActionAnimSequence)(BaseProcess *__hidden this);
UInt16 (__thiscall *SetCurrentAction)(BaseProcess *__hidden this, UInt16 action, BSAnimGroupSequence *sequence);
void (__thiscall *Unk_B6)(BaseProcess *__hidden this);
void (__thiscall *Unk_B7)(BaseProcess *__hidden this);
void (__thiscall *GetKnockedState)(BaseProcess *__hidden this);
UInt8 (__thiscall *SetKnockedState)(BaseProcess *__hidden this, UInt8 knockedState);
void (__thiscall *Unk_BA)(BaseProcess *__hidden this);
void (__thiscall *KnockbackActor)(BaseProcess *__hidden this, Actor *target, float arg1, float arg2, float arg3, float arg4);
void (__thiscall *Unk_BC)(BaseProcess *__hidden this);
void (__thiscall *Unk_BD)(BaseProcess *__hidden this);
UInt8 (__thiscall *GetCombatMode)(BaseProcess *__hidden this);
UInt8 (__thiscall *SetCombatMode)(BaseProcess *__hidden this, UInt8 mode);
UInt8 (__thiscall *GetWeaponOut)(BaseProcess *__hidden this);
UInt8 (__thiscall *SetWeaponOut)(BaseProcess *__hidden this, UInt8 out);
void (__thiscall *SetUnk20CInner)(BaseProcess *__hidden this);
Unk20C *(__thiscall *GetUnk20C)(BaseProcess *__hidden this);
void (__thiscall *InitUnk1A8Val)(BaseProcess *__hidden this);
void (__thiscall *Unk_C5)(BaseProcess *__hidden this);
void (__thiscall *SetUnk16C)(BaseProcess *__hidden this);
void (__thiscall *GetUnk16C)(BaseProcess *__hidden this);
void (__thiscall *GetUnk0F8)(BaseProcess *__hidden this);
void (__thiscall *SetUnk0F8)(BaseProcess *__hidden this);
void (__thiscall *Unk_CA)(BaseProcess *__hidden this, TESObjectREFR *unk);
void (__thiscall *Unk_CB)(BaseProcess *__hidden this, TESObjectREFR *unk);
void (__thiscall *GetUnk218)(BaseProcess *__hidden this);
void (__thiscall *SetUnk218)(BaseProcess *__hidden this);
void (__thiscall *GetUnk220Element)(BaseProcess *__hidden this);
void (__thiscall *SetUnk220Element)(BaseProcess *__hidden this);
void (__thiscall *StopSoundITMTorchHeldLP)(BaseProcess *__hidden this);
void (__thiscall *PlaySoundITMTorchHeldLP)(BaseProcess *__hidden this);
void (__thiscall *GetUnk278)(BaseProcess *__hidden this);
void (__thiscall *SetUnk278To0)(BaseProcess *__hidden this);
void (__thiscall *SetUnk2ACCallD5)(BaseProcess *__hidden this);
void (__thiscall *InitUnk2B0)(BaseProcess *__hidden this);
void (__thiscall *GetNearDetectionBonus)(BaseProcess *__hidden this);
void (__thiscall *GetUnk22C)(BaseProcess *__hidden this);
void (__thiscall *SetUnk22C)(BaseProcess *__hidden this);
void (__thiscall *Unk_D9)(BaseProcess *__hidden this);
UInt8 (__thiscall *GetSitSleepState)(BaseProcess *__hidden this);
void (__thiscall *SetSleepState)(BaseProcess *__hidden this, Actor *actor, UInt8 sleepState, TESObjectREFR *fornititure, UInt8 furnitureMarkerIndex);
SInt16 (__thiscall *GetFurnitureMarkerHeading)(BaseProcess *__hidden this);
TESFurniture *(__thiscall *GetFurniture)(BaseProcess *__hidden this);
void (__thiscall *GetFurnitureMarkerIndex)(BaseProcess *__hidden this);
void (__thiscall *GetUnk128)(BaseProcess *__hidden this);
UInt32 (__thiscall *Unk_E0)(BaseProcess *__hidden this);
void (__thiscall *GetUnk25C)(BaseProcess *__hidden this);
void (__thiscall *SetUnk25C)(BaseProcess *__hidden this, UInt8 a2);
UInt8 (__thiscall *GetUnk01C)(BaseProcess *__hidden this);
void (__thiscall *SetUnk01C)(BaseProcess *__hidden this, UInt8 arg);
void (__thiscall *GetUnk180)(BaseProcess *__hidden this);
void (__thiscall *SetUnk180)(BaseProcess *__hidden this);
void (__thiscall *Unk_E7)(BaseProcess *__hidden this);
void (__thiscall *GetUnk184)(BaseProcess *__hidden this);
void (__thiscall *SetUnk184)(BaseProcess *__hidden this);
float (__thiscall *GetLightAmount)(BaseProcess *__hidden this, Actor *actor, UInt32 unk1);
void *(__thiscall *GetDetectionState)(BaseProcess *__hidden this, Actor *target);
void (__thiscall *Unk_EC)(BaseProcess *__hidden this);
void (__thiscall *GetUnk030)(BaseProcess *__hidden this);
void (__thiscall *SetUnk030)(BaseProcess *__hidden this);
void (__thiscall *RemoveFornitureInteraction)(BaseProcess *__hidden this, Actor *act);
void (__thiscall *Unk_F0)(BaseProcess *__hidden this);
void (__thiscall *Unk_F1)(BaseProcess *__hidden this);
void (__thiscall *Unk_F2)(BaseProcess *__hidden this);
void (__thiscall *Unk_F3)(BaseProcess *__hidden this);
void (__thiscall *Unk_F4)(BaseProcess *__hidden this);
void (__thiscall *Unk_F5)(BaseProcess *__hidden this);
void (__thiscall *Unk_F6)(BaseProcess *__hidden this);
void (__thiscall *Unk_F7)(BaseProcess *__hidden this);
void (__thiscall *Unk_F8)(BaseProcess *__hidden this);
void (__thiscall *Unk_F9)(BaseProcess *__hidden this);
void (__thiscall *Unk_FA)(BaseProcess *__hidden this);
unsigned __int16 (__thiscall *GetSaveSize)(BaseProcess *, unsigned int changeMask, MobileObject *owner); ///< Verified process persistence virtual role: matching base/low/middle-low overrides and save/load/reset bodies. Revert dispatch at MobileObject 65A835 supplies mask and owner.
void (__thiscall *SaveGame)(BaseProcess *, unsigned int changeMask, MobileObject *owner); ///< Verified process persistence virtual role: matching base/low/middle-low overrides and save/load/reset bodies. Revert dispatch at MobileObject 65A835 supplies mask and owner.
void (__thiscall *LoadGame)(BaseProcess *, unsigned int changeMask, unsigned int currentFlags, MobileObject *owner); ///< Verified process persistence virtual role: matching base/low/middle-low overrides and save/load/reset bodies. Revert dispatch at MobileObject 65A835 supplies mask and owner.
void (__thiscall *InitLoadGame)(BaseProcess *, unsigned int changeMask, unsigned int currentFlags, MobileObject *owner); ///< Probable lifecycle phase name from local post-load fixup behavior and Fallout comparison. Verified ECX/three-stack-word ABI and concrete base/low implementations. External scheduling not fully audited.
void (__thiscall *FinishInitLoadGame)(BaseProcess *, unsigned int changeMask, unsigned int currentFlags, MobileObject *owner); ///< Probable lifecycle phase name from local post-load fixup behavior and Fallout comparison. Verified ECX/three-stack-word ABI and concrete base/low implementations. External scheduling not fully audited.
void (__thiscall *Revert)(BaseProcess *, unsigned int changeMask, MobileObject *owner); ///< Verified process persistence virtual role: matching base/low/middle-low overrides and save/load/reset bodies. Revert dispatch at MobileObject 65A835 supplies mask and owner.
void (__thiscall *Unk_101)(BaseProcess *__hidden this);
PathLow *(__thiscall *CreatePath)(BaseProcess *__hidden this);
PathLow *(__thiscall *GetCurrentPath)(BaseProcess *__hidden this);
void (__thiscall *Unk_104)(BaseProcess *__hidden this);
void (__thiscall *Unk_105)(BaseProcess *__hidden this);
void (__thiscall *Unk_106)(BaseProcess *__hidden this);
void (__thiscall *Unk_107)(BaseProcess *__hidden this);
void (__thiscall *Unk_108)(BaseProcess *__hidden this);
void (__thiscall *Unk_109)(BaseProcess *__hidden this);
void (__thiscall *Unk_10A)(BaseProcess *__hidden this);
void (__thiscall *Unk_10B)(BaseProcess *__hidden this);
void (__thiscall *Unk_10C)(BaseProcess *__hidden this);
void (__thiscall *Unk_10D)(BaseProcess *__hidden this);
void (__thiscall *Unk_10E)(BaseProcess *__hidden this);
void (__thiscall *Unk_10F)(BaseProcess *__hidden this);
void (__thiscall *Unk_110)(BaseProcess *__hidden this);
void (__thiscall *Unk_111)(BaseProcess *__hidden this);
void (__thiscall *Unk_112)(BaseProcess *__hidden this);
void (__thiscall *Unk_113)(BaseProcess *__hidden this);
void (__thiscall *Unk_114)(BaseProcess *__hidden this);
void (__thiscall *Unk_115)(BaseProcess *__hidden this);
void (__thiscall *Unk_116)(BaseProcess *__hidden this);
void (__thiscall *Unk_117)(BaseProcess *__hidden this);
void (__thiscall *Unk_118)(BaseProcess *__hidden this);
void (__thiscall *Unk_119)(BaseProcess *__hidden this);
void (__thiscall *Unk_11A)(BaseProcess *__hidden this);
void (__thiscall *Unk_11B)(BaseProcess *__hidden this);
void (__thiscall *Unk_11C)(BaseProcess *__hidden this);
void (__thiscall *Unk_11D)(BaseProcess *__hidden this);
void (__thiscall *Unk_11E)(BaseProcess *__hidden this);
void (__thiscall *Unk_11F)(BaseProcess *__hidden this);
void (__thiscall *Unk_120)(BaseProcess *__hidden this);
void (__thiscall *Unk_121)(BaseProcess *__hidden this);
void (__thiscall *Unk_122)(BaseProcess *__hidden this);
void (__thiscall *Unk_123)(BaseProcess *__hidden this);
void (__thiscall *Unk_124)(BaseProcess *__hidden this);
void (__thiscall *Unk_125)(BaseProcess *__hidden this);
void (__thiscall *Unk_126)(BaseProcess *__hidden this);
void (__thiscall *Unk_127)(BaseProcess *__hidden this);
void (__thiscall *Unk_128)(BaseProcess *__hidden this);
void (__thiscall *Unk_129)(BaseProcess *__hidden this);
void (__thiscall *Unk_12A)(BaseProcess *__hidden this);
void (__thiscall *Unk_12B)(BaseProcess *__hidden this);
void (__thiscall *Unk_12C)(BaseProcess *__hidden this);
void (__thiscall *Unk_12D)(BaseProcess *__hidden this);
void (__thiscall *Unk_12E)(BaseProcess *__hidden this);
void (__thiscall *Unk_12F)(BaseProcess *__hidden this);
void (__thiscall *Unk_130)(BaseProcess *__hidden this);
void (__thiscall *Unk_131)(BaseProcess *__hidden this);
TESObjectREFR *(__thiscall *GetActionTarget)(BaseProcess *__hidden this, UInt32 actionType);
void (__thiscall *Unk_133)(BaseProcess *__hidden this);
const char *(__thiscall *Unk_134)(BaseProcess *__hidden this);
void (__thiscall *Unk_135)(BaseProcess *__hidden this);
void (__thiscall *Unk_136)(BaseProcess *__hidden this);
void (__thiscall *Unk_137)(BaseProcess *__hidden this);
void (__thiscall *Unk_138)(BaseProcess *__hidden this);
void (__thiscall *Unk_139)(BaseProcess *__hidden this);
void (__thiscall *Unk_13A)(BaseProcess *__hidden this);
float (__thiscall *GetUnk08C)(BaseProcess *__hidden this);
void (__thiscall *SetUnk08C)(BaseProcess *__hidden this, float arg);
void (__thiscall *Unk_13D)(BaseProcess *__hidden this);
void (__thiscall *Unk_13E)(BaseProcess *__hidden this);
void (__thiscall *Unk_13F)(BaseProcess *__hidden this);
void (__thiscall *Unk_140)(BaseProcess *__hidden this);
};
