struct IDirect3DSwapChain9Vtbl
{
HRESULT (__stdcall *QueryInterface)(IDirect3DSwapChain9 *This, const IID *const riid, void **ppvObj);
ULONG (__stdcall *AddRef)(IDirect3DSwapChain9 *This);
ULONG (__stdcall *Release)(IDirect3DSwapChain9 *This);
HRESULT (__stdcall *Present)(IDirect3DSwapChain9 *This, const RECT *pSourceRect, const RECT *pDestRect, HWND hDestWindowOverride, const RGNDATA *pDirtyRegion, DWORD dwFlags); ///<
                                                                                                                                                                               ///<
                                                                                                                                                                               ///< 2026-10-08 stage-additional-chain-flip-contract: scoped native HAL API and modern implementation evidence, not original Oblivion binary semantics. Windowed FLIP with1/2/3 backbuffers preserves every GetBackBuffer COM identity and rotates image contents left through an extra private front image on successful Present.48 native identity/content snapshots include6 initially undefined-front observations;42 defined images are compared.48 rectangle controls: only null source AND null destination accepted;45 nonnull combinations reject. Three zero-client-area native cases still succeed and rotate. Owned DX11 FLIP now allocates private front image and acquires full-image write scopes before composition. On successful/occluded-success result, ordered CopySubresourceRegion commands rotate contents using existing exported old back0 as temporary; no CPU readback/native factory/Present. Failed/busy composition executes no rotation; scopes commit unchanged initialized pixels (internal CPU readback cache may invalidate). Predication disabled/restored around copies; actual GPU errors fail modern frame without native replay. Release+FLIP WARP306 checks and existing additional-chain WARP pass; paired client queries reportzero internal work,1/2/3-role contents/identities match native, error/busy and retained-surface/private-front retirement validated. Test initially treated S_FALSE query data as ready; fixed bounded polling, only fixture rebuilt/rerun; production/COPY-DISCARD results reused. No deployment/game/physical GPU/On12/FPS claim. GPU copy rotation has bandwidth cost, not resource-pointer exchange. Fullscreen additional, NONMASKABLE mapping, broader provider/flag/format scope and overall backend/live GPU bucket remain unfinished. Evidence: analysis/dx11_completion/stage-additional-chain-flip-contract.
                                                                                                                                                                               ///<
                                                                                                                                                                               ///< 2026-10-08 stage-owned-presentation-config-boundary: source/runtime fixture evidence. Audit found renderer-owned device and implicit-chain Present still forwarded to native when Enable or PresentDX11SwapChain was disabled. Baseline three flag combinations reached native traps6 times. Owned Present now rejects D3DERR_NOTAVAILABLE before frame work; accepted device calls latch modern ownership so later presentation selection cannot choose native. Shared chain hook checks foreign ownership first, then rejects disabled owned output for implicit/additional alike. Logical frame/copy/attempt counters, completion, scene and recording state stay unchanged on rejection; re-enable resumes existing DX11 output. Release+four affected checks pass: owned boundary30 disabled calls acrossnormal/recording/scene cases, primary-chain regression, exclusive CPU41 and WARP84. Native owned Present0; pre-adoption/foreign routes retained. No deployment/game/FPS claim. Remaining native RT/framebuffer copies identified in comparison diagnostic, not modern Present input; review its owned-capture validity next. Evidence: analysis/dx11_completion/stage-owned-presentation-config-boundary.
HRESULT (__stdcall *GetFrontBufferData)(IDirect3DSwapChain9 *This, IDirect3DSurface9 *pDestSurface); ///<
                                                                                                     ///<
                                                                                                     ///< 2026-10-03 stage-front-buffer native host contract: 78 created-destination cases compared device GetFrontBufferData and swapchain GetFrontBufferData; results identical (8 successes). Unlocked A8R8G8B8 SYSTEMMEM/SCRATCH offscreen surfaces and texture-level surfaces accept display-size or larger destinations; tested DEFAULT/MANAGED and other formats reject. Captured alpha was uniformly255. Larger1604x904 destination for1600x900 display writes only the top-left1600x900 region; prefilled right/bottom guards remained intact. Null, held-lock, invalid implicit-chain index and failed-Reset calls reject INVALIDCALL. After creating an additional chain, device index1 still rejected while that chain's own GetFrontBufferData succeeded; do not assume additional chains are implicit indexed device chains. A DXGI duplication capture component is now written; builds/validation and public destination/chain integration remain pending. No full desktop pixel data is written to evidence logs, only metadata/aggregate checks. Scoped host-provider observations, not inferred Oblivion usage. Existing MCP/IDA sessions left intact.
                                                                                                     ///<
                                                                                                     ///< 2026-10-03 stage-front-buffer public migration validated: Device slot33 and swapchain slot4 now use adapter-matched DXGI Desktop Duplication plus a separate DX11 context/readback; neither calls native GetFrontBufferData for the owned device. Actual host capture succeeded1600x900/5760000 bytes. WARP renderer public test passed cropped exact pixel commits to native and owned SYSTEMMEM/SCRATCH destinations, guard preservation, real primary/additional-chain captures, untouched renderer IA topology, invalid/held/implicit-index rejection, worker capture, foreign-owned rejection and failed/successful Reset recovery. Trapped native device/chain front calls=0. The normalization/78-row native-admission component check also passed and was reused unchanged. Source uses checked CPU destination writes; native CPU mapping is retained only for existing native surfaces, while owned surfaces commit directly. Display/adapter/swapchain queries remain metadata dependencies. Adapter-group mapping remains explicitly NOTAVAILABLE, duplication-unavailable sessions return a diagnosed failure, and rotated displays have synthetic rotation validation only. No native/GDI capture fallback or game-frame substitution. Artifacts archived, not deployed; V233 and High INI unchanged. Evidence: analysis/dx11_completion/stage-front-buffer/result.md. Source/harness facts, not new Oblivion call-site assumptions.
HRESULT (__stdcall *GetBackBuffer)(IDirect3DSwapChain9 *This, UINT iBackBuffer, D3DBACKBUFFER_TYPE Type, IDirect3DSurface9 **ppBackBuffer);
HRESULT (__stdcall *GetRasterStatus)(IDirect3DSwapChain9 *This, D3DRASTER_STATUS *pRasterStatus); ///<
                                                                                                  ///< [DX11 raster migration 2026-10-08] Owned chain slot6 uses actual DXGI output/WDDM scanline, not native raster. Additional chain records track last successfully presented destination window; before first Present, only a matching output of the actual renderer adapter qualifies. Device/chain foreign dispatch retained. Real display bridge21 checks passed with owned native calls0, foreign2. Full multi-monitor/adapter-group/On12 parity unverified; source not deployed.
HRESULT (__stdcall *GetDisplayMode)(IDirect3DSwapChain9 *This, D3DDISPLAYMODE *pMode);
HRESULT (__stdcall *GetDevice)(IDirect3DSwapChain9 *This, IDirect3DDevice9 **ppDevice);
HRESULT (__stdcall *GetPresentParameters)(IDirect3DSwapChain9 *This, D3DPRESENT_PARAMETERS *pPresentationParameters);
};
