enum DISPLAYCONFIG_TOPOLOGY_ID : __int32
{
DISPLAYCONFIG_TOPOLOGY_INTERNAL = 0x1,
DISPLAYCONFIG_TOPOLOGY_CLONE = 0x2,
DISPLAYCONFIG_TOPOLOGY_EXTEND = 0x4,
DISPLAYCONFIG_TOPOLOGY_EXTERNAL = 0x8,
DISPLAYCONFIG_TOPOLOGY_FORCE_UINT32 = 0xFFFFFFFF,
};
