struct IDirectDrawSurface7Vtbl
{
HRESULT (__stdcall *QueryInterface)(IDirectDrawSurface7 *This, const IID *const riid, LPVOID *ppvObj) __offset(OFF64|AUTO);
ULONG (__stdcall *AddRef)(IDirectDrawSurface7 *This) __offset(OFF64|AUTO);
ULONG (__stdcall *Release)(IDirectDrawSurface7 *This) __offset(OFF64|AUTO);
HRESULT (__stdcall *AddAttachedSurface)(IDirectDrawSurface7 *This, LPDIRECTDRAWSURFACE7) __offset(OFF64|AUTO);
HRESULT (__stdcall *AddOverlayDirtyRect)(IDirectDrawSurface7 *This, LPRECT) __offset(OFF64|AUTO);
HRESULT (__stdcall *Blt)(IDirectDrawSurface7 *This, LPRECT, LPDIRECTDRAWSURFACE7, LPRECT, DWORD, LPDDBLTFX) __offset(OFF64|AUTO);
HRESULT (__stdcall *BltBatch)(IDirectDrawSurface7 *This, LPDDBLTBATCH, DWORD, DWORD) __offset(OFF64|AUTO);
HRESULT (__stdcall *BltFast)(IDirectDrawSurface7 *This, DWORD, DWORD, LPDIRECTDRAWSURFACE7, LPRECT, DWORD) __offset(OFF64|AUTO);
HRESULT (__stdcall *DeleteAttachedSurface)(IDirectDrawSurface7 *This, DWORD, LPDIRECTDRAWSURFACE7) __offset(OFF64|AUTO);
HRESULT (__stdcall *EnumAttachedSurfaces)(IDirectDrawSurface7 *This, LPVOID, LPDDENUMSURFACESCALLBACK7) __offset(OFF64|AUTO);
HRESULT (__stdcall *EnumOverlayZOrders)(IDirectDrawSurface7 *This, DWORD, LPVOID, LPDDENUMSURFACESCALLBACK7) __offset(OFF64|AUTO);
HRESULT (__stdcall *Flip)(IDirectDrawSurface7 *This, LPDIRECTDRAWSURFACE7, DWORD) __offset(OFF64|AUTO);
HRESULT (__stdcall *GetAttachedSurface)(IDirectDrawSurface7 *This, LPDDSCAPS2, LPDIRECTDRAWSURFACE7 *) __offset(OFF64|AUTO);
HRESULT (__stdcall *GetBltStatus)(IDirectDrawSurface7 *This, DWORD) __offset(OFF64|AUTO);
HRESULT (__stdcall *GetCaps)(IDirectDrawSurface7 *This, LPDDSCAPS2) __offset(OFF64|AUTO);
HRESULT (__stdcall *GetClipper)(IDirectDrawSurface7 *This, LPDIRECTDRAWCLIPPER *) __offset(OFF64|AUTO);
HRESULT (__stdcall *GetColorKey)(IDirectDrawSurface7 *This, DWORD, LPDDCOLORKEY) __offset(OFF64|AUTO);
HRESULT (__stdcall *GetDC)(IDirectDrawSurface7 *This, HDC *) __offset(OFF64|AUTO);
HRESULT (__stdcall *GetFlipStatus)(IDirectDrawSurface7 *This, DWORD) __offset(OFF64|AUTO);
HRESULT (__stdcall *GetOverlayPosition)(IDirectDrawSurface7 *This, LPLONG, LPLONG) __offset(OFF64|AUTO);
HRESULT (__stdcall *GetPalette)(IDirectDrawSurface7 *This, LPDIRECTDRAWPALETTE *) __offset(OFF64|AUTO);
HRESULT (__stdcall *GetPixelFormat)(IDirectDrawSurface7 *This, LPDDPIXELFORMAT) __offset(OFF64|AUTO);
HRESULT (__stdcall *GetSurfaceDesc)(IDirectDrawSurface7 *This, LPDDSURFACEDESC2) __offset(OFF64|AUTO);
HRESULT (__stdcall *Initialize)(IDirectDrawSurface7 *This, LPDIRECTDRAW, LPDDSURFACEDESC2) __offset(OFF64|AUTO);
HRESULT (__stdcall *IsLost)(IDirectDrawSurface7 *This) __offset(OFF64|AUTO);
HRESULT (__stdcall *Lock)(IDirectDrawSurface7 *This, LPRECT, LPDDSURFACEDESC2, DWORD, HANDLE) __offset(OFF64|AUTO);
HRESULT (__stdcall *ReleaseDC)(IDirectDrawSurface7 *This, HDC) __offset(OFF64|AUTO);
HRESULT (__stdcall *Restore)(IDirectDrawSurface7 *This) __offset(OFF64|AUTO);
HRESULT (__stdcall *SetClipper)(IDirectDrawSurface7 *This, LPDIRECTDRAWCLIPPER) __offset(OFF64|AUTO);
HRESULT (__stdcall *SetColorKey)(IDirectDrawSurface7 *This, DWORD, LPDDCOLORKEY) __offset(OFF64|AUTO);
HRESULT (__stdcall *SetOverlayPosition)(IDirectDrawSurface7 *This, LONG, LONG) __offset(OFF64|AUTO);
HRESULT (__stdcall *SetPalette)(IDirectDrawSurface7 *This, LPDIRECTDRAWPALETTE) __offset(OFF64|AUTO);
HRESULT (__stdcall *Unlock)(IDirectDrawSurface7 *This, LPRECT) __offset(OFF64|AUTO);
HRESULT (__stdcall *UpdateOverlay)(IDirectDrawSurface7 *This, LPRECT, LPDIRECTDRAWSURFACE7, LPRECT, DWORD, LPDDOVERLAYFX) __offset(OFF64|AUTO);
HRESULT (__stdcall *UpdateOverlayDisplay)(IDirectDrawSurface7 *This, DWORD) __offset(OFF64|AUTO);
HRESULT (__stdcall *UpdateOverlayZOrder)(IDirectDrawSurface7 *This, DWORD, LPDIRECTDRAWSURFACE7) __offset(OFF64|AUTO);
HRESULT (__stdcall *GetDDInterface)(IDirectDrawSurface7 *This, LPVOID *) __offset(OFF64|AUTO);
HRESULT (__stdcall *PageLock)(IDirectDrawSurface7 *This, DWORD) __offset(OFF64|AUTO);
HRESULT (__stdcall *PageUnlock)(IDirectDrawSurface7 *This, DWORD) __offset(OFF64|AUTO);
HRESULT (__stdcall *SetSurfaceDesc)(IDirectDrawSurface7 *This, LPDDSURFACEDESC2, DWORD) __offset(OFF64|AUTO);
HRESULT (__stdcall *SetPrivateData)(IDirectDrawSurface7 *This, const GUID *const, LPVOID, DWORD, DWORD) __offset(OFF64|AUTO);
HRESULT (__stdcall *GetPrivateData)(IDirectDrawSurface7 *This, const GUID *const, LPVOID, LPDWORD) __offset(OFF64|AUTO);
HRESULT (__stdcall *FreePrivateData)(IDirectDrawSurface7 *This, const GUID *const) __offset(OFF64|AUTO);
HRESULT (__stdcall *GetUniquenessValue)(IDirectDrawSurface7 *This, LPDWORD) __offset(OFF64|AUTO);
HRESULT (__stdcall *ChangeUniquenessValue)(IDirectDrawSurface7 *This) __offset(OFF64|AUTO);
HRESULT (__stdcall *SetPriority)(IDirectDrawSurface7 *This, DWORD) __offset(OFF64|AUTO);
HRESULT (__stdcall *GetPriority)(IDirectDrawSurface7 *This, LPDWORD) __offset(OFF64|AUTO);
HRESULT (__stdcall *SetLOD)(IDirectDrawSurface7 *This, DWORD) __offset(OFF64|AUTO);
HRESULT (__stdcall *GetLOD)(IDirectDrawSurface7 *This, LPDWORD) __offset(OFF64|AUTO);
};
