int __usercall MagicCaster_ApplyActiveMagicItem_::EffectLoop_CheckIngredient@<eax>(
        int a1@<edi>,
        int ebp0@<ebp>,
        int esi0@<esi>,
        TESObjectREFR *ebx0@<ebx>,
        int a5,
        int a6,
        int a7,
        int a8,
        int a9,
        int a10,
        int a11,
        int a12,
        int a13,
        int a14,
        int a15,
        float a16,
        int a17,
        int a18,
        int a19,
        int a20,
        int a21,
        int a22,
        int a23,
        int a24,
        int a25,
        int a26,
        int a27,
        int a28,
        int a29,
        int a30,
        int a31,
        int a32,
        int a33,
        float a34,
        int a35,
        int a36)
{
  int v36; // eax
  int v37; // eax

  v36 = (*(int (__thiscall **)(int))(*(_DWORD *)esi0 + 0x30))(esi0);
  v37 = (*(int (__thiscall **)(int))(*(_DWORD *)v36 + 0x18))(v36);
  if ( !v37 )
    return MagicCaster_ApplyActiveMagicItem_::EffectLoop_Spell();
  if ( v37 != 8 )
    return MagicCaster_ApplyActiveMagicItem_::EffectLoop_CheckRange(
             a5,
             a6,
             a7,
             a8,
             a9,
             a10,
             a11,
             a12,
             a13,
             a14,
             a15,
             LODWORD(a16),
             a17,
             a18);
  if ( a20 && (*(_BYTE *)(a20 + 0x7C) & 2) != 0 )
    return MagicCaster_ApplyActiveMagicItem_::EffectLoop_EdibleIngredient();
  return MagicCaster_ApplyActiveMagicItem_::EffectLoop_InedibleIngredient(
           a1,
           ebp0,
           esi0,
           ebx0,
           a5,
           a6,
           a7,
           a8,
           a9,
           a10,
           a11,
           a12,
           a13,
           a14,
           a15,
           a16,
           a17,
           a18,
           a19,
           a20,
           a21,
           a22,
           a23,
           a24,
           a25,
           a26,
           a27,
           a28,
           a29,
           a30,
           a31,
           a32,
           a33,
           a34,
           a35,
           a36);
}
