struct IWebBrowserAppVtbl
{
HRESULT_0 (*QueryInterface)(IWebBrowserApp_0 *, const IID *const, void **);
ULONG (*AddRef)(IWebBrowserApp_0 *);
ULONG (*Release)(IWebBrowserApp_0 *);
HRESULT_0 (*GetTypeInfoCount)(IWebBrowserApp_0 *, UINT *);
HRESULT_0 (*GetTypeInfo)(IWebBrowserApp_0 *, UINT, LCID, ITypeInfo_0 **);
HRESULT_0 (*GetIDsOfNames)(IWebBrowserApp_0 *, const IID *const, LPOLESTR *, UINT, LCID, DISPID *);
HRESULT_0 (*Invoke)(IWebBrowserApp_0 *, DISPID, const IID *const, LCID, WORD, DISPPARAMS *, VARIANT *, EXCEPINFO *, UINT *);
HRESULT_0 (*GoBack)(IWebBrowserApp_0 *);
HRESULT_0 (*GoForward)(IWebBrowserApp_0 *);
HRESULT_0 (*GoHome)(IWebBrowserApp_0 *);
HRESULT_0 (*GoSearch)(IWebBrowserApp_0 *);
HRESULT_0 (*Navigate)(IWebBrowserApp_0 *, BSTR, VARIANT *, VARIANT *, VARIANT *, VARIANT *);
HRESULT_0 (*Refresh)(IWebBrowserApp_0 *);
HRESULT_0 (*Refresh2)(IWebBrowserApp_0 *, VARIANT *);
HRESULT_0 (*Stop)(IWebBrowserApp_0 *);
HRESULT_0 (*get_Application)(IWebBrowserApp_0 *, IDispatch_0 **);
HRESULT_0 (*get_Parent)(IWebBrowserApp_0 *, IDispatch_0 **);
HRESULT_0 (*get_Container)(IWebBrowserApp_0 *, IDispatch_0 **);
HRESULT_0 (*get_Document)(IWebBrowserApp_0 *, IDispatch_0 **);
HRESULT_0 (*get_TopLevelContainer)(IWebBrowserApp_0 *, VARIANT_BOOL *);
HRESULT_0 (*get_Type)(IWebBrowserApp_0 *, BSTR *);
HRESULT_0 (*get_Left)(IWebBrowserApp_0 *, LONG *);
HRESULT_0 (*put_Left)(IWebBrowserApp_0 *, LONG);
HRESULT_0 (*get_Top)(IWebBrowserApp_0 *, LONG *);
HRESULT_0 (*put_Top)(IWebBrowserApp_0 *, LONG);
HRESULT_0 (*get_Width)(IWebBrowserApp_0 *, LONG *);
HRESULT_0 (*put_Width)(IWebBrowserApp_0 *, LONG);
HRESULT_0 (*get_Height)(IWebBrowserApp_0 *, LONG *);
HRESULT_0 (*put_Height)(IWebBrowserApp_0 *, LONG);
HRESULT_0 (*get_LocationName)(IWebBrowserApp_0 *, BSTR *);
HRESULT_0 (*get_LocationURL)(IWebBrowserApp_0 *, BSTR *);
HRESULT_0 (*get_Busy)(IWebBrowserApp_0 *, VARIANT_BOOL *);
HRESULT_0 (*Quit)(IWebBrowserApp_0 *);
HRESULT_0 (*ClientToWindow)(IWebBrowserApp_0 *, int *, int *);
HRESULT_0 (*PutProperty)(IWebBrowserApp_0 *, BSTR, VARIANT);
HRESULT_0 (*GetProperty)(IWebBrowserApp_0 *, BSTR, VARIANT *);
HRESULT_0 (*get_Name)(IWebBrowserApp_0 *, BSTR *);
HRESULT_0 (*get_HWND)(IWebBrowserApp_0 *, SHANDLE_PTR *);
HRESULT_0 (*get_FullName)(IWebBrowserApp_0 *, BSTR *);
HRESULT_0 (*get_Path)(IWebBrowserApp_0 *, BSTR *);
HRESULT_0 (*get_Visible)(IWebBrowserApp_0 *, VARIANT_BOOL *);
HRESULT_0 (*put_Visible)(IWebBrowserApp_0 *, VARIANT_BOOL);
HRESULT_0 (*get_StatusBar)(IWebBrowserApp_0 *, VARIANT_BOOL *);
HRESULT_0 (*put_StatusBar)(IWebBrowserApp_0 *, VARIANT_BOOL);
HRESULT_0 (*get_StatusText)(IWebBrowserApp_0 *, BSTR *);
HRESULT_0 (*put_StatusText)(IWebBrowserApp_0 *, BSTR);
HRESULT_0 (*get_ToolBar)(IWebBrowserApp_0 *, int *);
HRESULT_0 (*put_ToolBar)(IWebBrowserApp_0 *, int);
HRESULT_0 (*get_MenuBar)(IWebBrowserApp_0 *, VARIANT_BOOL *);
HRESULT_0 (*put_MenuBar)(IWebBrowserApp_0 *, VARIANT_BOOL);
HRESULT_0 (*get_FullScreen)(IWebBrowserApp_0 *, VARIANT_BOOL *);
HRESULT_0 (*put_FullScreen)(IWebBrowserApp_0 *, VARIANT_BOOL);
};
