struct _MIDL_STUB_MESSAGE
{
PRPC_MESSAGE RpcMsg;
unsigned __int8 *Buffer;
unsigned __int8 *BufferStart;
unsigned __int8 *BufferEnd;
unsigned __int8 *BufferMark;
ULONG BufferLength;
ULONG MemorySize;
unsigned __int8 *Memory;
unsigned __int8 IsClient;
unsigned __int8 Pad;
unsigned __int16 uFlags2;
int ReuseBuffer;
NDR_ALLOC_ALL_NODES_CONTEXT *pAllocAllNodesContext;
NDR_POINTER_QUEUE_STATE *pPointerQueueState;
int IgnoreEmbeddedPointers;
unsigned __int8 *PointerBufferMark;
unsigned __int8 CorrDespIncrement;
unsigned __int8 uFlags;
unsigned __int16 UniquePtrCount;
__declspec(align(8)) ULONG_PTR MaxCount;
ULONG Offset;
ULONG ActualCount;
void *(*pfnAllocate)(SIZE_T);
void (*pfnFree)(void *);
unsigned __int8 *StackTop;
unsigned __int8 *pPresentedType;
unsigned __int8 *pTransmitType;
handle_t SavedHandle;
const _MIDL_STUB_DESC *StubDesc;
_FULL_PTR_XLAT_TABLES *FullPtrXlatTables;
ULONG FullPtrRefId;
ULONG PointerLength;
unsigned __int32 fInDontFree : 1;
unsigned __int32 fDontCallFreeInst : 1;
unsigned __int32 fInOnlyParam : 1;
unsigned __int32 fHasReturn : 1;
unsigned __int32 fHasExtensions : 1;
unsigned __int32 fHasNewCorrDesc : 1;
unsigned __int32 fIsIn : 1;
unsigned __int32 fIsOut : 1;
unsigned __int32 fIsOicf : 1;
unsigned __int32 fBufferValid : 1;
unsigned __int32 fHasMemoryValidateCallback : 1;
unsigned __int32 fInFree : 1;
unsigned __int32 fNeedMCCP : 1;
__int32 fUnused : 3;
__int32 fUnused2 : 16;
DWORD dwDestContext;
void *pvDestContext;
NDR_SCONTEXT *SavedContextHandles;
LONG ParamNumber;
IRpcChannelBuffer *pRpcChannelBuffer;
PARRAY_INFO pArrayInfo;
ULONG *SizePtrCountArray;
ULONG *SizePtrOffsetArray;
ULONG *SizePtrLengthArray;
void *pArgQueue;
DWORD dwStubPhase;
void *LowStackMark;
PNDR_ASYNC_MESSAGE pAsyncMsg;
PNDR_CORRELATION_INFO pCorrInfo;
unsigned __int8 *pCorrMemory;
void *pMemoryList;
CS_STUB_INFO *pCSInfo;
unsigned __int8 *ConformanceMark;
unsigned __int8 *VarianceMark;
INT_PTR Unused;
_NDR_PROC_CONTEXT *pContext;
void *ContextHandleHash;
void *pUserMarshalList;
INT_PTR Reserved51_3;
INT_PTR Reserved51_4;
INT_PTR Reserved51_5;
};
