enum COMMANDLINKSTATES : __int32
{
COMMANDLINKStateFiller0 = 0x0,
CMDLS_NORMAL = 0x1,
CMDLS_HOT = 0x2,
CMDLS_PRESSED = 0x3,
CMDLS_DISABLED = 0x4,
CMDLS_DEFAULTED = 0x5,
CMDLS_DEFAULTED_ANIMATING = 0x6,
};
