enum APTTYPEQUALIFIER : __int32
{
APTTYPEQUALIFIER_NONE = 0x0,
APTTYPEQUALIFIER_IMPLICIT_MTA = 0x1,
APTTYPEQUALIFIER_NA_ON_MTA = 0x2,
APTTYPEQUALIFIER_NA_ON_STA = 0x3,
APTTYPEQUALIFIER_NA_ON_IMPLICIT_MTA = 0x4,
APTTYPEQUALIFIER_NA_ON_MAINSTA = 0x5,
};
