enum SE_OBJECT_TYPE : __int32
{
SE_UNKNOWN_OBJECT_TYPE = 0x0,
SE_FILE_OBJECT = 0x1,
SE_SERVICE = 0x2,
SE_PRINTER = 0x3,
SE_REGISTRY_KEY = 0x4,
SE_LMSHARE = 0x5,
SE_KERNEL_OBJECT = 0x6,
SE_WINDOW_OBJECT = 0x7,
SE_DS_OBJECT = 0x8,
SE_DS_OBJECT_ALL = 0x9,
SE_PROVIDER_DEFINED_OBJECT = 0xA,
SE_WMIGUID_OBJECT = 0xB,
SE_REGISTRY_WOW64_32KEY = 0xC,
};
