struct $80D93121D5C2C7490092EA3C4923E85D
{
void (*p_glAccum)(GLenum, GLfloat) __offset(OFF64|AUTO);
void (*p_glAlphaFunc)(GLenum, GLfloat) __offset(OFF64|AUTO);
GLboolean (*p_glAreTexturesResident)(GLsizei, const GLuint *, GLboolean *) __offset(OFF64|AUTO);
void (*p_glArrayElement)(GLint) __offset(OFF64|AUTO);
void (*p_glBegin)(GLenum) __offset(OFF64|AUTO);
void (*p_glBindTexture)(GLenum, GLuint) __offset(OFF64|AUTO);
void (*p_glBitmap)(GLsizei, GLsizei, GLfloat, GLfloat, GLfloat, GLfloat, const GLubyte *) __offset(OFF64|AUTO);
void (*p_glBlendFunc)(GLenum, GLenum) __offset(OFF64|AUTO);
void (*p_glCallList)(GLuint) __offset(OFF64|AUTO);
void (*p_glCallLists)(GLsizei, GLenum, const void *) __offset(OFF64|AUTO);
void (*p_glClear)(GLbitfield) __offset(OFF64|AUTO);
void (*p_glClearAccum)(GLfloat, GLfloat, GLfloat, GLfloat) __offset(OFF64|AUTO);
void (*p_glClearColor)(GLfloat, GLfloat, GLfloat, GLfloat) __offset(OFF64|AUTO);
void (*p_glClearDepth)(GLdouble) __offset(OFF64|AUTO);
void (*p_glClearIndex)(GLfloat) __offset(OFF64|AUTO);
void (*p_glClearStencil)(GLint) __offset(OFF64|AUTO);
void (*p_glClipPlane)(GLenum, const GLdouble *) __offset(OFF64|AUTO);
void (*p_glColor3b)(GLbyte, GLbyte, GLbyte) __offset(OFF64|AUTO);
void (*p_glColor3bv)(const GLbyte *) __offset(OFF64|AUTO);
void (*p_glColor3d)(GLdouble, GLdouble, GLdouble) __offset(OFF64|AUTO);
void (*p_glColor3dv)(const GLdouble *) __offset(OFF64|AUTO);
void (*p_glColor3f)(GLfloat, GLfloat, GLfloat) __offset(OFF64|AUTO);
void (*p_glColor3fv)(const GLfloat *) __offset(OFF64|AUTO);
void (*p_glColor3i)(GLint, GLint, GLint) __offset(OFF64|AUTO);
void (*p_glColor3iv)(const GLint *) __offset(OFF64|AUTO);
void (*p_glColor3s)(GLshort, GLshort, GLshort) __offset(OFF64|AUTO);
void (*p_glColor3sv)(const GLshort *) __offset(OFF64|AUTO);
void (*p_glColor3ub)(GLubyte, GLubyte, GLubyte) __offset(OFF64|AUTO);
void (*p_glColor3ubv)(const GLubyte *) __offset(OFF64|AUTO);
void (*p_glColor3ui)(GLuint, GLuint, GLuint) __offset(OFF64|AUTO);
void (*p_glColor3uiv)(const GLuint *) __offset(OFF64|AUTO);
void (*p_glColor3us)(GLushort, GLushort, GLushort) __offset(OFF64|AUTO);
void (*p_glColor3usv)(const GLushort *) __offset(OFF64|AUTO);
void (*p_glColor4b)(GLbyte, GLbyte, GLbyte, GLbyte) __offset(OFF64|AUTO);
void (*p_glColor4bv)(const GLbyte *) __offset(OFF64|AUTO);
void (*p_glColor4d)(GLdouble, GLdouble, GLdouble, GLdouble) __offset(OFF64|AUTO);
void (*p_glColor4dv)(const GLdouble *) __offset(OFF64|AUTO);
void (*p_glColor4f)(GLfloat, GLfloat, GLfloat, GLfloat) __offset(OFF64|AUTO);
void (*p_glColor4fv)(const GLfloat *) __offset(OFF64|AUTO);
void (*p_glColor4i)(GLint, GLint, GLint, GLint) __offset(OFF64|AUTO);
void (*p_glColor4iv)(const GLint *) __offset(OFF64|AUTO);
void (*p_glColor4s)(GLshort, GLshort, GLshort, GLshort) __offset(OFF64|AUTO);
void (*p_glColor4sv)(const GLshort *) __offset(OFF64|AUTO);
void (*p_glColor4ub)(GLubyte, GLubyte, GLubyte, GLubyte) __offset(OFF64|AUTO);
void (*p_glColor4ubv)(const GLubyte *) __offset(OFF64|AUTO);
void (*p_glColor4ui)(GLuint, GLuint, GLuint, GLuint) __offset(OFF64|AUTO);
void (*p_glColor4uiv)(const GLuint *) __offset(OFF64|AUTO);
void (*p_glColor4us)(GLushort, GLushort, GLushort, GLushort) __offset(OFF64|AUTO);
void (*p_glColor4usv)(const GLushort *) __offset(OFF64|AUTO);
void (*p_glColorMask)(GLboolean, GLboolean, GLboolean, GLboolean) __offset(OFF64|AUTO);
void (*p_glColorMaterial)(GLenum, GLenum) __offset(OFF64|AUTO);
void (*p_glColorPointer)(GLint, GLenum, GLsizei, const void *) __offset(OFF64|AUTO);
void (*p_glCopyPixels)(GLint, GLint, GLsizei, GLsizei, GLenum) __offset(OFF64|AUTO);
void (*p_glCopyTexImage1D)(GLenum, GLint, GLenum, GLint, GLint, GLsizei, GLint) __offset(OFF64|AUTO);
void (*p_glCopyTexImage2D)(GLenum, GLint, GLenum, GLint, GLint, GLsizei, GLsizei, GLint) __offset(OFF64|AUTO);
void (*p_glCopyTexSubImage1D)(GLenum, GLint, GLint, GLint, GLint, GLsizei) __offset(OFF64|AUTO);
void (*p_glCopyTexSubImage2D)(GLenum, GLint, GLint, GLint, GLint, GLint, GLsizei, GLsizei) __offset(OFF64|AUTO);
void (*p_glCullFace)(GLenum) __offset(OFF64|AUTO);
void (*p_glDeleteLists)(GLuint, GLsizei) __offset(OFF64|AUTO);
void (*p_glDeleteTextures)(GLsizei, const GLuint *) __offset(OFF64|AUTO);
void (*p_glDepthFunc)(GLenum) __offset(OFF64|AUTO);
void (*p_glDepthMask)(GLboolean) __offset(OFF64|AUTO);
void (*p_glDepthRange)(GLdouble, GLdouble) __offset(OFF64|AUTO);
void (*p_glDisable)(GLenum) __offset(OFF64|AUTO);
void (*p_glDisableClientState)(GLenum) __offset(OFF64|AUTO);
void (*p_glDrawArrays)(GLenum, GLint, GLsizei) __offset(OFF64|AUTO);
void (*p_glDrawBuffer)(GLenum) __offset(OFF64|AUTO);
void (*p_glDrawElements)(GLenum, GLsizei, GLenum, const void *) __offset(OFF64|AUTO);
void (*p_glDrawPixels)(GLsizei, GLsizei, GLenum, GLenum, const void *) __offset(OFF64|AUTO);
void (*p_glEdgeFlag)(GLboolean) __offset(OFF64|AUTO);
void (*p_glEdgeFlagPointer)(GLsizei, const void *) __offset(OFF64|AUTO);
void (*p_glEdgeFlagv)(const GLboolean *) __offset(OFF64|AUTO);
void (*p_glEnable)(GLenum) __offset(OFF64|AUTO);
void (*p_glEnableClientState)(GLenum) __offset(OFF64|AUTO);
void (*p_glEnd)(void) __offset(OFF64|AUTO);
void (*p_glEndList)(void) __offset(OFF64|AUTO);
void (*p_glEvalCoord1d)(GLdouble) __offset(OFF64|AUTO);
void (*p_glEvalCoord1dv)(const GLdouble *) __offset(OFF64|AUTO);
void (*p_glEvalCoord1f)(GLfloat) __offset(OFF64|AUTO);
void (*p_glEvalCoord1fv)(const GLfloat *) __offset(OFF64|AUTO);
void (*p_glEvalCoord2d)(GLdouble, GLdouble) __offset(OFF64|AUTO);
void (*p_glEvalCoord2dv)(const GLdouble *) __offset(OFF64|AUTO);
void (*p_glEvalCoord2f)(GLfloat, GLfloat) __offset(OFF64|AUTO);
void (*p_glEvalCoord2fv)(const GLfloat *) __offset(OFF64|AUTO);
void (*p_glEvalMesh1)(GLenum, GLint, GLint) __offset(OFF64|AUTO);
void (*p_glEvalMesh2)(GLenum, GLint, GLint, GLint, GLint) __offset(OFF64|AUTO);
void (*p_glEvalPoint1)(GLint) __offset(OFF64|AUTO);
void (*p_glEvalPoint2)(GLint, GLint) __offset(OFF64|AUTO);
void (*p_glFeedbackBuffer)(GLsizei, GLenum, GLfloat *) __offset(OFF64|AUTO);
void (*p_glFinish)(void) __offset(OFF64|AUTO);
void (*p_glFlush)(void) __offset(OFF64|AUTO);
void (*p_glFogf)(GLenum, GLfloat) __offset(OFF64|AUTO);
void (*p_glFogfv)(GLenum, const GLfloat *) __offset(OFF64|AUTO);
void (*p_glFogi)(GLenum, GLint) __offset(OFF64|AUTO);
void (*p_glFogiv)(GLenum, const GLint *) __offset(OFF64|AUTO);
void (*p_glFrontFace)(GLenum) __offset(OFF64|AUTO);
void (*p_glFrustum)(GLdouble, GLdouble, GLdouble, GLdouble, GLdouble, GLdouble) __offset(OFF64|AUTO);
GLuint (*p_glGenLists)(GLsizei) __offset(OFF64|AUTO);
void (*p_glGenTextures)(GLsizei, GLuint *) __offset(OFF64|AUTO);
void (*p_glGetBooleanv)(GLenum, GLboolean *) __offset(OFF64|AUTO);
void (*p_glGetClipPlane)(GLenum, GLdouble *) __offset(OFF64|AUTO);
void (*p_glGetDoublev)(GLenum, GLdouble *) __offset(OFF64|AUTO);
GLenum (*p_glGetError)(void) __offset(OFF64|AUTO);
void (*p_glGetFloatv)(GLenum, GLfloat *) __offset(OFF64|AUTO);
void (*p_glGetIntegerv)(GLenum, GLint *) __offset(OFF64|AUTO);
void (*p_glGetLightfv)(GLenum, GLenum, GLfloat *) __offset(OFF64|AUTO);
void (*p_glGetLightiv)(GLenum, GLenum, GLint *) __offset(OFF64|AUTO);
void (*p_glGetMapdv)(GLenum, GLenum, GLdouble *) __offset(OFF64|AUTO);
void (*p_glGetMapfv)(GLenum, GLenum, GLfloat *) __offset(OFF64|AUTO);
void (*p_glGetMapiv)(GLenum, GLenum, GLint *) __offset(OFF64|AUTO);
void (*p_glGetMaterialfv)(GLenum, GLenum, GLfloat *) __offset(OFF64|AUTO);
void (*p_glGetMaterialiv)(GLenum, GLenum, GLint *) __offset(OFF64|AUTO);
void (*p_glGetPixelMapfv)(GLenum, GLfloat *) __offset(OFF64|AUTO);
void (*p_glGetPixelMapuiv)(GLenum, GLuint *) __offset(OFF64|AUTO);
void (*p_glGetPixelMapusv)(GLenum, GLushort *) __offset(OFF64|AUTO);
void (*p_glGetPointerv)(GLenum, void **) __offset(OFF64|AUTO);
void (*p_glGetPolygonStipple)(GLubyte *) __offset(OFF64|AUTO);
const GLubyte *(*p_glGetString)(GLenum) __offset(OFF64|AUTO);
void (*p_glGetTexEnvfv)(GLenum, GLenum, GLfloat *) __offset(OFF64|AUTO);
void (*p_glGetTexEnviv)(GLenum, GLenum, GLint *) __offset(OFF64|AUTO);
void (*p_glGetTexGendv)(GLenum, GLenum, GLdouble *) __offset(OFF64|AUTO);
void (*p_glGetTexGenfv)(GLenum, GLenum, GLfloat *) __offset(OFF64|AUTO);
void (*p_glGetTexGeniv)(GLenum, GLenum, GLint *) __offset(OFF64|AUTO);
void (*p_glGetTexImage)(GLenum, GLint, GLenum, GLenum, void *) __offset(OFF64|AUTO);
void (*p_glGetTexLevelParameterfv)(GLenum, GLint, GLenum, GLfloat *) __offset(OFF64|AUTO);
void (*p_glGetTexLevelParameteriv)(GLenum, GLint, GLenum, GLint *) __offset(OFF64|AUTO);
void (*p_glGetTexParameterfv)(GLenum, GLenum, GLfloat *) __offset(OFF64|AUTO);
void (*p_glGetTexParameteriv)(GLenum, GLenum, GLint *) __offset(OFF64|AUTO);
void (*p_glHint)(GLenum, GLenum) __offset(OFF64|AUTO);
void (*p_glIndexMask)(GLuint) __offset(OFF64|AUTO);
void (*p_glIndexPointer)(GLenum, GLsizei, const void *) __offset(OFF64|AUTO);
void (*p_glIndexd)(GLdouble) __offset(OFF64|AUTO);
void (*p_glIndexdv)(const GLdouble *) __offset(OFF64|AUTO);
void (*p_glIndexf)(GLfloat) __offset(OFF64|AUTO);
void (*p_glIndexfv)(const GLfloat *) __offset(OFF64|AUTO);
void (*p_glIndexi)(GLint) __offset(OFF64|AUTO);
void (*p_glIndexiv)(const GLint *) __offset(OFF64|AUTO);
void (*p_glIndexs)(GLshort) __offset(OFF64|AUTO);
void (*p_glIndexsv)(const GLshort *) __offset(OFF64|AUTO);
void (*p_glIndexub)(GLubyte) __offset(OFF64|AUTO);
void (*p_glIndexubv)(const GLubyte *) __offset(OFF64|AUTO);
void (*p_glInitNames)(void) __offset(OFF64|AUTO);
void (*p_glInterleavedArrays)(GLenum, GLsizei, const void *) __offset(OFF64|AUTO);
GLboolean (*p_glIsEnabled)(GLenum) __offset(OFF64|AUTO);
GLboolean (*p_glIsList)(GLuint) __offset(OFF64|AUTO);
GLboolean (*p_glIsTexture)(GLuint) __offset(OFF64|AUTO);
void (*p_glLightModelf)(GLenum, GLfloat) __offset(OFF64|AUTO);
void (*p_glLightModelfv)(GLenum, const GLfloat *) __offset(OFF64|AUTO);
void (*p_glLightModeli)(GLenum, GLint) __offset(OFF64|AUTO);
void (*p_glLightModeliv)(GLenum, const GLint *) __offset(OFF64|AUTO);
void (*p_glLightf)(GLenum, GLenum, GLfloat) __offset(OFF64|AUTO);
void (*p_glLightfv)(GLenum, GLenum, const GLfloat *) __offset(OFF64|AUTO);
void (*p_glLighti)(GLenum, GLenum, GLint) __offset(OFF64|AUTO);
void (*p_glLightiv)(GLenum, GLenum, const GLint *) __offset(OFF64|AUTO);
void (*p_glLineStipple)(GLint, GLushort) __offset(OFF64|AUTO);
void (*p_glLineWidth)(GLfloat) __offset(OFF64|AUTO);
void (*p_glListBase)(GLuint) __offset(OFF64|AUTO);
void (*p_glLoadIdentity)(void) __offset(OFF64|AUTO);
void (*p_glLoadMatrixd)(const GLdouble *) __offset(OFF64|AUTO);
void (*p_glLoadMatrixf)(const GLfloat *) __offset(OFF64|AUTO);
void (*p_glLoadName)(GLuint) __offset(OFF64|AUTO);
void (*p_glLogicOp)(GLenum) __offset(OFF64|AUTO);
void (*p_glMap1d)(GLenum, GLdouble, GLdouble, GLint, GLint, const GLdouble *) __offset(OFF64|AUTO);
void (*p_glMap1f)(GLenum, GLfloat, GLfloat, GLint, GLint, const GLfloat *) __offset(OFF64|AUTO);
void (*p_glMap2d)(GLenum, GLdouble, GLdouble, GLint, GLint, GLdouble, GLdouble, GLint, GLint, const GLdouble *) __offset(OFF64|AUTO);
void (*p_glMap2f)(GLenum, GLfloat, GLfloat, GLint, GLint, GLfloat, GLfloat, GLint, GLint, const GLfloat *) __offset(OFF64|AUTO);
void (*p_glMapGrid1d)(GLint, GLdouble, GLdouble) __offset(OFF64|AUTO);
void (*p_glMapGrid1f)(GLint, GLfloat, GLfloat) __offset(OFF64|AUTO);
void (*p_glMapGrid2d)(GLint, GLdouble, GLdouble, GLint, GLdouble, GLdouble) __offset(OFF64|AUTO);
void (*p_glMapGrid2f)(GLint, GLfloat, GLfloat, GLint, GLfloat, GLfloat) __offset(OFF64|AUTO);
void (*p_glMaterialf)(GLenum, GLenum, GLfloat) __offset(OFF64|AUTO);
void (*p_glMaterialfv)(GLenum, GLenum, const GLfloat *) __offset(OFF64|AUTO);
void (*p_glMateriali)(GLenum, GLenum, GLint) __offset(OFF64|AUTO);
void (*p_glMaterialiv)(GLenum, GLenum, const GLint *) __offset(OFF64|AUTO);
void (*p_glMatrixMode)(GLenum) __offset(OFF64|AUTO);
void (*p_glMultMatrixd)(const GLdouble *) __offset(OFF64|AUTO);
void (*p_glMultMatrixf)(const GLfloat *) __offset(OFF64|AUTO);
void (*p_glNewList)(GLuint, GLenum) __offset(OFF64|AUTO);
void (*p_glNormal3b)(GLbyte, GLbyte, GLbyte) __offset(OFF64|AUTO);
void (*p_glNormal3bv)(const GLbyte *) __offset(OFF64|AUTO);
void (*p_glNormal3d)(GLdouble, GLdouble, GLdouble) __offset(OFF64|AUTO);
void (*p_glNormal3dv)(const GLdouble *) __offset(OFF64|AUTO);
void (*p_glNormal3f)(GLfloat, GLfloat, GLfloat) __offset(OFF64|AUTO);
void (*p_glNormal3fv)(const GLfloat *) __offset(OFF64|AUTO);
void (*p_glNormal3i)(GLint, GLint, GLint) __offset(OFF64|AUTO);
void (*p_glNormal3iv)(const GLint *) __offset(OFF64|AUTO);
void (*p_glNormal3s)(GLshort, GLshort, GLshort) __offset(OFF64|AUTO);
void (*p_glNormal3sv)(const GLshort *) __offset(OFF64|AUTO);
void (*p_glNormalPointer)(GLenum, GLsizei, const void *) __offset(OFF64|AUTO);
void (*p_glOrtho)(GLdouble, GLdouble, GLdouble, GLdouble, GLdouble, GLdouble) __offset(OFF64|AUTO);
void (*p_glPassThrough)(GLfloat) __offset(OFF64|AUTO);
void (*p_glPixelMapfv)(GLenum, GLsizei, const GLfloat *) __offset(OFF64|AUTO);
void (*p_glPixelMapuiv)(GLenum, GLsizei, const GLuint *) __offset(OFF64|AUTO);
void (*p_glPixelMapusv)(GLenum, GLsizei, const GLushort *) __offset(OFF64|AUTO);
void (*p_glPixelStoref)(GLenum, GLfloat) __offset(OFF64|AUTO);
void (*p_glPixelStorei)(GLenum, GLint) __offset(OFF64|AUTO);
void (*p_glPixelTransferf)(GLenum, GLfloat) __offset(OFF64|AUTO);
void (*p_glPixelTransferi)(GLenum, GLint) __offset(OFF64|AUTO);
void (*p_glPixelZoom)(GLfloat, GLfloat) __offset(OFF64|AUTO);
void (*p_glPointSize)(GLfloat) __offset(OFF64|AUTO);
void (*p_glPolygonMode)(GLenum, GLenum) __offset(OFF64|AUTO);
void (*p_glPolygonOffset)(GLfloat, GLfloat) __offset(OFF64|AUTO);
void (*p_glPolygonStipple)(const GLubyte *) __offset(OFF64|AUTO);
void (*p_glPopAttrib)(void) __offset(OFF64|AUTO);
void (*p_glPopClientAttrib)(void) __offset(OFF64|AUTO);
void (*p_glPopMatrix)(void) __offset(OFF64|AUTO);
void (*p_glPopName)(void) __offset(OFF64|AUTO);
void (*p_glPrioritizeTextures)(GLsizei, const GLuint *, const GLfloat *) __offset(OFF64|AUTO);
void (*p_glPushAttrib)(GLbitfield) __offset(OFF64|AUTO);
void (*p_glPushClientAttrib)(GLbitfield) __offset(OFF64|AUTO);
void (*p_glPushMatrix)(void) __offset(OFF64|AUTO);
void (*p_glPushName)(GLuint) __offset(OFF64|AUTO);
void (*p_glRasterPos2d)(GLdouble, GLdouble) __offset(OFF64|AUTO);
void (*p_glRasterPos2dv)(const GLdouble *) __offset(OFF64|AUTO);
void (*p_glRasterPos2f)(GLfloat, GLfloat) __offset(OFF64|AUTO);
void (*p_glRasterPos2fv)(const GLfloat *) __offset(OFF64|AUTO);
void (*p_glRasterPos2i)(GLint, GLint) __offset(OFF64|AUTO);
void (*p_glRasterPos2iv)(const GLint *) __offset(OFF64|AUTO);
void (*p_glRasterPos2s)(GLshort, GLshort) __offset(OFF64|AUTO);
void (*p_glRasterPos2sv)(const GLshort *) __offset(OFF64|AUTO);
void (*p_glRasterPos3d)(GLdouble, GLdouble, GLdouble) __offset(OFF64|AUTO);
void (*p_glRasterPos3dv)(const GLdouble *) __offset(OFF64|AUTO);
void (*p_glRasterPos3f)(GLfloat, GLfloat, GLfloat) __offset(OFF64|AUTO);
void (*p_glRasterPos3fv)(const GLfloat *) __offset(OFF64|AUTO);
void (*p_glRasterPos3i)(GLint, GLint, GLint) __offset(OFF64|AUTO);
void (*p_glRasterPos3iv)(const GLint *) __offset(OFF64|AUTO);
void (*p_glRasterPos3s)(GLshort, GLshort, GLshort) __offset(OFF64|AUTO);
void (*p_glRasterPos3sv)(const GLshort *) __offset(OFF64|AUTO);
void (*p_glRasterPos4d)(GLdouble, GLdouble, GLdouble, GLdouble) __offset(OFF64|AUTO);
void (*p_glRasterPos4dv)(const GLdouble *) __offset(OFF64|AUTO);
void (*p_glRasterPos4f)(GLfloat, GLfloat, GLfloat, GLfloat) __offset(OFF64|AUTO);
void (*p_glRasterPos4fv)(const GLfloat *) __offset(OFF64|AUTO);
void (*p_glRasterPos4i)(GLint, GLint, GLint, GLint) __offset(OFF64|AUTO);
void (*p_glRasterPos4iv)(const GLint *) __offset(OFF64|AUTO);
void (*p_glRasterPos4s)(GLshort, GLshort, GLshort, GLshort) __offset(OFF64|AUTO);
void (*p_glRasterPos4sv)(const GLshort *) __offset(OFF64|AUTO);
void (*p_glReadBuffer)(GLenum) __offset(OFF64|AUTO);
void (*p_glReadPixels)(GLint, GLint, GLsizei, GLsizei, GLenum, GLenum, void *) __offset(OFF64|AUTO);
void (*p_glRectd)(GLdouble, GLdouble, GLdouble, GLdouble) __offset(OFF64|AUTO);
void (*p_glRectdv)(const GLdouble *, const GLdouble *) __offset(OFF64|AUTO);
void (*p_glRectf)(GLfloat, GLfloat, GLfloat, GLfloat) __offset(OFF64|AUTO);
void (*p_glRectfv)(const GLfloat *, const GLfloat *) __offset(OFF64|AUTO);
void (*p_glRecti)(GLint, GLint, GLint, GLint) __offset(OFF64|AUTO);
void (*p_glRectiv)(const GLint *, const GLint *) __offset(OFF64|AUTO);
void (*p_glRects)(GLshort, GLshort, GLshort, GLshort) __offset(OFF64|AUTO);
void (*p_glRectsv)(const GLshort *, const GLshort *) __offset(OFF64|AUTO);
GLint (*p_glRenderMode)(GLenum) __offset(OFF64|AUTO);
void (*p_glRotated)(GLdouble, GLdouble, GLdouble, GLdouble) __offset(OFF64|AUTO);
void (*p_glRotatef)(GLfloat, GLfloat, GLfloat, GLfloat) __offset(OFF64|AUTO);
void (*p_glScaled)(GLdouble, GLdouble, GLdouble) __offset(OFF64|AUTO);
void (*p_glScalef)(GLfloat, GLfloat, GLfloat) __offset(OFF64|AUTO);
void (*p_glScissor)(GLint, GLint, GLsizei, GLsizei) __offset(OFF64|AUTO);
void (*p_glSelectBuffer)(GLsizei, GLuint *) __offset(OFF64|AUTO);
void (*p_glShadeModel)(GLenum) __offset(OFF64|AUTO);
void (*p_glStencilFunc)(GLenum, GLint, GLuint) __offset(OFF64|AUTO);
void (*p_glStencilMask)(GLuint) __offset(OFF64|AUTO);
void (*p_glStencilOp)(GLenum, GLenum, GLenum) __offset(OFF64|AUTO);
void (*p_glTexCoord1d)(GLdouble) __offset(OFF64|AUTO);
void (*p_glTexCoord1dv)(const GLdouble *) __offset(OFF64|AUTO);
void (*p_glTexCoord1f)(GLfloat) __offset(OFF64|AUTO);
void (*p_glTexCoord1fv)(const GLfloat *) __offset(OFF64|AUTO);
void (*p_glTexCoord1i)(GLint) __offset(OFF64|AUTO);
void (*p_glTexCoord1iv)(const GLint *) __offset(OFF64|AUTO);
void (*p_glTexCoord1s)(GLshort) __offset(OFF64|AUTO);
void (*p_glTexCoord1sv)(const GLshort *) __offset(OFF64|AUTO);
void (*p_glTexCoord2d)(GLdouble, GLdouble) __offset(OFF64|AUTO);
void (*p_glTexCoord2dv)(const GLdouble *) __offset(OFF64|AUTO);
void (*p_glTexCoord2f)(GLfloat, GLfloat) __offset(OFF64|AUTO);
void (*p_glTexCoord2fv)(const GLfloat *) __offset(OFF64|AUTO);
void (*p_glTexCoord2i)(GLint, GLint) __offset(OFF64|AUTO);
void (*p_glTexCoord2iv)(const GLint *) __offset(OFF64|AUTO);
void (*p_glTexCoord2s)(GLshort, GLshort) __offset(OFF64|AUTO);
void (*p_glTexCoord2sv)(const GLshort *) __offset(OFF64|AUTO);
void (*p_glTexCoord3d)(GLdouble, GLdouble, GLdouble) __offset(OFF64|AUTO);
void (*p_glTexCoord3dv)(const GLdouble *) __offset(OFF64|AUTO);
void (*p_glTexCoord3f)(GLfloat, GLfloat, GLfloat) __offset(OFF64|AUTO);
void (*p_glTexCoord3fv)(const GLfloat *) __offset(OFF64|AUTO);
void (*p_glTexCoord3i)(GLint, GLint, GLint) __offset(OFF64|AUTO);
void (*p_glTexCoord3iv)(const GLint *) __offset(OFF64|AUTO);
void (*p_glTexCoord3s)(GLshort, GLshort, GLshort) __offset(OFF64|AUTO);
void (*p_glTexCoord3sv)(const GLshort *) __offset(OFF64|AUTO);
void (*p_glTexCoord4d)(GLdouble, GLdouble, GLdouble, GLdouble) __offset(OFF64|AUTO);
void (*p_glTexCoord4dv)(const GLdouble *) __offset(OFF64|AUTO);
void (*p_glTexCoord4f)(GLfloat, GLfloat, GLfloat, GLfloat) __offset(OFF64|AUTO);
void (*p_glTexCoord4fv)(const GLfloat *) __offset(OFF64|AUTO);
void (*p_glTexCoord4i)(GLint, GLint, GLint, GLint) __offset(OFF64|AUTO);
void (*p_glTexCoord4iv)(const GLint *) __offset(OFF64|AUTO);
void (*p_glTexCoord4s)(GLshort, GLshort, GLshort, GLshort) __offset(OFF64|AUTO);
void (*p_glTexCoord4sv)(const GLshort *) __offset(OFF64|AUTO);
void (*p_glTexCoordPointer)(GLint, GLenum, GLsizei, const void *) __offset(OFF64|AUTO);
void (*p_glTexEnvf)(GLenum, GLenum, GLfloat) __offset(OFF64|AUTO);
void (*p_glTexEnvfv)(GLenum, GLenum, const GLfloat *) __offset(OFF64|AUTO);
void (*p_glTexEnvi)(GLenum, GLenum, GLint) __offset(OFF64|AUTO);
void (*p_glTexEnviv)(GLenum, GLenum, const GLint *) __offset(OFF64|AUTO);
void (*p_glTexGend)(GLenum, GLenum, GLdouble) __offset(OFF64|AUTO);
void (*p_glTexGendv)(GLenum, GLenum, const GLdouble *) __offset(OFF64|AUTO);
void (*p_glTexGenf)(GLenum, GLenum, GLfloat) __offset(OFF64|AUTO);
void (*p_glTexGenfv)(GLenum, GLenum, const GLfloat *) __offset(OFF64|AUTO);
void (*p_glTexGeni)(GLenum, GLenum, GLint) __offset(OFF64|AUTO);
void (*p_glTexGeniv)(GLenum, GLenum, const GLint *) __offset(OFF64|AUTO);
void (*p_glTexImage1D)(GLenum, GLint, GLint, GLsizei, GLint, GLenum, GLenum, const void *) __offset(OFF64|AUTO);
void (*p_glTexImage2D)(GLenum, GLint, GLint, GLsizei, GLsizei, GLint, GLenum, GLenum, const void *) __offset(OFF64|AUTO);
void (*p_glTexParameterf)(GLenum, GLenum, GLfloat) __offset(OFF64|AUTO);
void (*p_glTexParameterfv)(GLenum, GLenum, const GLfloat *) __offset(OFF64|AUTO);
void (*p_glTexParameteri)(GLenum, GLenum, GLint) __offset(OFF64|AUTO);
void (*p_glTexParameteriv)(GLenum, GLenum, const GLint *) __offset(OFF64|AUTO);
void (*p_glTexSubImage1D)(GLenum, GLint, GLint, GLsizei, GLenum, GLenum, const void *) __offset(OFF64|AUTO);
void (*p_glTexSubImage2D)(GLenum, GLint, GLint, GLint, GLsizei, GLsizei, GLenum, GLenum, const void *) __offset(OFF64|AUTO);
void (*p_glTranslated)(GLdouble, GLdouble, GLdouble) __offset(OFF64|AUTO);
void (*p_glTranslatef)(GLfloat, GLfloat, GLfloat) __offset(OFF64|AUTO);
void (*p_glVertex2d)(GLdouble, GLdouble) __offset(OFF64|AUTO);
void (*p_glVertex2dv)(const GLdouble *) __offset(OFF64|AUTO);
void (*p_glVertex2f)(GLfloat, GLfloat) __offset(OFF64|AUTO);
void (*p_glVertex2fv)(const GLfloat *) __offset(OFF64|AUTO);
void (*p_glVertex2i)(GLint, GLint) __offset(OFF64|AUTO);
void (*p_glVertex2iv)(const GLint *) __offset(OFF64|AUTO);
void (*p_glVertex2s)(GLshort, GLshort) __offset(OFF64|AUTO);
void (*p_glVertex2sv)(const GLshort *) __offset(OFF64|AUTO);
void (*p_glVertex3d)(GLdouble, GLdouble, GLdouble) __offset(OFF64|AUTO);
void (*p_glVertex3dv)(const GLdouble *) __offset(OFF64|AUTO);
void (*p_glVertex3f)(GLfloat, GLfloat, GLfloat) __offset(OFF64|AUTO);
void (*p_glVertex3fv)(const GLfloat *) __offset(OFF64|AUTO);
void (*p_glVertex3i)(GLint, GLint, GLint) __offset(OFF64|AUTO);
void (*p_glVertex3iv)(const GLint *) __offset(OFF64|AUTO);
void (*p_glVertex3s)(GLshort, GLshort, GLshort) __offset(OFF64|AUTO);
void (*p_glVertex3sv)(const GLshort *) __offset(OFF64|AUTO);
void (*p_glVertex4d)(GLdouble, GLdouble, GLdouble, GLdouble) __offset(OFF64|AUTO);
void (*p_glVertex4dv)(const GLdouble *) __offset(OFF64|AUTO);
void (*p_glVertex4f)(GLfloat, GLfloat, GLfloat, GLfloat) __offset(OFF64|AUTO);
void (*p_glVertex4fv)(const GLfloat *) __offset(OFF64|AUTO);
void (*p_glVertex4i)(GLint, GLint, GLint, GLint) __offset(OFF64|AUTO);
void (*p_glVertex4iv)(const GLint *) __offset(OFF64|AUTO);
void (*p_glVertex4s)(GLshort, GLshort, GLshort, GLshort) __offset(OFF64|AUTO);
void (*p_glVertex4sv)(const GLshort *) __offset(OFF64|AUTO);
void (*p_glVertexPointer)(GLint, GLenum, GLsizei, const void *) __offset(OFF64|AUTO);
void (*p_glViewport)(GLint, GLint, GLsizei, GLsizei) __offset(OFF64|AUTO);
};
