union $30060EE037AF8FC1E98724083C3A486D
{
char cVal;
UCHAR bVal;
__int16 iVal;
USHORT uiVal;
VARIANT_BOOL boolVal;
LONG lVal;
ULONG ulVal;
float fltVal;
SCODE scode;
LARGE_INTEGER_1 hVal;
ULARGE_INTEGER_0 uhVal;
double dblVal;
CY cyVal;
DATE date;
FILETIME filetime;
CLSID *puuid __offset(OFF64|AUTO);
BLOB blob;
CLIPDATA *pclipdata __offset(OFF64|AUTO);
IStream_0 *pStream __offset(OFF64|AUTO);
IStorage_0 *pStorage __offset(OFF64|AUTO);
BSTR bstrVal __offset(OFF64|AUTO);
BSTRBLOB bstrblobVal;
LPSTR pszVal __offset(OFF64|AUTO);
LPWSTR pwszVal __offset(OFF64|AUTO);
IUnknown_0 *punkVal __offset(OFF64|AUTO);
IDispatch_0 *pdispVal __offset(OFF64|AUTO);
CAC cac;
CAUB caub;
CAI cai;
CAUI caui;
CABOOL cabool;
CAL cal;
CAUL caul;
CAFLT caflt;
CASCODE cascode;
CAH cah;
CAUH cauh;
CADBL cadbl;
CACY cacy;
CADATE cadate;
CAFILETIME cafiletime;
CACLSID cauuid;
CACLIPDATA caclipdata;
CABSTR cabstr;
CABSTRBLOB cabstrblob;
CALPSTR calpstr;
CALPWSTR calpwstr;
CAPROPVARIANT capropvar;
LPSAFEARRAY parray __offset(OFF64|AUTO);
CHAR *pcVal __offset(OFF64|AUTO);
UCHAR *pbVal __offset(OFF64|AUTO);
SHORT *piVal __offset(OFF64|AUTO);
USHORT *puiVal __offset(OFF64|AUTO);
LONG *plVal __offset(OFF64|AUTO);
ULONG *pulVal __offset(OFF64|AUTO);
INT *pintVal __offset(OFF64|AUTO);
UINT *puintVal __offset(OFF64|AUTO);
FLOAT *pfltVal __offset(OFF64|AUTO);
DOUBLE *pdblVal __offset(OFF64|AUTO);
VARIANT_BOOL *pboolVal __offset(OFF64|AUTO);
DECIMAL *pdecVal __offset(OFF64|AUTO);
SCODE *pscode __offset(OFF64|AUTO);
CY *pcyVal __offset(OFF64|AUTO);
DATE *pdate __offset(OFF64|AUTO);
BSTR *pbstrVal __offset(OFF64|AUTO);
IUnknown_0 **ppunkVal __offset(OFF64|AUTO);
IDispatch_0 **ppdispVal __offset(OFF64|AUTO);
LPSAFEARRAY *pparray __offset(OFF64|AUTO);
PROPVARIANT *pvarVal __offset(OFF64|AUTO);
};
