struct __declspec(align(8)) _DSPROPERTY_DIRECTSOUNDDEVICE_DESCRIPTION_W_DATA
{
DIRECTSOUNDDEVICE_TYPE Type;
DIRECTSOUNDDEVICE_DATAFLOW DataFlow;
GUID DeviceId;
LPWSTR Description;
LPWSTR Module;
LPWSTR Interface;
ULONG WaveDeviceId;
};
