enum INTERNAL_IF_OPER_STATUS : __int32
{
MIB_IF_OPER_STATUS_NON_OPERATIONAL = 0x0,
MIB_IF_OPER_STATUS_UNREACHABLE = 0x1,
MIB_IF_OPER_STATUS_DISCONNECTED = 0x2,
MIB_IF_OPER_STATUS_CONNECTING = 0x3,
MIB_IF_OPER_STATUS_CONNECTED = 0x4,
MIB_IF_OPER_STATUS_OPERATIONAL = 0x5,
};
