enum OFFSETTYPE : __int32
{
OT_TOPLEFT = 0x0,
OT_TOPRIGHT = 0x1,
OT_TOPMIDDLE = 0x2,
OT_BOTTOMLEFT = 0x3,
OT_BOTTOMRIGHT = 0x4,
OT_BOTTOMMIDDLE = 0x5,
OT_MIDDLELEFT = 0x6,
OT_MIDDLERIGHT = 0x7,
OT_LEFTOFCAPTION = 0x8,
OT_RIGHTOFCAPTION = 0x9,
OT_LEFTOFLASTBUTTON = 0xA,
OT_RIGHTOFLASTBUTTON = 0xB,
OT_ABOVELASTBUTTON = 0xC,
OT_BELOWLASTBUTTON = 0xD,
};
