enum _D3DCUBEMAP_FACES
{
D3DCUBEMAP_FACE_POSITIVE_X = 0x0,
D3DCUBEMAP_FACE_NEGATIVE_X = 0x1,
D3DCUBEMAP_FACE_POSITIVE_Y = 0x2,
D3DCUBEMAP_FACE_NEGATIVE_Y = 0x3,
D3DCUBEMAP_FACE_POSITIVE_Z = 0x4,
D3DCUBEMAP_FACE_NEGATIVE_Z = 0x5,
D3DCUBEMAP_FACE_FORCE_DWORD = 0x7FFFFFFF,
};
