struct DISPLAYCONFIG_TARGET_DEVICE_NAME
{
DISPLAYCONFIG_DEVICE_INFO_HEADER_0 header;
DISPLAYCONFIG_TARGET_DEVICE_NAME_FLAGS_0 flags;
DISPLAYCONFIG_VIDEO_OUTPUT_TECHNOLOGY outputTechnology;
UINT16 edidManufactureId;
UINT16 edidProductCodeId;
UINT32 connectorInstance;
WCHAR_0 monitorFriendlyDeviceName[64];
WCHAR_0 monitorDevicePath[128];
};
