enum D3DSAMPLERSTATETYPE : __int32
{
D3DSAMP_ADDRESSU = 0x1,
D3DSAMP_ADDRESSV = 0x2,
D3DSAMP_ADDRESSW = 0x3,
D3DSAMP_BORDERCOLOR = 0x4,
D3DSAMP_MAGFILTER = 0x5,
D3DSAMP_MINFILTER = 0x6,
D3DSAMP_MIPFILTER = 0x7,
D3DSAMP_MIPMAPLODBIAS = 0x8,
D3DSAMP_MAXMIPLEVEL = 0x9,
D3DSAMP_MAXANISOTROPY = 0xA,
D3DSAMP_SRGBTEXTURE = 0xB,
D3DSAMP_ELEMENTINDEX = 0xC,
D3DSAMP_DMAPOFFSET = 0xD,
D3DSAMP_FORCE_DWORD = 0x7FFFFFFF,
};
