enum OblivionShadowCasterCategory
{
OBL_SHADOW_CATEGORY_UNRESOLVED = 0x0,
OBL_SHADOW_CATEGORY_ARCHITECTURE = 0x1,
OBL_SHADOW_CATEGORY_FURNITURE = 0x2,
OBL_SHADOW_CATEGORY_ACTORS = 0x3,
OBL_SHADOW_CATEGORY_ITEMS = 0x4,
OBL_SHADOW_CATEGORY_MISC = 0x5,
OBL_SHADOW_CATEGORY_OTHER = 0x6,
};
