enum WMIDPREQUESTCODE : __int32
{
WMI_GET_ALL_DATA = 0x0,
WMI_GET_SINGLE_INSTANCE = 0x1,
WMI_SET_SINGLE_INSTANCE = 0x2,
WMI_SET_SINGLE_ITEM = 0x3,
WMI_ENABLE_EVENTS = 0x4,
WMI_DISABLE_EVENTS = 0x5,
WMI_ENABLE_CONNECTION = 0x6,
WMI_DISABLE_CONNECTION = 0x7,
WMI_REGINFO = 0x8,
WMI_EXECUTE_METHOD = 0x9,
WMI_CAPTURE_STATE = 0xA,
};
