enum DISPLAYCONFIG_ROTATION : __int32
{
DISPLAYCONFIG_ROTATION_IDENTITY = 0x1,
DISPLAYCONFIG_ROTATION_ROTATE90 = 0x2,
DISPLAYCONFIG_ROTATION_ROTATE180 = 0x3,
DISPLAYCONFIG_ROTATION_ROTATE270 = 0x4,
DISPLAYCONFIG_ROTATION_FORCE_UINT32 = 0xFFFFFFFF,
};
