enum builtin_winprocs : __int32
{
WINPROC_BUTTON = 0x0,
WINPROC_COMBO = 0x1,
WINPROC_DEFWND = 0x2,
WINPROC_DIALOG = 0x3,
WINPROC_EDIT = 0x4,
WINPROC_LISTBOX = 0x5,
WINPROC_MDICLIENT = 0x6,
WINPROC_SCROLLBAR = 0x7,
WINPROC_STATIC = 0x8,
WINPROC_IME = 0x9,
WINPROC_DESKTOP = 0xA,
NB_BUILTIN_AW_WINPROCS = 0xA,
WINPROC_ICONTITLE = 0xB,
WINPROC_MENU = 0xC,
WINPROC_MESSAGE = 0xD,
NB_BUILTIN_WINPROCS = 0xE,
};
