enum _TRUSTEE_TYPE : __int32
{
TRUSTEE_IS_UNKNOWN = 0x0,
TRUSTEE_IS_USER = 0x1,
TRUSTEE_IS_GROUP = 0x2,
TRUSTEE_IS_DOMAIN = 0x3,
TRUSTEE_IS_ALIAS = 0x4,
TRUSTEE_IS_WELL_KNOWN_GROUP = 0x5,
TRUSTEE_IS_DELETED = 0x6,
TRUSTEE_IS_INVALID = 0x7,
TRUSTEE_IS_COMPUTER = 0x8,
};
