enum TESPackageType : __int8
{
kPackageType_Find = 0x0,
kPackageType_Follow = 0x1,
kPackageType_Escort = 0x2,
kPackageType_Eat = 0x3,
kPackageType_Sleep = 0x4,
kPackageType_Wander = 0x5,
kPackageType_Travel = 0x6,
kPackageType_Accompany = 0x7,
kPackageType_UseItemAt = 0x8,
kPackageType_Ambush = 0x9,
kPackageType_FleeNotCombat = 0xA,
kPackageType_CastMagic = 0xB,
kPackageType_Combat = 0xC,
kPackageType_CombatLow = 0xD,
kPackageType_Activate = 0xE,
kPackageType_Alarm = 0xF,
kPackageType_Flee = 0x10,
kPackageType_Trespass = 0x11,
kPackageType_Dialogue = 0x12,
kPackageType_Spectator = 0x13,
kPackageType_ReactToDead = 0x14,
kPackageType_GetUp = 0x15,
kPackageType_MountHorse = 0x16,
kPackageType_DismountHorse = 0x17,
kPackageType_DoNothing = 0x18,
kPackageType_CastTargetSpell = 0x19,
kPackageType_CastTouchSpell = 0x1A,
kPackageType_VampireFeed = 0x1B,
kPackageType_Surface = 0x1C,
kPackageType_SearchForAttacker = 0x1D,
kPackageType_ClearMountPosition = 0x1E,
kPackageType_SummonCreatureDefend = 0x1F,
kPackageType_MovementBlocked = 0x20,
kPackageType_Count = 0x21,
};
