enum wm_char_mapping : __int32
{
WMCHAR_MAP_POSTMESSAGE = 0x0,
WMCHAR_MAP_SENDMESSAGE = 0x1,
WMCHAR_MAP_SENDMESSAGETIMEOUT = 0x2,
WMCHAR_MAP_RECVMESSAGE = 0x3,
WMCHAR_MAP_DISPATCHMESSAGE = 0x4,
WMCHAR_MAP_CALLWINDOWPROC = 0x5,
WMCHAR_MAP_COUNT = 0x6,
WMCHAR_MAP_NOMAPPING = 0x6,
};
