struct IDirect3DTexture9Vtbl
{
HRESULT (__stdcall *QueryInterface)(IDirect3DTexture9 *This, const IID *const riid, void **ppvObj); ///<
                                                                                                    ///<
                                                                                                    ///< 2026-10-03 stage-texture-com-contract host evidence: texture2D/cube/volume root plus2aliases report shared count3 across all4tested pools, retaining parent identity through GetContainer after parent release. Private data is per endpoint, not shared. Managed ROOT priority stores values; surface aliases always read/set0. Root QI supports IUnknown/Resource9/BaseTexture9/specific interface; surface QI supports IUnknown/Surface9 but rejects Resource9 despite C++ inheritance. Volume QI supports IUnknown/Volume9. Alias GetContainer(Device9) rejects; standalone surface GetContainer(IUnknown/Device9) returns device. Private-data IUNKNOWN retains on set/get and releases on removal. Zero-byte SetPrivateData returns E_OUTOFMEMORY; missing key stays missing, existing key becomes size0. Failed Reset on managed2D returns levels/type/priority0; GetLevelDesc/GetDesc reject and preserve descriptor output; GetSurfaceLevel lost failure leaves output unchanged, whereas bad-level failure while operational writesnull. QI/GetDevice/GetContainer/private data remain available. Software/HW-VP metadata comparison is archived. Owned D3D9TextureInterfaces frontend implements these contracts, aggregate retirement/inventory and required backend data callbacks; tests pass but real Store/data callbacks and live factory activation remain unfinished. No native resource allocation by this frontend; no deployment.
ULONG (__stdcall *AddRef)(IDirect3DTexture9 *This); ///<
                                                    ///<
                                                    ///< 2026-10-03 stage-texture-com-contract host evidence: texture2D/cube/volume root plus2aliases report shared count3 across all4tested pools, retaining parent identity through GetContainer after parent release. Private data is per endpoint, not shared. Managed ROOT priority stores values; surface aliases always read/set0. Root QI supports IUnknown/Resource9/BaseTexture9/specific interface; surface QI supports IUnknown/Surface9 but rejects Resource9 despite C++ inheritance. Volume QI supports IUnknown/Volume9. Alias GetContainer(Device9) rejects; standalone surface GetContainer(IUnknown/Device9) returns device. Private-data IUNKNOWN retains on set/get and releases on removal. Zero-byte SetPrivateData returns E_OUTOFMEMORY; missing key stays missing, existing key becomes size0. Failed Reset on managed2D returns levels/type/priority0; GetLevelDesc/GetDesc reject and preserve descriptor output; GetSurfaceLevel lost failure leaves output unchanged, whereas bad-level failure while operational writesnull. QI/GetDevice/GetContainer/private data remain available. Software/HW-VP metadata comparison is archived. Owned D3D9TextureInterfaces frontend implements these contracts, aggregate retirement/inventory and required backend data callbacks; tests pass but real Store/data callbacks and live factory activation remain unfinished. No native resource allocation by this frontend; no deployment.
ULONG (__stdcall *Release)(IDirect3DTexture9 *This); ///<
                                                     ///<
                                                     ///< 2026-10-03 stage-texture-com-contract host evidence: texture2D/cube/volume root plus2aliases report shared count3 across all4tested pools, retaining parent identity through GetContainer after parent release. Private data is per endpoint, not shared. Managed ROOT priority stores values; surface aliases always read/set0. Root QI supports IUnknown/Resource9/BaseTexture9/specific interface; surface QI supports IUnknown/Surface9 but rejects Resource9 despite C++ inheritance. Volume QI supports IUnknown/Volume9. Alias GetContainer(Device9) rejects; standalone surface GetContainer(IUnknown/Device9) returns device. Private-data IUNKNOWN retains on set/get and releases on removal. Zero-byte SetPrivateData returns E_OUTOFMEMORY; missing key stays missing, existing key becomes size0. Failed Reset on managed2D returns levels/type/priority0; GetLevelDesc/GetDesc reject and preserve descriptor output; GetSurfaceLevel lost failure leaves output unchanged, whereas bad-level failure while operational writesnull. QI/GetDevice/GetContainer/private data remain available. Software/HW-VP metadata comparison is archived. Owned D3D9TextureInterfaces frontend implements these contracts, aggregate retirement/inventory and required backend data callbacks; tests pass but real Store/data callbacks and live factory activation remain unfinished. No native resource allocation by this frontend; no deployment.
HRESULT (__stdcall *GetDevice)(IDirect3DTexture9 *This, IDirect3DDevice9 **ppDevice);
HRESULT (__stdcall *SetPrivateData)(IDirect3DTexture9 *This, const GUID *const refguid, const void *pData, DWORD SizeOfData, DWORD Flags); ///<
                                                                                                                                           ///<
                                                                                                                                           ///< 2026-10-03 stage-texture-com-contract host evidence: texture2D/cube/volume root plus2aliases report shared count3 across all4tested pools, retaining parent identity through GetContainer after parent release. Private data is per endpoint, not shared. Managed ROOT priority stores values; surface aliases always read/set0. Root QI supports IUnknown/Resource9/BaseTexture9/specific interface; surface QI supports IUnknown/Surface9 but rejects Resource9 despite C++ inheritance. Volume QI supports IUnknown/Volume9. Alias GetContainer(Device9) rejects; standalone surface GetContainer(IUnknown/Device9) returns device. Private-data IUNKNOWN retains on set/get and releases on removal. Zero-byte SetPrivateData returns E_OUTOFMEMORY; missing key stays missing, existing key becomes size0. Failed Reset on managed2D returns levels/type/priority0; GetLevelDesc/GetDesc reject and preserve descriptor output; GetSurfaceLevel lost failure leaves output unchanged, whereas bad-level failure while operational writesnull. QI/GetDevice/GetContainer/private data remain available. Software/HW-VP metadata comparison is archived. Owned D3D9TextureInterfaces frontend implements these contracts, aggregate retirement/inventory and required backend data callbacks; tests pass but real Store/data callbacks and live factory activation remain unfinished. No native resource allocation by this frontend; no deployment.
HRESULT (__stdcall *GetPrivateData)(IDirect3DTexture9 *This, const GUID *const refguid, void *pData, DWORD *pSizeOfData);
HRESULT (__stdcall *FreePrivateData)(IDirect3DTexture9 *This, const GUID *const refguid);
DWORD (__stdcall *SetPriority)(IDirect3DTexture9 *This, DWORD PriorityNew); ///<
                                                                            ///<
                                                                            ///< 2026-10-03 stage-texture-com-contract host evidence: texture2D/cube/volume root plus2aliases report shared count3 across all4tested pools, retaining parent identity through GetContainer after parent release. Private data is per endpoint, not shared. Managed ROOT priority stores values; surface aliases always read/set0. Root QI supports IUnknown/Resource9/BaseTexture9/specific interface; surface QI supports IUnknown/Surface9 but rejects Resource9 despite C++ inheritance. Volume QI supports IUnknown/Volume9. Alias GetContainer(Device9) rejects; standalone surface GetContainer(IUnknown/Device9) returns device. Private-data IUNKNOWN retains on set/get and releases on removal. Zero-byte SetPrivateData returns E_OUTOFMEMORY; missing key stays missing, existing key becomes size0. Failed Reset on managed2D returns levels/type/priority0; GetLevelDesc/GetDesc reject and preserve descriptor output; GetSurfaceLevel lost failure leaves output unchanged, whereas bad-level failure while operational writesnull. QI/GetDevice/GetContainer/private data remain available. Software/HW-VP metadata comparison is archived. Owned D3D9TextureInterfaces frontend implements these contracts, aggregate retirement/inventory and required backend data callbacks; tests pass but real Store/data callbacks and live factory activation remain unfinished. No native resource allocation by this frontend; no deployment.
DWORD (__stdcall *GetPriority)(IDirect3DTexture9 *This); ///<
                                                         ///<
                                                         ///< 2026-10-03 stage-texture-com-contract host evidence: texture2D/cube/volume root plus2aliases report shared count3 across all4tested pools, retaining parent identity through GetContainer after parent release. Private data is per endpoint, not shared. Managed ROOT priority stores values; surface aliases always read/set0. Root QI supports IUnknown/Resource9/BaseTexture9/specific interface; surface QI supports IUnknown/Surface9 but rejects Resource9 despite C++ inheritance. Volume QI supports IUnknown/Volume9. Alias GetContainer(Device9) rejects; standalone surface GetContainer(IUnknown/Device9) returns device. Private-data IUNKNOWN retains on set/get and releases on removal. Zero-byte SetPrivateData returns E_OUTOFMEMORY; missing key stays missing, existing key becomes size0. Failed Reset on managed2D returns levels/type/priority0; GetLevelDesc/GetDesc reject and preserve descriptor output; GetSurfaceLevel lost failure leaves output unchanged, whereas bad-level failure while operational writesnull. QI/GetDevice/GetContainer/private data remain available. Software/HW-VP metadata comparison is archived. Owned D3D9TextureInterfaces frontend implements these contracts, aggregate retirement/inventory and required backend data callbacks; tests pass but real Store/data callbacks and live factory activation remain unfinished. No native resource allocation by this frontend; no deployment.
void (__stdcall *PreLoad)(IDirect3DTexture9 *This);
D3DRESOURCETYPE (__stdcall *GetType)(IDirect3DTexture9 *This);
DWORD (__stdcall *SetLOD)(IDirect3DTexture9 *This, DWORD LODNew); ///<
                                                                  ///<
                                                                  ///< 2026-10-02 scoped host D3D9 contract evidence, stage-owned-texture-lod/native.log (not a claim of an Oblivion call-site execution): 44 successful 2D/cube/volume creation cases, 396 SetLOD/GetLOD observations. MANAGED ordinary resources clamp requested DWORD to public visible GetLevelCount-1 and return the previous value. DEFAULT/SYSTEMMEM/SCRATCH ignore writes and return/read zero. MANAGED AUTOGEN 2D/cube expose one level and clamp to zero, not hidden generated mips. After failed Reset with live DEFAULT resource: GetLOD and SetLOD return zero; requested write is ignored; successful Reset restores prior managed LOD2. Native volume AUTOGEN creation rejected. This is host-provider measurement, not universal capability proof. Owned replacement source/validation status is recorded separately.
                                                                  ///<
                                                                  ///< 2026-10-02 source milestone: owned public SetLOD/GetLOD now maintain atomic CPU state and publish changed controls to DX11 SRVs; no-op exchanges preserve revision. Original per-object GetLOD is used only for bootstrap inspection to avoid hook recursion; public foreign resources retain original routing. Release renderer build and four targeted checks passed: 396 native LOD observations, worker calls and 2D/cube/volume SRV mip selection with zero native LOD calls, alias reinspection, failed-Reset recovery, 193 manager checks, 109 inspection checks and 45 mip-reference comparisons (max channel error1). Undeployed; V233 remains installed. Native texture COM allocation/filter/bootstrap metadata remain dependencies. Evidence stage-owned-texture-lod.
                                                                  ///<
                                                                  ///< 2026-10-02 source stage-owned-texture-dirty: owned AddDirtyRect/AddDirtyBox now validate/copy caller arguments and atomically update owned dirty metadata without native control calls. Release renderer and2 targeted checks passed:1872native result comparisons plus exact DX11 2D/cube/volume partial-transfer pixels, held-lock, invalid-pointer and Reset cases; manager199checks. Test exposed a real reset-publication bug also affecting new LOD/filter setters: CPU control commits must succeed while GPU replay is already pending, keeping publicationLost set until Runtime Lookup replays latest controls/data. Fix preserves the replay fence; it does not authorize stale GPU data. Recovery test proves filter/dirty CPU commits then actual DX11 replay; LOD value/replay-fence preservation also checked. Initial test-only whole-region normalization mismatch corrected separately. No deployment. Native texture COM allocation/bootstrap and GDI remain dependencies; no general backend-completion/suppression claim.
DWORD (__stdcall *GetLOD)(IDirect3DTexture9 *This); ///<
                                                    ///<
                                                    ///< 2026-10-02 scoped host D3D9 contract evidence, stage-owned-texture-lod/native.log (not a claim of an Oblivion call-site execution): 44 successful 2D/cube/volume creation cases, 396 SetLOD/GetLOD observations. MANAGED ordinary resources clamp requested DWORD to public visible GetLevelCount-1 and return the previous value. DEFAULT/SYSTEMMEM/SCRATCH ignore writes and return/read zero. MANAGED AUTOGEN 2D/cube expose one level and clamp to zero, not hidden generated mips. After failed Reset with live DEFAULT resource: GetLOD and SetLOD return zero; requested write is ignored; successful Reset restores prior managed LOD2. Native volume AUTOGEN creation rejected. This is host-provider measurement, not universal capability proof. Owned replacement source/validation status is recorded separately.
                                                    ///<
                                                    ///< 2026-10-02 source milestone: owned public SetLOD/GetLOD now maintain atomic CPU state and publish changed controls to DX11 SRVs; no-op exchanges preserve revision. Original per-object GetLOD is used only for bootstrap inspection to avoid hook recursion; public foreign resources retain original routing. Release renderer build and four targeted checks passed: 396 native LOD observations, worker calls and 2D/cube/volume SRV mip selection with zero native LOD calls, alias reinspection, failed-Reset recovery, 193 manager checks, 109 inspection checks and 45 mip-reference comparisons (max channel error1). Undeployed; V233 remains installed. Native texture COM allocation/filter/bootstrap metadata remain dependencies. Evidence stage-owned-texture-lod.
DWORD (__stdcall *GetLevelCount)(IDirect3DTexture9 *This); ///<
                                                           ///<
                                                           ///< 2026-10-03 stage-texture-com-contract host evidence: texture2D/cube/volume root plus2aliases report shared count3 across all4tested pools, retaining parent identity through GetContainer after parent release. Private data is per endpoint, not shared. Managed ROOT priority stores values; surface aliases always read/set0. Root QI supports IUnknown/Resource9/BaseTexture9/specific interface; surface QI supports IUnknown/Surface9 but rejects Resource9 despite C++ inheritance. Volume QI supports IUnknown/Volume9. Alias GetContainer(Device9) rejects; standalone surface GetContainer(IUnknown/Device9) returns device. Private-data IUNKNOWN retains on set/get and releases on removal. Zero-byte SetPrivateData returns E_OUTOFMEMORY; missing key stays missing, existing key becomes size0. Failed Reset on managed2D returns levels/type/priority0; GetLevelDesc/GetDesc reject and preserve descriptor output; GetSurfaceLevel lost failure leaves output unchanged, whereas bad-level failure while operational writesnull. QI/GetDevice/GetContainer/private data remain available. Software/HW-VP metadata comparison is archived. Owned D3D9TextureInterfaces frontend implements these contracts, aggregate retirement/inventory and required backend data callbacks; tests pass but real Store/data callbacks and live factory activation remain unfinished. No native resource allocation by this frontend; no deployment.
HRESULT (__stdcall *SetAutoGenFilterType)(IDirect3DTexture9 *This, D3DTEXTUREFILTERTYPE FilterType); ///<
                                                                                                     ///<
                                                                                                     ///< 2026-10-02 scoped native provider contract probe stage-owned-texture-filter/native.log: 144 attempted 2D/cube/volume creations across four pools, ordinary/AUTOGEN/AUTOGEN+RT/DYNAMIC usage and A8R8G8B8/DXT1/R5G6B5; 70 successes and980 filter observations. POINT/LINEAR setters succeed even on ordinary non-AUTOGEN textures. ANISOTROPIC succeeds on 2D but rejects on cube/volume (reported filter caps 03030700/03030300/03030300). NONE and enum values4..8/99/FFFFFFFF reject without changing the stored filter. Initial filter is LINEAR except SCRATCH cube returns NONE on this provider. Failed Reset makes getter return NONE and valid/invalid setters return D3DERR_INVALIDCALL; a successful Reset restores prior managed POINT state. Measurements are host-scoped, not inferred native Oblivion calls or a universal capability proof. Native filter setter/getter still remain in production; owned migration not implemented yet.
                                                                                                     ///<
                                                                                                     ///< 2026-10-02 contract clarification: Microsoft SetAutoGenFilterType documentation requires the corresponding D3DPTFILTERCAPS_MINFxxx bit; source admission uses cached per-kind device caps. Docs describe non-AUTOGEN controls as no-effect/NONE, but the scoped native host probe (70 creations/980 calls) instead stores POINT/LINEAR and 2D ANISOTROPIC on ordinary resources. Migration deliberately follows the measured provider behavior here, retains bootstrap initial filter (including SCRATCH cube NONE), and records this divergence rather than asserting universal behavior. References: https://learn.microsoft.com/en-us/windows/win32/api/d3d9/nf-d3d9-idirect3dbasetexture9-setautogenfiltertype and corresponding getautogenfiltertype. Exotic capable providers/mip algorithms remain unverified.
                                                                                                     ///<
                                                                                                     ///< 2026-10-02 completed source milestone stage-owned-texture-filter: public owned slots14/15 now use atomic owned Store filter state, cached per-kind D3DCAPS9 MINF admission and DX11 mip publication. Original getter is retained only for bootstrap inspection; foreign resources forward. Failed Reset getterNONE/setterINVALIDCALL and managed recovery preserve measured values. Release DLL and3 targeted tests passed:980 native API comparisons; zero native filter calls during owned worker controls; alias reinspection and reset;45 generated mip image comparisons max channel-byte error1; manager199checks/inspection109checks. No deployment. Native texture COM factories and dirty controls remain; unusual capable-provider filters/mip algorithms still unverified. V233 installed DLL unchanged; High INI explicitly set by user.
                                                                                                     ///<
                                                                                                     ///< 2026-10-02 source stage-owned-texture-dirty: owned AddDirtyRect/AddDirtyBox now validate/copy caller arguments and atomically update owned dirty metadata without native control calls. Release renderer and2 targeted checks passed:1872native result comparisons plus exact DX11 2D/cube/volume partial-transfer pixels, held-lock, invalid-pointer and Reset cases; manager199checks. Test exposed a real reset-publication bug also affecting new LOD/filter setters: CPU control commits must succeed while GPU replay is already pending, keeping publicationLost set until Runtime Lookup replays latest controls/data. Fix preserves the replay fence; it does not authorize stale GPU data. Recovery test proves filter/dirty CPU commits then actual DX11 replay; LOD value/replay-fence preservation also checked. Initial test-only whole-region normalization mismatch corrected separately. No deployment. Native texture COM allocation/bootstrap and GDI remain dependencies; no general backend-completion/suppression claim.
D3DTEXTUREFILTERTYPE (__stdcall *GetAutoGenFilterType)(IDirect3DTexture9 *This); ///<
                                                                                 ///<
                                                                                 ///< 2026-10-02 scoped native provider contract probe stage-owned-texture-filter/native.log: 144 attempted 2D/cube/volume creations across four pools, ordinary/AUTOGEN/AUTOGEN+RT/DYNAMIC usage and A8R8G8B8/DXT1/R5G6B5; 70 successes and980 filter observations. POINT/LINEAR setters succeed even on ordinary non-AUTOGEN textures. ANISOTROPIC succeeds on 2D but rejects on cube/volume (reported filter caps 03030700/03030300/03030300). NONE and enum values4..8/99/FFFFFFFF reject without changing the stored filter. Initial filter is LINEAR except SCRATCH cube returns NONE on this provider. Failed Reset makes getter return NONE and valid/invalid setters return D3DERR_INVALIDCALL; a successful Reset restores prior managed POINT state. Measurements are host-scoped, not inferred native Oblivion calls or a universal capability proof. Native filter setter/getter still remain in production; owned migration not implemented yet.
                                                                                 ///<
                                                                                 ///< 2026-10-02 contract clarification: Microsoft SetAutoGenFilterType documentation requires the corresponding D3DPTFILTERCAPS_MINFxxx bit; source admission uses cached per-kind device caps. Docs describe non-AUTOGEN controls as no-effect/NONE, but the scoped native host probe (70 creations/980 calls) instead stores POINT/LINEAR and 2D ANISOTROPIC on ordinary resources. Migration deliberately follows the measured provider behavior here, retains bootstrap initial filter (including SCRATCH cube NONE), and records this divergence rather than asserting universal behavior. References: https://learn.microsoft.com/en-us/windows/win32/api/d3d9/nf-d3d9-idirect3dbasetexture9-setautogenfiltertype and corresponding getautogenfiltertype. Exotic capable providers/mip algorithms remain unverified.
                                                                                 ///<
                                                                                 ///< 2026-10-02 completed source milestone stage-owned-texture-filter: public owned slots14/15 now use atomic owned Store filter state, cached per-kind D3DCAPS9 MINF admission and DX11 mip publication. Original getter is retained only for bootstrap inspection; foreign resources forward. Failed Reset getterNONE/setterINVALIDCALL and managed recovery preserve measured values. Release DLL and3 targeted tests passed:980 native API comparisons; zero native filter calls during owned worker controls; alias reinspection and reset;45 generated mip image comparisons max channel-byte error1; manager199checks/inspection109checks. No deployment. Native texture COM factories and dirty controls remain; unusual capable-provider filters/mip algorithms still unverified. V233 installed DLL unchanged; High INI explicitly set by user.
void (__stdcall *GenerateMipSubLevels)(IDirect3DTexture9 *This);
HRESULT (__stdcall *GetLevelDesc)(IDirect3DTexture9 *This, UINT Level, D3DSURFACE_DESC *pDesc); ///<
                                                                                                ///<
                                                                                                ///< 2026-10-03 stage-texture-com-contract host evidence: texture2D/cube/volume root plus2aliases report shared count3 across all4tested pools, retaining parent identity through GetContainer after parent release. Private data is per endpoint, not shared. Managed ROOT priority stores values; surface aliases always read/set0. Root QI supports IUnknown/Resource9/BaseTexture9/specific interface; surface QI supports IUnknown/Surface9 but rejects Resource9 despite C++ inheritance. Volume QI supports IUnknown/Volume9. Alias GetContainer(Device9) rejects; standalone surface GetContainer(IUnknown/Device9) returns device. Private-data IUNKNOWN retains on set/get and releases on removal. Zero-byte SetPrivateData returns E_OUTOFMEMORY; missing key stays missing, existing key becomes size0. Failed Reset on managed2D returns levels/type/priority0; GetLevelDesc/GetDesc reject and preserve descriptor output; GetSurfaceLevel lost failure leaves output unchanged, whereas bad-level failure while operational writesnull. QI/GetDevice/GetContainer/private data remain available. Software/HW-VP metadata comparison is archived. Owned D3D9TextureInterfaces frontend implements these contracts, aggregate retirement/inventory and required backend data callbacks; tests pass but real Store/data callbacks and live factory activation remain unfinished. No native resource allocation by this frontend; no deployment.
HRESULT (__stdcall *GetSurfaceLevel)(IDirect3DTexture9 *This, UINT Level, IDirect3DSurface9 **ppSurfaceLevel); ///<
                                                                                                               ///<
                                                                                                               ///< 2026-10-03 stage-texture-com-contract host evidence: texture2D/cube/volume root plus2aliases report shared count3 across all4tested pools, retaining parent identity through GetContainer after parent release. Private data is per endpoint, not shared. Managed ROOT priority stores values; surface aliases always read/set0. Root QI supports IUnknown/Resource9/BaseTexture9/specific interface; surface QI supports IUnknown/Surface9 but rejects Resource9 despite C++ inheritance. Volume QI supports IUnknown/Volume9. Alias GetContainer(Device9) rejects; standalone surface GetContainer(IUnknown/Device9) returns device. Private-data IUNKNOWN retains on set/get and releases on removal. Zero-byte SetPrivateData returns E_OUTOFMEMORY; missing key stays missing, existing key becomes size0. Failed Reset on managed2D returns levels/type/priority0; GetLevelDesc/GetDesc reject and preserve descriptor output; GetSurfaceLevel lost failure leaves output unchanged, whereas bad-level failure while operational writesnull. QI/GetDevice/GetContainer/private data remain available. Software/HW-VP metadata comparison is archived. Owned D3D9TextureInterfaces frontend implements these contracts, aggregate retirement/inventory and required backend data callbacks; tests pass but real Store/data callbacks and live factory activation remain unfinished. No native resource allocation by this frontend; no deployment.
HRESULT (__stdcall *LockRect)(IDirect3DTexture9 *This, UINT Level, D3DLOCKED_RECT *pLockedRect, const RECT *pRect, DWORD Flags); ///<
                                                                                                                                 ///<
                                                                                                                                 ///< 2026-10-03 stage-owned-texture-mapping:1980native texture/cube/volume map cases and459surface cases. CPU2D/cube paths accept ignored hints incl tested unknown bit1, READONLY|DISCARD and bounded empty/unaligned-BC rectangles; volume and DEFAULT paths validate flags/ranges. DEFAULT ordinary textures reject locks; DYNAMIC accepts qualified maps. DEFAULT cube DISCARD rejects; dynamic2D/volume null top-level DISCARD succeeds; lower2D/cube DEFAULT DISCARD rejects. Duplicate same-subresource locks reject without breaking first Unlock; separate mips can lock together. Failed operational locks zero mapping outputs. DEFAULT standalone DONOTWAIT is valid but observed WASSTILLDRAWING while pending. RT row pitch has provider padding (64 vs owned minimum32 in8x8ARGB case), not portable fixed ABI. OwnedTextureMapping now uses Store sessions/owned row buffers, exact upload regions, CPU flag normalization, owner-supplied busy status, worker/race exclusion and reset replay; WARP pixels and legacy native-lock CPU regression pass. BeginOwnedLock rejects overlap before poisoning a lease; legacy native BeginLock remains unchanged. Empty CPU map has no write authority; out-of-bounds/reversed inputs reject. Component is not wired to live COM/factory callbacks yet. No renderer DLL build/deployment.
                                                                                                                                 ///<
                                                                                                                                 ///< 2026-10-03 stage-depth-texture-contract native host evidence: dynamic DEFAULT bare D16/D24S8/D24X8 sampled via ps_3_0 tex2Dproj (w=1), level0, point or linear filtering, clamp addressing. 81 uniform texel threshold searches plus210 filter rows establish: D24S8 depth=float((word>>8)/16777215), D24X8=float((word>>8)/16777216), low8 ignored by comparison. D16 uses low16 and clamps/rounds the comparison reference to UNORM16, round-half-up with exact intermediate precision; raw32767 fails at reference0.5. Negative refs pass; D16 max passes positive infinity; floating D24 comparison does not clamp >1; NaN comparisons return0. Linear filtering blends per-texel boolean comparisons. Standard DX11 R16 comparison alone differed at a half-step and treated NaN as0-ref; the new HLSL helper uses exact 40-bit integer product emulation to quantize D16 references and explicit isnan rejection. Conversion uses R16_UNORM for D16 and R32_FLOAT for the two measured D24 encodings. All858 native/modern comparison results now match in WARP; bounds/unreadable-input/unchanged-output tests also pass. Component is NOT connected to production Store/shader/sampler routing; public bare-depth creation stays rejected until all those paths are integrated. LOD, other opcodes, address modes, w-edge cases and other depth formats remain unqualified. This describes host-provider API behavior, not Oblivion disassembly or DSV memory layout; do not transplant into arbitrary depth/stencil semantics. Evidence: analysis/dx11_completion/stage-depth-texture-contract/result.md.
                                                                                                                                 ///<
                                                                                                                                 ///< 2026-10-03 stage-sampled-depth-storage: Source now has an explicit owned Description.sampledDepth interpretation (plugin metadata, not a native ABI member). For qualified DEFAULT 2D/surface D16/D24S8/D24X8 payloads without depth-stencil/render-target usage, Store retains exact raw CPU bytes and mapping/alias/replay semantics; GPU publication converts to R16_UNORM or R32_FLOAT comparison views. GPU views expose the native sampled-depth format. Description equality seals the interpretation. Raw readback uses retained CPU data because D24 GPU conversion loses the ignored low byte. GPU writes/copies, RTV/DSV use and unqualified sRGB views remain rejected. The flag is false for ordinary native inspection/public creation: shader/sampler routing and wider sampling/transfer contracts must be completed before activation. Release renderer and four targeted checks passed: sampled-depth storage actual GPU pixels and raw readback/worker/partial/reset/retirement, existing depth resources, color publication and1932-case public factory matrix. Existing15 factory exclusions remain unchanged. Artifacts archived, NOT deployed; V233/High INI unchanged. Evidence: analysis/dx11_completion/stage-sampled-depth-storage/result.md. Implementation validation, not a new Oblivion binary layout claim.
HRESULT (__stdcall *UnlockRect)(IDirect3DTexture9 *This, UINT Level); ///<
                                                                      ///<
                                                                      ///< 2026-10-03 stage-owned-texture-mapping:1980native texture/cube/volume map cases and459surface cases. CPU2D/cube paths accept ignored hints incl tested unknown bit1, READONLY|DISCARD and bounded empty/unaligned-BC rectangles; volume and DEFAULT paths validate flags/ranges. DEFAULT ordinary textures reject locks; DYNAMIC accepts qualified maps. DEFAULT cube DISCARD rejects; dynamic2D/volume null top-level DISCARD succeeds; lower2D/cube DEFAULT DISCARD rejects. Duplicate same-subresource locks reject without breaking first Unlock; separate mips can lock together. Failed operational locks zero mapping outputs. DEFAULT standalone DONOTWAIT is valid but observed WASSTILLDRAWING while pending. RT row pitch has provider padding (64 vs owned minimum32 in8x8ARGB case), not portable fixed ABI. OwnedTextureMapping now uses Store sessions/owned row buffers, exact upload regions, CPU flag normalization, owner-supplied busy status, worker/race exclusion and reset replay; WARP pixels and legacy native-lock CPU regression pass. BeginOwnedLock rejects overlap before poisoning a lease; legacy native BeginLock remains unchanged. Empty CPU map has no write authority; out-of-bounds/reversed inputs reject. Component is not wired to live COM/factory callbacks yet. No renderer DLL build/deployment.
                                                                      ///<
                                                                      ///< 2026-10-03 stage-depth-texture-contract native host evidence: dynamic DEFAULT bare D16/D24S8/D24X8 sampled via ps_3_0 tex2Dproj (w=1), level0, point or linear filtering, clamp addressing. 81 uniform texel threshold searches plus210 filter rows establish: D24S8 depth=float((word>>8)/16777215), D24X8=float((word>>8)/16777216), low8 ignored by comparison. D16 uses low16 and clamps/rounds the comparison reference to UNORM16, round-half-up with exact intermediate precision; raw32767 fails at reference0.5. Negative refs pass; D16 max passes positive infinity; floating D24 comparison does not clamp >1; NaN comparisons return0. Linear filtering blends per-texel boolean comparisons. Standard DX11 R16 comparison alone differed at a half-step and treated NaN as0-ref; the new HLSL helper uses exact 40-bit integer product emulation to quantize D16 references and explicit isnan rejection. Conversion uses R16_UNORM for D16 and R32_FLOAT for the two measured D24 encodings. All858 native/modern comparison results now match in WARP; bounds/unreadable-input/unchanged-output tests also pass. Component is NOT connected to production Store/shader/sampler routing; public bare-depth creation stays rejected until all those paths are integrated. LOD, other opcodes, address modes, w-edge cases and other depth formats remain unqualified. This describes host-provider API behavior, not Oblivion disassembly or DSV memory layout; do not transplant into arbitrary depth/stencil semantics. Evidence: analysis/dx11_completion/stage-depth-texture-contract/result.md.
                                                                      ///<
                                                                      ///< 2026-10-03 stage-sampled-depth-storage: Source now has an explicit owned Description.sampledDepth interpretation (plugin metadata, not a native ABI member). For qualified DEFAULT 2D/surface D16/D24S8/D24X8 payloads without depth-stencil/render-target usage, Store retains exact raw CPU bytes and mapping/alias/replay semantics; GPU publication converts to R16_UNORM or R32_FLOAT comparison views. GPU views expose the native sampled-depth format. Description equality seals the interpretation. Raw readback uses retained CPU data because D24 GPU conversion loses the ignored low byte. GPU writes/copies, RTV/DSV use and unqualified sRGB views remain rejected. The flag is false for ordinary native inspection/public creation: shader/sampler routing and wider sampling/transfer contracts must be completed before activation. Release renderer and four targeted checks passed: sampled-depth storage actual GPU pixels and raw readback/worker/partial/reset/retirement, existing depth resources, color publication and1932-case public factory matrix. Existing15 factory exclusions remain unchanged. Artifacts archived, NOT deployed; V233/High INI unchanged. Evidence: analysis/dx11_completion/stage-sampled-depth-storage/result.md. Implementation validation, not a new Oblivion binary layout claim.
HRESULT (__stdcall *AddDirtyRect)(IDirect3DTexture9 *This, const RECT *pDirtyRect); ///<
                                                                                    ///<
                                                                                    ///< 2026-10-02 host D3D9 dirty-control contract, stage-owned-texture-dirty/native.log:72 creation attempts/44successes/1872 AddDirtyRect/AddDirtyBox calls across2D/cube/volume,4pools,ordinary/AUTOGEN/DYNAMIC,A8R8G8B8/DXT1. Null and full regions accepted on all successful resources. Empty/reversed/negative/out-of-bounds regions and cube faces6/FFFFFFFF rejected INVALIDCALL. DXT1 rejects non-block-aligned rectangles; valid A8R8G8B8 rectangles accepted. AddDirtyRect succeeds during a held NO_DIRTY_UPDATE lock. Failed Reset makes whole/valid/invalid dirty requests return INVALIDCALL; success after recovery. Additional small/nonmultiple-of4 top DXT1 creation attempts1/2/3/6 all rejected by provider, so no dirty-edge behavior inferred for them. Host observations, not Oblivion call-site evidence or universal-provider claims.
                                                                                    ///<
                                                                                    ///< 2026-10-02 source stage-owned-texture-dirty: owned AddDirtyRect/AddDirtyBox now validate/copy caller arguments and atomically update owned dirty metadata without native control calls. Release renderer and2 targeted checks passed:1872native result comparisons plus exact DX11 2D/cube/volume partial-transfer pixels, held-lock, invalid-pointer and Reset cases; manager199checks. Test exposed a real reset-publication bug also affecting new LOD/filter setters: CPU control commits must succeed while GPU replay is already pending, keeping publicationLost set until Runtime Lookup replays latest controls/data. Fix preserves the replay fence; it does not authorize stale GPU data. Recovery test proves filter/dirty CPU commits then actual DX11 replay; LOD value/replay-fence preservation also checked. Initial test-only whole-region normalization mismatch corrected separately. No deployment. Native texture COM allocation/bootstrap and GDI remain dependencies; no general backend-completion/suppression claim.
};
