enum stubless_phase : __int32
{
STUBLESS_UNMARSHAL = 0x0,
STUBLESS_INITOUT = 0x1,
STUBLESS_CALLSERVER = 0x2,
STUBLESS_CALCSIZE = 0x3,
STUBLESS_GETBUFFER = 0x4,
STUBLESS_MARSHAL = 0x5,
STUBLESS_MUSTFREE = 0x6,
STUBLESS_FREE = 0x7,
};
