enum DISPLAYCONFIG_SCANLINE_ORDERING : __int32
{
DISPLAYCONFIG_SCANLINE_ORDERING_UNSPECIFIED = 0x0,
DISPLAYCONFIG_SCANLINE_ORDERING_PROGRESSIVE = 0x1,
DISPLAYCONFIG_SCANLINE_ORDERING_INTERLACED = 0x2,
DISPLAYCONFIG_SCANLINE_ORDERING_INTERLACED_UPPERFIELDFIRST = 0x2,
DISPLAYCONFIG_SCANLINE_ORDERING_INTERLACED_LOWERFIELDFIRST = 0x3,
DISPLAYCONFIG_SCANLINE_ORDERING_FORCE_UINT32 = 0xFFFFFFFF,
};
