enum GLOBALOPT_PROPERTIES : __int32
{
COMGLB_EXCEPTION_HANDLING = 0x1,
COMGLB_APPID = 0x2,
COMGLB_RPC_THREADPOOL_SETTING = 0x3,
COMGLB_RO_SETTINGS = 0x4,
COMGLB_UNMARSHALING_POLICY = 0x5,
COMGLB_PROPERTIES_RESERVED1 = 0x6,
COMGLB_PROPERTIES_RESERVED2 = 0x7,
COMGLB_PROPERTIES_RESERVED3 = 0x8,
};
