enum tagMKSYS : __int32
{
MKSYS_NONE = 0x0,
MKSYS_GENERICCOMPOSITE = 0x1,
MKSYS_FILEMONIKER = 0x2,
MKSYS_ANTIMONIKER = 0x3,
MKSYS_ITEMMONIKER = 0x4,
MKSYS_POINTERMONIKER = 0x5,
MKSYS_CLASSMONIKER = 0x7,
};
