enum STARTPANELPARTS : __int32
{
STARTPANELPartFiller0 = 0x0,
SPP_USERPANE = 0x1,
SPP_MOREPROGRAMS = 0x2,
SPP_MOREPROGRAMSARROW = 0x3,
SPP_PROGLIST = 0x4,
SPP_PROGLISTSEPARATOR = 0x5,
SPP_PLACESLIST = 0x6,
SPP_PLACESLISTSEPARATOR = 0x7,
SPP_LOGOFF = 0x8,
SPP_LOGOFFBUTTONS = 0x9,
SPP_USERPICTURE = 0xA,
SPP_PREVIEW = 0xB,
};
