enum DISPLAYCONFIG_PIXELFORMAT : __int32
{
DISPLAYCONFIG_PIXELFORMAT_8BPP = 0x1,
DISPLAYCONFIG_PIXELFORMAT_16BPP = 0x2,
DISPLAYCONFIG_PIXELFORMAT_24BPP = 0x3,
DISPLAYCONFIG_PIXELFORMAT_32BPP = 0x4,
DISPLAYCONFIG_PIXELFORMAT_NONGDI = 0x5,
DISPLAYCONFIG_PIXELFORMAT_FORCE_UINT32 = 0xFFFFFFFF,
};
