enum BUTTONPARTS : __int32
{
BUTTONPartFiller0 = 0x0,
BP_PUSHBUTTON = 0x1,
BP_RADIOBUTTON = 0x2,
BP_CHECKBOX = 0x3,
BP_GROUPBOX = 0x4,
BP_USERBUTTON = 0x5,
BP_COMMANDLINK = 0x6,
BP_COMMANDLINKGLYPH = 0x7,
};
