struct ActorVtbl
{
MobileObjectVtbl super;
SInt32 (__thiscall *GetFame)(Actor *this);
SInt32 (__thiscall *GetInfamy)(Actor *this);
void (__thiscall *Resurrect)(Actor *this, UInt32 unk1, UInt8 unk2, UInt8 unk3);
void (__thiscall *Unk_84)(Actor *this);
void (__thiscall *Unk_85)(Actor *this);
void (__thiscall *Unk_86)(Actor *this);
void (__thiscall *Unk_87)(Actor *this);
void (__thiscall *ApplyDamage)(Actor *this, float damage, float arg1, Actor *attacker);
int (__thiscall *GetDisposition)(Actor *, Actor *, SInt32);
void (__thiscall *ProcessControl)(Actor *this);
void (__thiscall *Unk_8B)(Actor *this);
void (__thiscall *SetPackageDismount)(Actor *this);
void (__thiscall *Unk_8D)(Actor *this);
void (__thiscall *Unk_8E)(Actor *this);
void (__thiscall *Unk_8F)(Actor *this);
void (__thiscall *OnAlarmAttack)(Actor *this, Actor *attackVictim, UInt32 arg1);
void (__thiscall *Unk_91)(Actor *this);
void (__thiscall *Unk_92)(Actor *this);
void (__thiscall *Unk_93)(Actor *this);
void (__thiscall *Unk_94)(Actor *this);
void (__thiscall *Unk_95)(Actor *this);
void (__thiscall *Unk_96)(Actor *this);
void (__thiscall *Unk_97)(Actor *this);
bool (__thiscall *HasVampireFed)(Actor *this);
void (__thiscall *SetVampireHasFed)(Actor *this, bool bFed);
void (__thiscall *Unk_9A)(Actor *this);
void (__thiscall *Unk_9B)(Actor *this);
void (__thiscall *SetTransparency)(Actor *this, bool enable, float amount);
void (__thiscall *Unk_9D)(Actor *this);
void (__thiscall *Unk_9E)(Actor *this);
void (__thiscall *Unk_9F)(Actor *this);
void (__thiscall *Unk_A0)(Actor *this);
SInt32 (__thiscall *GetActorValue)(Actor *this, AVCode avCode);
float (__thiscall *GetAV_F)(Actor *this, AVCode avCode);
void (__thiscall *SetAV_F)(Actor *this, UInt32 avCode, float val);
void (__thiscall *SetActorValue)(Actor *this, UInt32 avCode, UInt32 val);
void (__thiscall *ModMaxAV_F)(Actor *this, UInt32 avCode, float amt, Actor *arg2);
void (__thiscall *ModMaxAV)(Actor *this, UInt32 avCode, SInt32 amt, Actor *arg2);
void (__thiscall *ApplyScriptAVMod_F)(Actor *this, UInt32 avCode, float amt, UInt32 arg2);
void (__thiscall *ApplyScriptAVMod)(Actor *this, UInt32 avCode, SInt32 amt, Actor *arg2);
void (__thiscall *DamageAV_F)(Actor *this, UInt32 avCode, float amt, Actor *arg2);
void (__thiscall *DamageAV)(Actor *this, UInt32 value, UInt32 amount, UInt32 unk);
void (__thiscall *ModBaseAV_F)(Actor *this, UInt32 avCode, float amt);
void (__thiscall *ModBaseAV)(Actor *this, UInt32 avCode, SInt32 amt);
void (__thiscall *Unk_AD)(Actor *this);
void (__thiscall *Unk_AE)(Actor *this);
void (__thiscall *Unk_AF)(Actor *this);
void (__thiscall *Unk_B0)(Actor *this);
bool (__thiscall *DamageEquippedItem)(Actor *this, EntryData *entry, float damage, bool suppressArmorSkillModifiers); ///< bool __thiscall(Actor*, EntryData*, float damage, bool suppressArmorSkillModifiers). Base 0x5F3870; Player override 0x65FF10 suppresses damage in god mode.
void (__thiscall *Unk_B2)(Actor *this);
void (__thiscall *Unk_B3)(Actor *this, TESObjectREFR *activatedRefr, UInt32 quantity);
void (__thiscall *Unk_B4)(Actor *this);
void (__thiscall *Unk_B5)(Actor *this);
void (__thiscall *Unk_B6)(Actor *this);
void (__thiscall *Unk_B7)(Actor *this);
void (__thiscall *Unk_B8)(Actor *this);
void (__thiscall *Unk_B9)(Actor *this);
void (__thiscall *Unk_BA)(Actor *this); ///< void __thiscall(Actor*). Called unconditionally after bow projectile construction/optional manager insertion. Base Actor target 0x60D0A0 is no-op; Player target 0x662590 consumes one equipped AMMO unless god mode.
void (__thiscall *Unk_BB)(Actor *this);
void (__thiscall *Unk_BC)(Actor *this);
void (__thiscall *Unk_BD)(Actor *this);
void (__thiscall *Unk_BE)(Actor *this);
void (__thiscall *Unk_BF)(Actor *this);
void (__thiscall *Unk_C0)(Actor *this);
void (__thiscall *Unk_C1)(Actor *this);
void (__thiscall *Unk_C2)(Actor *this);
void (__thiscall *CleanupCurrentPackage)(Actor *this);
void (__thiscall *ManageAlarm)(Actor *this);
void (__thiscall *Unk_C5)(Actor *this);
void (__thiscall *Unk_C6)(Actor *this);
void (__thiscall *Unk_C7)(Actor *this);
void (__thiscall *AddPackageWakeUp)(Actor *this);
void (__thiscall *Unk_C9)(Actor *this);
void (__thiscall *Unk_CA)(Actor *this);
void (__thiscall *Unk_CB)(Actor *this);
CombatController *(__thiscall *GetCombatController)(Actor *this);
bool (__thiscall *IsInCombat)(Actor *this, bool unk);
TESForm *(__thiscall *GetCombatTarget)(Actor *this);
void (__thiscall *Unk_CF)(Actor *this);
void (__thiscall *Unk_D0)(Actor *this);
void (__thiscall *Unk_D1)(Actor *this);
void (__thiscall *Unk_D2)(Actor *this);
void (__thiscall *Unk_D3)(Actor *this);
bool (__thiscall *IsYielding)(Actor *this);
bool (__thiscall *IsTresspassing)(Actor *this);
void (__thiscall *Unk_D6)(Actor *this);
void (__thiscall *Unk_D7)(Actor *this);
void (__thiscall *Unk_D8)(Actor *this);
void (__thiscall *Unk_D9)(Actor *this);
void (__thiscall *Unk_DA)(Actor *this);
void (__thiscall *Unk_DB)(Actor *this);
void (__thiscall *Yeld)(Actor *this);
void (__thiscall *Unk_DD)(Actor *this);
void (__thiscall *Unk_DE)(Actor *this);
void (__thiscall *Unk_DF)(Actor *this);
Creature *(__thiscall *GetMountedHorse)(Actor *this);
void (__thiscall *Unk_E1)(Actor *this);
void (__thiscall *Unk_E2)(Actor *this);
void (__thiscall *Unk_E3)(Actor *this);
void (__thiscall *Unk_E4)(Actor *this);
void (__thiscall *Unk_E5)(Actor *this);
void (__thiscall *Unk_E6)(Actor *this);
void (__thiscall *ModExperience)(Actor *this, UInt32 actorValue, UInt32 scaleIndex, float baseDelta);
void (__thiscall *Unk_E8)(Actor *this);
void (__thiscall *Unk_E9)(Actor *this);
void (__thiscall *Unk_EA)(Actor *this);
void (__thiscall *AttackHandling)(Actor *this, UInt32 unused, TESObjectREFR *arrowRef, TESObjectREFR *target);
void (__thiscall *Unk_EC)(Actor *this);
void (__thiscall *Unk_ED)(Actor *this);
void (__thiscall *OnHealthDamage)(Actor *this, Actor *attacker, float damage);
};
