enum SIZEBOXSTATES : __int32
{
SZB_RIGHTALIGN = 0x1,
SZB_LEFTALIGN = 0x2,
SZB_TOPRIGHTALIGN = 0x3,
SZB_TOPLEFTALIGN = 0x4,
SZB_HALFBOTTOMRIGHTALIGN = 0x5,
SZB_HALFBOTTOMLEFTALIGN = 0x6,
SZB_HALFTOPRIGHTALIGN = 0x7,
SZB_HALFTOPLEFTALIGN = 0x8,
};
