int __usercall Actor_AttackHandling_::RunOnHitByScript_@<eax>(
        int a1@<edi>,
        int a2@<esi>,
        int ebp0@<ebp>,
        double st5_0@<st2>,
        double st6_0@<st1>,
        int a6,
        int a7,
        int a8,
        int a9,
        int a10,
        int a11,
        int a12,
        int a13,
        int a14,
        int a15,
        int a16,
        int a17,
        int a18,
        int a19,
        int a20,
        int a21,
        int a22,
        int a23,
        int a24,
        float a25)
{
  return Actor_AttackHandling_::RunOnHitByScript(
           a1,
           a2,
           ebp0,
           st5_0,
           st6_0,
           a6,
           a7,
           a8,
           a9,
           a10,
           a11,
           a12,
           a13,
           a14,
           a15,
           a16,
           a17,
           a18,
           a19,
           a20,
           a21,
           a22,
           a23,
           a24,
           a25);
}
