struct __declspec(align(8)) _D3DKMT_SETVIDPNSOURCEOWNER
{
D3DKMT_HANDLE hDevice;
const D3DKMT_VIDPNSOURCEOWNER_TYPE *pType;
const D3DDDI_VIDEO_PRESENT_SOURCE_ID *pVidPnSourceId;
UINT VidPnSourceCount;
};
