enum mwMediumArmor_OblivionActorValue
{
OBL_AV_Strength = 0x0,
OBL_AV_Intelligence = 0x1,
OBL_AV_Willpower = 0x2,
OBL_AV_Agility = 0x3,
OBL_AV_Speed = 0x4,
OBL_AV_Endurance = 0x5,
OBL_AV_Personality = 0x6,
OBL_AV_Luck = 0x7,
OBL_AV_Armorer = 0xC,
OBL_AV_Athletics = 0xD,
OBL_AV_Blade = 0xE,
OBL_AV_Block = 0xF,
OBL_AV_Blunt = 0x10,
OBL_AV_HandToHand = 0x11,
OBL_AV_HeavyArmor = 0x12,
OBL_AV_Alchemy = 0x13,
OBL_AV_Alteration = 0x14,
OBL_AV_Conjuration = 0x15,
OBL_AV_Destruction = 0x16,
OBL_AV_Illusion = 0x17,
OBL_AV_Mysticism = 0x18,
OBL_AV_Restoration = 0x19,
OBL_AV_Acrobatics = 0x1A,
OBL_AV_LightArmor = 0x1B,
OBL_AV_Marksman = 0x1C,
OBL_AV_Mercantile = 0x1D,
OBL_AV_Security = 0x1E,
OBL_AV_Sneak = 0x1F,
OBL_AV_Speechcraft = 0x20,
};
