enum hkMaterial
{
kMaterial_Stone = 0x0,
kMaterial_Cloth = 0x1,
kMaterial_Dirt = 0x2,
kMaterial_Glass = 0x3,
kMaterial_Grass = 0x4,
kMaterial_Metal = 0x5,
kMaterial_Organic = 0x6,
kMaterial_Skin = 0x7,
kMaterial_Water = 0x8,
kMaterial_Wood = 0x9,
kMaterial_HeavyStone = 0xA,
kMaterial_HeavyMetal = 0xB,
kMaterial_HeavyWood = 0xC,
kMaterial_Chain = 0xD,
kMaterial_Snow = 0xE,
kMaterial_StoneStairs = 0xF,
kMaterial_ClothStairs = 0x10,
kMaterial_DirtStairs = 0x11,
kMaterial_GlassStairs = 0x12,
kMaterial_GrassStairs = 0x13,
kMaterial_MetalStairs = 0x14,
kMaterial_OrganicStairs = 0x15,
kMaterial_SkinStairs = 0x16,
kMaterial_WaterStairs = 0x17,
kMaterial_WoodStairs = 0x18,
kMaterial_HeavyStoneStairs = 0x19,
kMaterial_HeavyMetalStairs = 0x1A,
kMaterial_HeavyWoodStairs = 0x1B,
kMaterial_ChainStairs = 0x1C,
kMaterial_SnowStairs = 0x1D,
kMaterial_Elevator = 0x1E,
kMaterial_Default = 0x1F,
};
