enum _D3DLIGHTSTATETYPE
{
D3DLIGHTSTATE_MATERIAL = 0x1,
D3DLIGHTSTATE_AMBIENT = 0x2,
D3DLIGHTSTATE_COLORMODEL = 0x3,
D3DLIGHTSTATE_FOGMODE = 0x4,
D3DLIGHTSTATE_FOGSTART = 0x5,
D3DLIGHTSTATE_FOGEND = 0x6,
D3DLIGHTSTATE_FOGDENSITY = 0x7,
D3DLIGHTSTATE_FORCE_DWORD = 0x7FFFFFFF,
};
