struct TESFormVtbl
{
BaseFormComponentVtbl super;
void (__thiscall *Destroy)(TESForm *this, bool Dealloc);
void (__thiscall *Unk_05)(TESForm *this);
void (__thiscall *Unk_06)(TESForm *this);
bool (__thiscall *LoadForm)(TESForm *this, void *modEntry);
void (__thiscall *Unk_08)(TESForm *this);
void (__thiscall *Unk_09)(TESForm *this);
void (__thiscall *Unk_0A)(TESForm *this);
void (__thiscall *Unk_0B)(TESForm *this);
void (__thiscall *Unk_0C)(TESForm *this);
void (__thiscall *Unk_0D)(TESForm *this);
void (__thiscall *Unk_0E)(TESForm *this);
void (__thiscall *Unk_0F)(TESForm *this);
void (__thiscall *MarkAsModified)(TESForm *this, UInt32 mask);
void (__thiscall *ClearModified)(TESForm *this, UInt32 mask);
void (__thiscall *Unk_12)(TESForm *this);
UInt32 (__thiscall *GetSaveSize)(TESForm *this, UInt32 modifiedMask);
void (__thiscall *SaveGame)(TESForm *this, UInt32 modifiedMask);
void (__thiscall *LoadGame)(TESForm *this, UInt32 modifiedMask, UInt32 unk);
void (__thiscall *Unk_16)(TESForm *this);
void (__thiscall *Unk_17)(TESForm *this);
void (__thiscall *Unk_18)(TESForm *this);
void (__thiscall *Unk_19)(TESForm *this);
bool (__thiscall *SeekRecordTypeFast)(TESForm *this, Data *);
void (__thiscall *DoPostFixup)(TESForm *this);
void (__thiscall *Unk_1C)(TESForm *this);
void (__thiscall *GetDescription)(TESForm *this, BSStringT *dst);
void (__thiscall *Unk_1E)(TESForm *this);
void (__thiscall *Unk_1F)(TESForm *this);
void (__thiscall *Unk_20)(TESForm *this);
void (__thiscall *Unk_21)(TESForm *this);
void (__thiscall *Unk_22)(TESForm *this);
void (__thiscall *Unk_23)(TESForm *this);
void (__thiscall *SetFromActiveFile)(TESForm *this, UInt8 arg);
void (__thiscall *SetQuestItem)(TESForm *this, bool isQuestItem);
void (__thiscall *Unk_26)(TESForm *this);
void (__thiscall *Unk_27)(TESForm *this);
void (__thiscall *Unk_28)(TESForm *this);
bool (__thiscall *Unk_29)(TESForm *this);
bool (__thiscall *Unk_2A)(TESForm *this);
bool (__thiscall *Unk_2B)(TESForm *this);
void (__thiscall *Unk_2C)(TESForm *this);
void (__thiscall *CopyFrom)(TESForm *form);
bool (__thiscall *Compare)(TESForm *form);
void (__thiscall *Unk_2F)(TESForm *this);
void (__thiscall *Unk_30)(TESForm *this);
void (__thiscall *Unk_31)(TESForm *this);
void (__thiscall *Unk_32)(TESForm *this);
bool (__thiscall *Unk_33)(TESForm *this, TESObjectREFR *refr0, TESObjectREFR *refr1, UInt32 unk2);
const char *(__thiscall *GetName)(TESForm *this);
const char *(__thiscall *GetEditorName)(TESForm *this);
void (__thiscall *SetEditorID)(TESForm *this, const char *name);
};
