struct __declspec(align(8)) gdi_dc_funcs
{
INT (*pAbortDoc)(PHYSDEV) __offset(OFF64|AUTO);
BOOL (*pAbortPath)(PHYSDEV) __offset(OFF64|AUTO);
BOOL (*pAlphaBlend)(PHYSDEV, bitblt_coords *, PHYSDEV, bitblt_coords *, BLENDFUNCTION) __offset(OFF64|AUTO);
BOOL (*pAngleArc)(PHYSDEV, INT, INT, DWORD, FLOAT, FLOAT) __offset(OFF64|AUTO);
BOOL (*pArc)(PHYSDEV, INT, INT, INT, INT, INT, INT, INT, INT) __offset(OFF64|AUTO);
BOOL (*pArcTo)(PHYSDEV, INT, INT, INT, INT, INT, INT, INT, INT) __offset(OFF64|AUTO);
BOOL (*pBeginPath)(PHYSDEV) __offset(OFF64|AUTO);
DWORD (*pBlendImage)(PHYSDEV, BITMAPINFO *, const gdi_image_bits *, bitblt_coords *, bitblt_coords *, BLENDFUNCTION) __offset(OFF64|AUTO);
BOOL (*pChord)(PHYSDEV, INT, INT, INT, INT, INT, INT, INT, INT) __offset(OFF64|AUTO);
BOOL (*pCloseFigure)(PHYSDEV) __offset(OFF64|AUTO);
BOOL (*pCreateCompatibleDC)(PHYSDEV, PHYSDEV *) __offset(OFF64|AUTO);
BOOL (*pCreateDC)(PHYSDEV *, LPCWSTR, LPCWSTR, LPCWSTR, const DEVMODEW *) __offset(OFF64|AUTO);
BOOL (*pDeleteDC)(PHYSDEV) __offset(OFF64|AUTO);
BOOL (*pDeleteObject)(PHYSDEV, HGDIOBJ) __offset(OFF64|AUTO);
DWORD (*pDeviceCapabilities)(LPSTR, LPCSTR, LPCSTR, WORD, LPSTR, LPDEVMODEA) __offset(OFF64|AUTO);
BOOL (*pEllipse)(PHYSDEV, INT, INT, INT, INT) __offset(OFF64|AUTO);
INT (*pEndDoc)(PHYSDEV) __offset(OFF64|AUTO);
INT (*pEndPage)(PHYSDEV) __offset(OFF64|AUTO);
BOOL (*pEndPath)(PHYSDEV) __offset(OFF64|AUTO);
BOOL (*pEnumFonts)(PHYSDEV, LPLOGFONTW, FONTENUMPROCW, LPARAM_0) __offset(OFF64|AUTO);
INT (*pEnumICMProfiles)(PHYSDEV, ICMENUMPROCW, LPARAM_0) __offset(OFF64|AUTO);
INT (*pExcludeClipRect)(PHYSDEV, INT, INT, INT, INT) __offset(OFF64|AUTO);
INT (*pExtDeviceMode)(LPSTR, HWND, LPDEVMODEA, LPSTR, LPSTR, LPDEVMODEA, LPSTR, DWORD) __offset(OFF64|AUTO);
INT (*pExtEscape)(PHYSDEV, INT, INT, LPCVOID, INT, LPVOID) __offset(OFF64|AUTO);
BOOL (*pExtFloodFill)(PHYSDEV, INT, INT, COLORREF, UINT) __offset(OFF64|AUTO);
INT (*pExtSelectClipRgn)(PHYSDEV, HRGN, INT) __offset(OFF64|AUTO);
BOOL (*pExtTextOut)(PHYSDEV, INT, INT, UINT, const RECT *, LPCWSTR, UINT, const INT *) __offset(OFF64|AUTO);
BOOL (*pFillPath)(PHYSDEV) __offset(OFF64|AUTO);
BOOL (*pFillRgn)(PHYSDEV, HRGN, HBRUSH) __offset(OFF64|AUTO);
BOOL (*pFlattenPath)(PHYSDEV) __offset(OFF64|AUTO);
BOOL (*pFontIsLinked)(PHYSDEV) __offset(OFF64|AUTO);
BOOL (*pFrameRgn)(PHYSDEV, HRGN, HBRUSH, INT, INT) __offset(OFF64|AUTO);
BOOL (*pGdiComment)(PHYSDEV, UINT, const BYTE *) __offset(OFF64|AUTO);
UINT (*pGetBoundsRect)(PHYSDEV, RECT *, UINT) __offset(OFF64|AUTO);
BOOL (*pGetCharABCWidths)(PHYSDEV, UINT, UINT, LPABC) __offset(OFF64|AUTO);
BOOL (*pGetCharABCWidthsI)(PHYSDEV, UINT, UINT, WORD *, LPABC) __offset(OFF64|AUTO);
BOOL (*pGetCharWidth)(PHYSDEV, UINT, UINT, LPINT) __offset(OFF64|AUTO);
BOOL (*pGetCharWidthInfo)(PHYSDEV, void *) __offset(OFF64|AUTO);
INT (*pGetDeviceCaps)(PHYSDEV, INT) __offset(OFF64|AUTO);
BOOL (*pGetDeviceGammaRamp)(PHYSDEV, LPVOID) __offset(OFF64|AUTO);
DWORD (*pGetFontData)(PHYSDEV, DWORD, DWORD, LPVOID, DWORD) __offset(OFF64|AUTO);
BOOL (*pGetFontRealizationInfo)(PHYSDEV, void *) __offset(OFF64|AUTO);
DWORD (*pGetFontUnicodeRanges)(PHYSDEV, LPGLYPHSET) __offset(OFF64|AUTO);
DWORD (*pGetGlyphIndices)(PHYSDEV, LPCWSTR, INT, LPWORD, DWORD) __offset(OFF64|AUTO);
DWORD (*pGetGlyphOutline)(PHYSDEV, UINT, UINT, LPGLYPHMETRICS, DWORD, LPVOID, const MAT2 *) __offset(OFF64|AUTO);
BOOL (*pGetICMProfile)(PHYSDEV, LPDWORD, LPWSTR) __offset(OFF64|AUTO);
DWORD (*pGetImage)(PHYSDEV, BITMAPINFO *, gdi_image_bits *, bitblt_coords *) __offset(OFF64|AUTO);
DWORD (*pGetKerningPairs)(PHYSDEV, DWORD, LPKERNINGPAIR) __offset(OFF64|AUTO);
COLORREF (*pGetNearestColor)(PHYSDEV, COLORREF) __offset(OFF64|AUTO);
UINT (*pGetOutlineTextMetrics)(PHYSDEV, UINT, LPOUTLINETEXTMETRICW) __offset(OFF64|AUTO);
COLORREF (*pGetPixel)(PHYSDEV, INT, INT) __offset(OFF64|AUTO);
UINT (*pGetSystemPaletteEntries)(PHYSDEV, UINT, UINT, LPPALETTEENTRY) __offset(OFF64|AUTO);
UINT (*pGetTextCharsetInfo)(PHYSDEV, LPFONTSIGNATURE, DWORD) __offset(OFF64|AUTO);
BOOL (*pGetTextExtentExPoint)(PHYSDEV, LPCWSTR, INT, LPINT) __offset(OFF64|AUTO);
BOOL (*pGetTextExtentExPointI)(PHYSDEV, const WORD *, INT, LPINT) __offset(OFF64|AUTO);
INT (*pGetTextFace)(PHYSDEV, INT, LPWSTR) __offset(OFF64|AUTO);
BOOL (*pGetTextMetrics)(PHYSDEV, TEXTMETRICW *) __offset(OFF64|AUTO);
BOOL (*pGradientFill)(PHYSDEV, TRIVERTEX *, ULONG, void *, ULONG, ULONG) __offset(OFF64|AUTO);
INT (*pIntersectClipRect)(PHYSDEV, INT, INT, INT, INT) __offset(OFF64|AUTO);
BOOL (*pInvertRgn)(PHYSDEV, HRGN) __offset(OFF64|AUTO);
BOOL (*pLineTo)(PHYSDEV, INT, INT) __offset(OFF64|AUTO);
BOOL (*pModifyWorldTransform)(PHYSDEV, const XFORM *, DWORD) __offset(OFF64|AUTO);
BOOL (*pMoveTo)(PHYSDEV, INT, INT) __offset(OFF64|AUTO);
INT (*pOffsetClipRgn)(PHYSDEV, INT, INT) __offset(OFF64|AUTO);
BOOL (*pOffsetViewportOrgEx)(PHYSDEV, INT, INT, POINT *) __offset(OFF64|AUTO);
BOOL (*pOffsetWindowOrgEx)(PHYSDEV, INT, INT, POINT *) __offset(OFF64|AUTO);
BOOL (*pPaintRgn)(PHYSDEV, HRGN) __offset(OFF64|AUTO);
BOOL (*pPatBlt)(PHYSDEV, bitblt_coords *, DWORD) __offset(OFF64|AUTO);
BOOL (*pPie)(PHYSDEV, INT, INT, INT, INT, INT, INT, INT, INT) __offset(OFF64|AUTO);
BOOL (*pPolyBezier)(PHYSDEV, const POINT *, DWORD) __offset(OFF64|AUTO);
BOOL (*pPolyBezierTo)(PHYSDEV, const POINT *, DWORD) __offset(OFF64|AUTO);
BOOL (*pPolyDraw)(PHYSDEV, const POINT *, const BYTE *, DWORD) __offset(OFF64|AUTO);
BOOL (*pPolyPolygon)(PHYSDEV, const POINT *, const INT *, UINT) __offset(OFF64|AUTO);
BOOL (*pPolyPolyline)(PHYSDEV, const POINT *, const DWORD *, DWORD) __offset(OFF64|AUTO);
BOOL (*pPolygon)(PHYSDEV, const POINT *, INT) __offset(OFF64|AUTO);
BOOL (*pPolyline)(PHYSDEV, const POINT *, INT) __offset(OFF64|AUTO);
BOOL (*pPolylineTo)(PHYSDEV, const POINT *, INT) __offset(OFF64|AUTO);
DWORD (*pPutImage)(PHYSDEV, HRGN, BITMAPINFO *, const gdi_image_bits *, bitblt_coords *, bitblt_coords *, DWORD) __offset(OFF64|AUTO);
UINT (*pRealizeDefaultPalette)(PHYSDEV) __offset(OFF64|AUTO);
UINT (*pRealizePalette)(PHYSDEV, HPALETTE, BOOL) __offset(OFF64|AUTO);
BOOL (*pRectangle)(PHYSDEV, INT, INT, INT, INT) __offset(OFF64|AUTO);
HDC (*pResetDC)(PHYSDEV, const DEVMODEW *) __offset(OFF64|AUTO);
BOOL (*pRestoreDC)(PHYSDEV, INT) __offset(OFF64|AUTO);
BOOL (*pRoundRect)(PHYSDEV, INT, INT, INT, INT, INT, INT) __offset(OFF64|AUTO);
INT (*pSaveDC)(PHYSDEV) __offset(OFF64|AUTO);
BOOL (*pScaleViewportExtEx)(PHYSDEV, INT, INT, INT, INT, SIZE *) __offset(OFF64|AUTO);
BOOL (*pScaleWindowExtEx)(PHYSDEV, INT, INT, INT, INT, SIZE *) __offset(OFF64|AUTO);
HBITMAP (*pSelectBitmap)(PHYSDEV, HBITMAP) __offset(OFF64|AUTO);
HBRUSH (*pSelectBrush)(PHYSDEV, HBRUSH, const brush_pattern *) __offset(OFF64|AUTO);
BOOL (*pSelectClipPath)(PHYSDEV, INT) __offset(OFF64|AUTO);
HFONT (*pSelectFont)(PHYSDEV, HFONT, UINT *) __offset(OFF64|AUTO);
HPALETTE (*pSelectPalette)(PHYSDEV, HPALETTE, BOOL) __offset(OFF64|AUTO);
HPEN (*pSelectPen)(PHYSDEV, HPEN, const brush_pattern *) __offset(OFF64|AUTO);
INT (*pSetArcDirection)(PHYSDEV, INT) __offset(OFF64|AUTO);
COLORREF (*pSetBkColor)(PHYSDEV, COLORREF) __offset(OFF64|AUTO);
INT (*pSetBkMode)(PHYSDEV, INT) __offset(OFF64|AUTO);
UINT (*pSetBoundsRect)(PHYSDEV, RECT *, UINT) __offset(OFF64|AUTO);
COLORREF (*pSetDCBrushColor)(PHYSDEV, COLORREF) __offset(OFF64|AUTO);
COLORREF (*pSetDCPenColor)(PHYSDEV, COLORREF) __offset(OFF64|AUTO);
INT (*pSetDIBitsToDevice)(PHYSDEV, INT, INT, DWORD, DWORD, INT, INT, UINT, UINT, LPCVOID, BITMAPINFO *, UINT) __offset(OFF64|AUTO);
void (*pSetDeviceClipping)(PHYSDEV, HRGN) __offset(OFF64|AUTO);
BOOL (*pSetDeviceGammaRamp)(PHYSDEV, LPVOID) __offset(OFF64|AUTO);
DWORD (*pSetLayout)(PHYSDEV, DWORD) __offset(OFF64|AUTO);
INT (*pSetMapMode)(PHYSDEV, INT) __offset(OFF64|AUTO);
DWORD (*pSetMapperFlags)(PHYSDEV, DWORD) __offset(OFF64|AUTO);
COLORREF (*pSetPixel)(PHYSDEV, INT, INT, COLORREF) __offset(OFF64|AUTO);
INT (*pSetPolyFillMode)(PHYSDEV, INT) __offset(OFF64|AUTO);
INT (*pSetROP2)(PHYSDEV, INT) __offset(OFF64|AUTO);
INT (*pSetRelAbs)(PHYSDEV, INT) __offset(OFF64|AUTO);
INT (*pSetStretchBltMode)(PHYSDEV, INT) __offset(OFF64|AUTO);
UINT (*pSetTextAlign)(PHYSDEV, UINT) __offset(OFF64|AUTO);
INT (*pSetTextCharacterExtra)(PHYSDEV, INT) __offset(OFF64|AUTO);
COLORREF (*pSetTextColor)(PHYSDEV, COLORREF) __offset(OFF64|AUTO);
BOOL (*pSetTextJustification)(PHYSDEV, INT, INT) __offset(OFF64|AUTO);
BOOL (*pSetViewportExtEx)(PHYSDEV, INT, INT, SIZE *) __offset(OFF64|AUTO);
BOOL (*pSetViewportOrgEx)(PHYSDEV, INT, INT, POINT *) __offset(OFF64|AUTO);
BOOL (*pSetWindowExtEx)(PHYSDEV, INT, INT, SIZE *) __offset(OFF64|AUTO);
BOOL (*pSetWindowOrgEx)(PHYSDEV, INT, INT, POINT *) __offset(OFF64|AUTO);
BOOL (*pSetWorldTransform)(PHYSDEV, const XFORM *) __offset(OFF64|AUTO);
INT (*pStartDoc)(PHYSDEV, const DOCINFOW *) __offset(OFF64|AUTO);
INT (*pStartPage)(PHYSDEV) __offset(OFF64|AUTO);
BOOL (*pStretchBlt)(PHYSDEV, bitblt_coords *, PHYSDEV, bitblt_coords *, DWORD) __offset(OFF64|AUTO);
INT (*pStretchDIBits)(PHYSDEV, INT, INT, INT, INT, INT, INT, INT, INT, const void *, BITMAPINFO *, UINT, DWORD) __offset(OFF64|AUTO);
BOOL (*pStrokeAndFillPath)(PHYSDEV) __offset(OFF64|AUTO);
BOOL (*pStrokePath)(PHYSDEV) __offset(OFF64|AUTO);
BOOL (*pUnrealizePalette)(HPALETTE) __offset(OFF64|AUTO);
BOOL (*pWidenPath)(PHYSDEV) __offset(OFF64|AUTO);
NTSTATUS (*pD3DKMTCheckVidPnExclusiveOwnership)(const D3DKMT_CHECKVIDPNEXCLUSIVEOWNERSHIP *) __offset(OFF64|AUTO);
NTSTATUS (*pD3DKMTSetVidPnSourceOwner)(const D3DKMT_SETVIDPNSOURCEOWNER *) __offset(OFF64|AUTO);
opengl_funcs *(*wine_get_wgl_driver)(PHYSDEV, UINT) __offset(OFF64|AUTO);
const vulkan_funcs *(*wine_get_vulkan_driver)(PHYSDEV, UINT) __offset(OFF64|AUTO);
UINT priority;
};
