enum CHECKBOXSTATES : __int32
{
CHECKBOXStateFiller0 = 0x0,
CBS_UNCHECKEDNORMAL = 0x1,
CBS_UNCHECKEDHOT = 0x2,
CBS_UNCHECKEDPRESSED = 0x3,
CBS_UNCHECKEDDISABLED = 0x4,
CBS_CHECKEDNORMAL = 0x5,
CBS_CHECKEDHOT = 0x6,
CBS_CHECKEDPRESSED = 0x7,
CBS_CHECKEDDISABLED = 0x8,
CBS_MIXEDNORMAL = 0x9,
CBS_MIXEDHOT = 0xA,
CBS_MIXEDPRESSED = 0xB,
CBS_MIXEDDISABLED = 0xC,
};
