// Verified (Oblivion): initializes the 0xE0-byte TESEffectShaderData block at TESEffectShader+0x18, including cFlags, blend defaults, particle lifetimes/velocity/scale/colors, and the byte/float values copied by TESEffectShader_ConfigureVisualProperty. Probable member names come from the matching Fallout EffectShaderData layout; the defaults and offsets are directly corroborated in Oblivion.
unsigned int __thiscall TESEffectShaderData_InitializeDefaults(TESEffectShaderData *this)
{
  this->fFillAlphaFadeInTime = 0.0; /*0x4ac9c7*/
  this->cFlags = 0;                             // Verified (Oblivion): TESEffectShaderData_InitializeDefaults zeroes Data.cFlags. Individual set-bit semantics are established at the MagicShaderHitEffect_InitializeVisual callsites: 0x01 suppresses texture-effect-data setup; 0x08 suppresses the particle-property path. /*0x4ac9ca*/
  this->fFillAlphaFullTime = 0.0; /*0x4ac9cc*/
  this->iFillColor = 0; /*0x4ac9cf*/
  this->fFillAlphaFadeOutTime = 0.0; /*0x4ac9d2*/
  this->iEdgeColor = 0; /*0x4ac9d5*/
  this->fFillAlphaPersistentPercent = 0.0; /*0x4ac9d8*/
  this->fFillAlphaPulseAmplitude = 0.0; /*0x4ac9e0*/
  this->eTextureBlendModeDest = 6; /*0x4ac9e3*/
  this->eParticleBlendModeDest = 6; /*0x4ac9e8*/
  this->fFillAlphaPulseFrequency = 1.0; /*0x4ac9eb*/
  this->fEdgeExponentValue = 1.0; /*0x4ac9f3*/
  this->eTextureBlendOperation = 1; /*0x4ac9f6*/
  this->eParticleBlendOperation = 1; /*0x4ac9fb*/
  this->fFillTextureUAnimSpeed = 0.0; /*0x4ac9fe*/
  this->eTextureBlendModeSource = 5; /*0x4aca01*/
  this->fFillTextureVAnimSpeed = 0.0; /*0x4aca08*/
  this->eTextureZTestFunction = 3; /*0x4aca0b*/
  this->fEdgeAlphaFadeInTime = 0.0; /*0x4aca12*/
  this->eParticleBlendModeSource = 5; /*0x4aca15*/
  this->fEdgeAlphaFullTime = 0.0; /*0x4aca1c*/
  this->eParticleZTestFunction = 4; /*0x4aca1f*/
  this->fEdgeAlphaFadeOutTime = 0.0; /*0x4aca26*/
  this->fEdgeAlphaPersistentPercent = 0.0; /*0x4aca29*/
  this->fEdgeAlphaPulseAmplitude = 0.0; /*0x4aca2c*/
  this->fEdgeAlphaPulseFrequency = 1.0; /*0x4aca31*/
  this->fFillAlphaFullPercent = 1.0; /*0x4aca34*/
  this->fEdgeAlphaFullPercent = 1.0; /*0x4aca37*/
  this->fParticleFadeInTime = 0.0; /*0x4aca3c*/
  this->fParticleFullTime = 0.0; /*0x4aca3f*/
  this->fParticleFadeOutTime = 0.0; /*0x4aca42*/
  this->fParticleLifeVar = 0.0; /*0x4aca45*/
  this->fParticleNormalSpeed = 0.0; /*0x4aca4b*/
  this->fParticleNormalAcc = 0.0; /*0x4aca51*/
  this->fParticleFull = 1.0; /*0x4aca6b*/
  this->ParticleVelocity.x = 0.0; /*0x4aca6e*/
  this->fParticlePersistent = 1.0; /*0x4aca78*/
  this->fParticleLifetime = 1.0; /*0x4aca7e*/
  this->ParticleVelocity.y = 0.0; /*0x4aca84*/
  this->ParticleVelocity.z = 0.0; /*0x4aca8c*/
  this->fParticleScale1 = 1.0; /*0x4acaa6*/
  this->ParticleAcceleration.x = 0.0; /*0x4acaac*/
  this->fParticleScale2 = 1.0; /*0x4acab6*/
  this->fParticleScale2Time = 1.0; /*0x4acabc*/
  this->ParticleAcceleration.y = 0.0; /*0x4acac2*/
  this->fParticleScale1Time = 0.0; /*0x4acacf*/
  this->ParticleAcceleration.z = 0.0; /*0x4acad5*/
  this->iParticleColor1 = 0xFFFFFF; /*0x4acadd*/
  this->fParticleColor1Alpha = 1.0; /*0x4acae3*/
  this->iParticleColor2 = 0xFFFFFF; /*0x4acae9*/
  this->fParticleColor2Alpha = 1.0; /*0x4acaef*/
  this->iParticleColor3 = 0xFFFFFF; /*0x4acaf5*/
  this->fParticleColor3Alpha = 1.0; /*0x4acafb*/
  this->fParticleColor1Time = 0.0; /*0x4acb03*/
  this->fParticleColor2Time = kHeadBodyNormalMatchRadius; /*0x4acb0f*/
  this->fParticleColor3Time = 1.0; /*0x4acb15*/
  return 0xFFFFFF; /*0x4acb1b*/
}
