enum PERCEIVED : __int32
{
PERCEIVED_TYPE_UNKNOWN = 0x0,
PERCEIVED_TYPE_TEXT = 0x1,
PERCEIVED_TYPE_IMAGE = 0x2,
PERCEIVED_TYPE_AUDIO = 0x3,
PERCEIVED_TYPE_VIDEO = 0x4,
PERCEIVED_TYPE_COMPRESSED = 0x5,
PERCEIVED_TYPE_DOCUMENT = 0x6,
PERCEIVED_TYPE_SYSTEM = 0x7,
PERCEIVED_TYPE_APPLICATION = 0x8,
PERCEIVED_TYPE_GAMEMEDIA = 0x9,
PERCEIVED_TYPE_CONTACTS = 0xA,
PERCEIVED_TYPE_CUSTOM = 0xFFFFFFFD,
PERCEIVED_TYPE_UNSPECIFIED = 0xFFFFFFFE,
PERCEIVED_TYPE_FOLDER = 0xFFFFFFFF,
};
