int __usercall Actor_AttackHandling_::__@<eax>(
        int (*a1)(void)@<edx>,
        int a2@<ebp>,
        int a3@<edi>,
        char bl0@<bl>,
        int esi0@<esi>,
        int a6,
        int a7,
        int a8,
        int a9,
        int a10,
        float a11,
        int a12,
        int a13,
        int a14,
        int a15,
        int a16,
        int a17,
        int a18,
        int a19,
        int a20,
        int a21,
        int a22,
        int a23,
        int a24,
        int a25,
        int a26,
        int a27,
        int a28,
        int a29)
{
  int v29; // eax

  v29 = a1();
  (*(void (__thiscall **)(int, int))(a2 + 0x210))(a3, v29 + 1);
  (*(void (__thiscall **)(int, int))(*(_DWORD *)a3 + 0x218))(a3, a29);
  return Actor_AttackHandling_::ApplyNormalWeaponResistance(
           bl0,
           a3,
           esi0,
           a6,
           a7,
           a8,
           a9,
           a10,
           a11,
           a12,
           a13,
           a14,
           a15,
           a16,
           a17,
           a18,
           a19,
           a20,
           a21,
           a22,
           a23,
           a24,
           a25);
}
