union $F544424FCBA3464EB82EB5986A3D7567
{
SERVICE_DESCRIPTIONA *descr __offset(OFF64|AUTO);
SERVICE_FAILURE_ACTIONSA *actions __offset(OFF64|AUTO);
SERVICE_DELAYED_AUTO_START_INFO *delayedstart __offset(OFF64|AUTO);
SERVICE_FAILURE_ACTIONS_FLAG *actionsflag __offset(OFF64|AUTO);
SERVICE_SID_INFO *sid __offset(OFF64|AUTO);
SERVICE_RPC_REQUIRED_PRIVILEGES_INFO *privinfo __offset(OFF64|AUTO);
SERVICE_PRESHUTDOWN_INFO *preshutdown __offset(OFF64|AUTO);
};
