enum irp_type : __int32
{
IRP_CALL_NONE = 0x0,
IRP_CALL_CREATE = 0x1,
IRP_CALL_CLOSE = 0x2,
IRP_CALL_READ = 0x3,
IRP_CALL_WRITE = 0x4,
IRP_CALL_FLUSH = 0x5,
IRP_CALL_IOCTL = 0x6,
IRP_CALL_VOLUME = 0x7,
IRP_CALL_FREE = 0x8,
IRP_CALL_CANCEL = 0x9,
};
