enum COMBOBOXPARTS_0 : __int32
{
CP_DROPDOWNBUTTON_0 = 0x1,
CP_BACKGROUND = 0x2,
CP_TRANSPARENTBACKGROUND = 0x3,
CP_BORDER = 0x4,
CP_READONLY = 0x5,
CP_DROPDOWNBUTTONRIGHT = 0x6,
CP_DROPDOWNBUTTONLEFT = 0x7,
CP_CUEBANNER = 0x8,
};
