enum EXPLORERBARPARTS : __int32
{
EXPLORERBARPartFiller0 = 0x0,
EBP_HEADERBACKGROUND = 0x1,
EBP_HEADERCLOSE = 0x2,
EBP_HEADERPIN = 0x3,
EBP_IEBARMENU = 0x4,
EBP_NORMALGROUPBACKGROUND = 0x5,
EBP_NORMALGROUPCOLLAPSE = 0x6,
EBP_NORMALGROUPEXPAND = 0x7,
EBP_NORMALGROUPHEAD = 0x8,
EBP_SPECIALGROUPBACKGROUND = 0x9,
EBP_SPECIALGROUPCOLLAPSE = 0xA,
EBP_SPECIALGROUPEXPAND = 0xB,
EBP_SPECIALGROUPHEAD = 0xC,
};
