int __usercall ActiveEffect_Base_LoadEffect_::LoadHitEffect_@<eax>(
        int eax0@<eax>,
        _DWORD *ebx0@<ebx>,
        int ebp0@<ebp>,
        int a4,
        int a5,
        int a6,
        int a7,
        int a8,
        int a9,
        int a10,
        int a11,
        int a12,
        int a13,
        int a14,
        int a15,
        int a16,
        int a17,
        int a18)
{
  return ActiveEffect_Base_LoadEffect_::LoadHitEffect(
           ebx0,
           ebp0,
           eax0,
           a4,
           a5,
           a6,
           a7,
           a8,
           a9,
           a10,
           a11,
           a12,
           a13,
           a14,
           a15,
           0xFFFFFFFF,
           a17,
           a18);
}
