enum _D3DKMT_QUERYSTATISTICS_TYPE : __int32
{
D3DKMT_QUERYSTATISTICS_ADAPTER = 0x0,
D3DKMT_QUERYSTATISTICS_PROCESS = 0x1,
D3DKMT_QUERYSTATISTICS_PROCESS_ADAPTER = 0x2,
D3DKMT_QUERYSTATISTICS_SEGMENT = 0x3,
D3DKMT_QUERYSTATISTICS_PROCESS_SEGMENT = 0x4,
D3DKMT_QUERYSTATISTICS_NODE = 0x5,
D3DKMT_QUERYSTATISTICS_PROCESS_NODE = 0x6,
D3DKMT_QUERYSTATISTICS_VIDPNSOURCE = 0x7,
D3DKMT_QUERYSTATISTICS_PROCESS_VIDPNSOURCE = 0x8,
};
