enum TASKBARPARTS : __int32
{
TASKBARPartFiller0 = 0x0,
TBP_BACKGROUNDBOTTOM = 0x1,
TBP_BACKGROUNDRIGHT = 0x2,
TBP_BACKGROUNDTOP = 0x3,
TBP_BACKGROUNDLEFT = 0x4,
TBP_SIZINGBARBOTTOM = 0x5,
TBP_SIZINGBARRIGHT = 0x6,
TBP_SIZINGBARTOP = 0x7,
TBP_SIZINGBARLEFT = 0x8,
};
