enum EDITPARTS_0 : __int32
{
EP_EDITTEXT_0 = 0x1,
EP_CARET_0 = 0x2,
EP_BACKGROUND = 0x3,
EP_PASSWORD = 0x4,
EP_BACKGROUNDWITHBORDER = 0x5,
EP_EDITBORDER_NOSCROLL = 0x6,
EP_EDITBORDER_HSCROLL = 0x7,
EP_EDITBORDER_VSCROLL = 0x8,
EP_EDITBORDER_HVSCROLL = 0x9,
};
