union $B2D9965D7D89CBDF13408723EE5A4B60
{
SERVICE_DESCRIPTIONW *descr __offset(OFF64|AUTO);
SERVICE_FAILURE_ACTIONSW *actions __offset(OFF64|AUTO);
SERVICE_DELAYED_AUTO_START_INFO *delayedstart __offset(OFF64|AUTO);
SERVICE_FAILURE_ACTIONS_FLAG *actionsflag __offset(OFF64|AUTO);
SERVICE_SID_INFO *sid __offset(OFF64|AUTO);
SERVICE_RPC_REQUIRED_PRIVILEGES_INFO *privinfo __offset(OFF64|AUTO);
SERVICE_PRESHUTDOWN_INFO *preshutdown __offset(OFF64|AUTO);
};
