struct IDirectDrawSurface4Vtbl
{
HRESULT (__stdcall *QueryInterface)(IDirectDrawSurface4 *This, const IID *const riid, LPVOID *ppvObj) __offset(OFF64|AUTO);
ULONG (__stdcall *AddRef)(IDirectDrawSurface4 *This) __offset(OFF64|AUTO);
ULONG (__stdcall *Release)(IDirectDrawSurface4 *This) __offset(OFF64|AUTO);
HRESULT (__stdcall *AddAttachedSurface)(IDirectDrawSurface4 *This, LPDIRECTDRAWSURFACE4) __offset(OFF64|AUTO);
HRESULT (__stdcall *AddOverlayDirtyRect)(IDirectDrawSurface4 *This, LPRECT) __offset(OFF64|AUTO);
HRESULT (__stdcall *Blt)(IDirectDrawSurface4 *This, LPRECT, LPDIRECTDRAWSURFACE4, LPRECT, DWORD, LPDDBLTFX) __offset(OFF64|AUTO);
HRESULT (__stdcall *BltBatch)(IDirectDrawSurface4 *This, LPDDBLTBATCH, DWORD, DWORD) __offset(OFF64|AUTO);
HRESULT (__stdcall *BltFast)(IDirectDrawSurface4 *This, DWORD, DWORD, LPDIRECTDRAWSURFACE4, LPRECT, DWORD) __offset(OFF64|AUTO);
HRESULT (__stdcall *DeleteAttachedSurface)(IDirectDrawSurface4 *This, DWORD, LPDIRECTDRAWSURFACE4) __offset(OFF64|AUTO);
HRESULT (__stdcall *EnumAttachedSurfaces)(IDirectDrawSurface4 *This, LPVOID, LPDDENUMSURFACESCALLBACK2) __offset(OFF64|AUTO);
HRESULT (__stdcall *EnumOverlayZOrders)(IDirectDrawSurface4 *This, DWORD, LPVOID, LPDDENUMSURFACESCALLBACK2) __offset(OFF64|AUTO);
HRESULT (__stdcall *Flip)(IDirectDrawSurface4 *This, LPDIRECTDRAWSURFACE4, DWORD) __offset(OFF64|AUTO);
HRESULT (__stdcall *GetAttachedSurface)(IDirectDrawSurface4 *This, LPDDSCAPS2, LPDIRECTDRAWSURFACE4 *) __offset(OFF64|AUTO);
HRESULT (__stdcall *GetBltStatus)(IDirectDrawSurface4 *This, DWORD) __offset(OFF64|AUTO);
HRESULT (__stdcall *GetCaps)(IDirectDrawSurface4 *This, LPDDSCAPS2) __offset(OFF64|AUTO);
HRESULT (__stdcall *GetClipper)(IDirectDrawSurface4 *This, LPDIRECTDRAWCLIPPER *) __offset(OFF64|AUTO);
HRESULT (__stdcall *GetColorKey)(IDirectDrawSurface4 *This, DWORD, LPDDCOLORKEY) __offset(OFF64|AUTO);
HRESULT (__stdcall *GetDC)(IDirectDrawSurface4 *This, HDC *) __offset(OFF64|AUTO);
HRESULT (__stdcall *GetFlipStatus)(IDirectDrawSurface4 *This, DWORD) __offset(OFF64|AUTO);
HRESULT (__stdcall *GetOverlayPosition)(IDirectDrawSurface4 *This, LPLONG, LPLONG) __offset(OFF64|AUTO);
HRESULT (__stdcall *GetPalette)(IDirectDrawSurface4 *This, LPDIRECTDRAWPALETTE *) __offset(OFF64|AUTO);
HRESULT (__stdcall *GetPixelFormat)(IDirectDrawSurface4 *This, LPDDPIXELFORMAT) __offset(OFF64|AUTO);
HRESULT (__stdcall *GetSurfaceDesc)(IDirectDrawSurface4 *This, LPDDSURFACEDESC2) __offset(OFF64|AUTO);
HRESULT (__stdcall *Initialize)(IDirectDrawSurface4 *This, LPDIRECTDRAW, LPDDSURFACEDESC2) __offset(OFF64|AUTO);
HRESULT (__stdcall *IsLost)(IDirectDrawSurface4 *This) __offset(OFF64|AUTO);
HRESULT (__stdcall *Lock)(IDirectDrawSurface4 *This, LPRECT, LPDDSURFACEDESC2, DWORD, HANDLE) __offset(OFF64|AUTO);
HRESULT (__stdcall *ReleaseDC)(IDirectDrawSurface4 *This, HDC) __offset(OFF64|AUTO);
HRESULT (__stdcall *Restore)(IDirectDrawSurface4 *This) __offset(OFF64|AUTO);
HRESULT (__stdcall *SetClipper)(IDirectDrawSurface4 *This, LPDIRECTDRAWCLIPPER) __offset(OFF64|AUTO);
HRESULT (__stdcall *SetColorKey)(IDirectDrawSurface4 *This, DWORD, LPDDCOLORKEY) __offset(OFF64|AUTO);
HRESULT (__stdcall *SetOverlayPosition)(IDirectDrawSurface4 *This, LONG, LONG) __offset(OFF64|AUTO);
HRESULT (__stdcall *SetPalette)(IDirectDrawSurface4 *This, LPDIRECTDRAWPALETTE) __offset(OFF64|AUTO);
HRESULT (__stdcall *Unlock)(IDirectDrawSurface4 *This, LPRECT) __offset(OFF64|AUTO);
HRESULT (__stdcall *UpdateOverlay)(IDirectDrawSurface4 *This, LPRECT, LPDIRECTDRAWSURFACE4, LPRECT, DWORD, LPDDOVERLAYFX) __offset(OFF64|AUTO);
HRESULT (__stdcall *UpdateOverlayDisplay)(IDirectDrawSurface4 *This, DWORD) __offset(OFF64|AUTO);
HRESULT (__stdcall *UpdateOverlayZOrder)(IDirectDrawSurface4 *This, DWORD, LPDIRECTDRAWSURFACE4) __offset(OFF64|AUTO);
HRESULT (__stdcall *GetDDInterface)(IDirectDrawSurface4 *This, LPVOID *) __offset(OFF64|AUTO);
HRESULT (__stdcall *PageLock)(IDirectDrawSurface4 *This, DWORD) __offset(OFF64|AUTO);
HRESULT (__stdcall *PageUnlock)(IDirectDrawSurface4 *This, DWORD) __offset(OFF64|AUTO);
HRESULT (__stdcall *SetSurfaceDesc)(IDirectDrawSurface4 *This, LPDDSURFACEDESC2, DWORD) __offset(OFF64|AUTO);
HRESULT (__stdcall *SetPrivateData)(IDirectDrawSurface4 *This, const GUID *const, LPVOID, DWORD, DWORD) __offset(OFF64|AUTO);
HRESULT (__stdcall *GetPrivateData)(IDirectDrawSurface4 *This, const GUID *const, LPVOID, LPDWORD) __offset(OFF64|AUTO);
HRESULT (__stdcall *FreePrivateData)(IDirectDrawSurface4 *This, const GUID *const) __offset(OFF64|AUTO);
HRESULT (__stdcall *GetUniquenessValue)(IDirectDrawSurface4 *This, LPDWORD) __offset(OFF64|AUTO);
HRESULT (__stdcall *ChangeUniquenessValue)(IDirectDrawSurface4 *This) __offset(OFF64|AUTO);
};
