struct tagUSER_DRIVER
{
BOOL (*pActivateKeyboardLayout)(HKL, UINT);
void (*pBeep)(void);
INT (*pGetKeyNameText)(LONG, LPWSTR, INT);
UINT (*pGetKeyboardLayoutList)(INT, HKL *);
UINT (*pMapVirtualKeyEx)(UINT, UINT, HKL);
BOOL (*pRegisterHotKey)(HWND, UINT, UINT);
INT (*pToUnicodeEx)(UINT, UINT, const BYTE *, LPWSTR, int, UINT, HKL);
void (*pUnregisterHotKey)(HWND, UINT, UINT);
SHORT (*pVkKeyScanEx)(WCHAR_0, HKL);
void (*pDestroyCursorIcon)(HCURSOR);
void (*pSetCursor)(HCURSOR);
BOOL (*pGetCursorPos)(LPPOINT);
BOOL (*pSetCursorPos)(INT, INT);
BOOL (*pClipCursor)(LPCRECT);
void (*pUpdateClipboard)(void);
LONG (*pChangeDisplaySettingsEx)(LPCWSTR, LPDEVMODEW_0, HWND, DWORD, LPVOID);
BOOL (*pEnumDisplayMonitors)(HDC, LPRECT, MONITORENUMPROC, LPARAM_0);
BOOL (*pEnumDisplaySettingsEx)(LPCWSTR, DWORD, LPDEVMODEW_0, DWORD);
BOOL (*pGetMonitorInfo)(HMONITOR, MONITORINFO *);
BOOL (*pCreateDesktopWindow)(HWND);
BOOL (*pCreateWindow)(HWND);
void (*pDestroyWindow)(HWND);
void (*pFlashWindowEx)(FLASHWINFO *);
void (*pGetDC)(HDC, HWND, HWND, const RECT *, const RECT *, DWORD);
DWORD (*pMsgWaitForMultipleObjectsEx)(DWORD, const HANDLE *, DWORD, DWORD, DWORD);
void (*pReleaseDC)(HWND, HDC);
BOOL (*pScrollDC)(HDC, INT, INT, HRGN);
void (*pSetActiveWindow)(HWND);
void (*pSetCapture)(HWND, UINT);
void (*pSetFocus)(HWND);
void (*pSetLayeredWindowAttributes)(HWND, COLORREF, BYTE, DWORD);
void (*pSetParent)(HWND, HWND, HWND);
void (*pSetWindowRgn)(HWND, HRGN, BOOL);
void (*pSetWindowIcon)(HWND, UINT, HICON);
void (*pSetWindowStyle)(HWND, INT, STYLESTRUCT *);
void (*pSetWindowText)(HWND, LPCWSTR);
UINT (*pShowWindow)(HWND, INT, RECT *, UINT);
LRESULT_0 (*pSysCommand)(HWND, WPARAM_0, LPARAM_0);
BOOL (*pUpdateLayeredWindow)(HWND, const UPDATELAYEREDWINDOWINFO *, const RECT *);
LRESULT_0 (*pWindowMessage)(HWND, UINT, WPARAM_0, LPARAM_0);
BOOL (*pWindowPosChanging)(HWND, HWND, UINT, const RECT *, const RECT *, RECT *, window_surface **);
void (*pWindowPosChanged)(HWND, HWND, UINT, const RECT *, const RECT *, const RECT *, const RECT *, window_surface *);
BOOL (*pSystemParametersInfo)(UINT, UINT, void *, UINT);
void (*pUpdateCandidatePos)(HWND, const RECT *);
void (*pThreadDetach)(void);
};
