int __usercall MagicCaster_ApplyActiveMagicItem_::EffectLoop_Next@<eax>(
        int a1@<edi>,
        int a2@<esi>,
        TESObjectREFR *ebx0@<ebx>,
        int a4,
        int a5,
        int a6,
        int a7,
        int a8,
        int a9,
        int a10,
        int a11,
        int a12,
        int a13,
        int a14,
        int a15,
        int a16,
        int a17,
        int a18,
        __int64 a19,
        int a20,
        int a21,
        int a22,
        int a23,
        int a24,
        int a25,
        int a26,
        int a27,
        int a28,
        int a29,
        int a30,
        int a31,
        int a32,
        int a33,
        int a34)
{
  int v34; // eax
  int v35; // eax

  v34 = (*(int (__thiscall **)(int))(*(_DWORD *)a2 + 0x30))(a2);
  if ( (*(int (__thiscall **)(int))(*(_DWORD *)v34 + 0x18))(v34) == 8 )
    return MagicCaster_ApplyActiveMagicItem_::GetVFXInfo(
             a2,
             ebx0,
             a4,
             a5,
             a6,
             a7,
             a8,
             a9,
             a10,
             a11,
             a12,
             a13,
             a14,
             a15,
             a16,
             a17,
             a18,
             a19,
             a20,
             a21,
             a22,
             a23,
             a24,
             a25,
             a26,
             a27,
             a28,
             a29,
             a30,
             a31,
             a32,
             a33,
             a34);
  v35 = *(_DWORD *)(a1 + 8);
  if ( !v35 )
    return MagicCaster_ApplyActiveMagicItem_::GetVFXInfo(
             a2,
             ebx0,
             a4,
             a5,
             a6,
             a7,
             a8,
             a9,
             a10,
             a11,
             a12,
             a13,
             a14,
             a15,
             a16,
             a17,
             a18,
             a19,
             a20,
             a21,
             a22,
             a23,
             a24,
             a25,
             a26,
             a27,
             a28,
             a29,
             a30,
             a31,
             a32,
             a33,
             a34);
  a16 = v35 - 4;
  if ( v35 == 4 )
    return MagicCaster_ApplyActiveMagicItem_::GetVFXInfo(
             a2,
             ebx0,
             a4,
             a5,
             a6,
             a7,
             a8,
             a9,
             a10,
             a11,
             a12,
             a13,
             a14,
             a15,
             a16,
             a17,
             a18,
             a19,
             a20,
             a21,
             a22,
             a23,
             a24,
             a25,
             a26,
             a27,
             a28,
             a29,
             a30,
             a31,
             a32,
             a33,
             a34);
  else
    return MagicCaster_ApplyActiveMagicItem_::EffectLoop_Body(
             v35 - 4,
             a2,
             ebx0,
             a4,
             a5,
             a6,
             a7,
             a8,
             a9,
             a10,
             a11,
             a12,
             a13,
             a14,
             a15,
             a16,
             a17,
             a18,
             a19,
             a20,
             a21,
             a22,
             a23,
             a24,
             a25,
             a26,
             a27,
             a28,
             a29,
             a30,
             a31,
             a32,
             a33,
             a34);
}
