int __usercall Actor_AttackHandling_::ApplySneakAttackBonus@<eax>(
        int *a1@<edi>,
        char bl0@<bl>,
        int esi0@<esi>,
        int a4,
        int a5,
        int a6,
        int a7,
        int a8,
        float a9,
        int a10,
        int a11,
        int a12,
        int a13,
        int a14,
        int a15,
        int a16,
        int a17,
        float a18,
        int a19,
        int a20,
        int a21,
        int a22,
        int a23,
        int a24,
        int a25,
        int a26,
        int a27)
{
  float v28; // [esp+18h] [ebp+18h]
  int v29; // [esp+3Ch] [ebp+3Ch]

  v28 = a9 * *(float *)&a17;
  *(float *)&v29 = *(float *)&a17 * a18;
  return Actor_AttackHandling_::__(
           *(int (**)(void))(*a1 + 0x214),
           *a1,
           (int)a1,
           bl0,
           esi0,
           a4,
           a5,
           a6,
           a7,
           a8,
           v28,
           a10,
           a11,
           a12,
           a13,
           a14,
           a15,
           a16,
           a17,
           v29,
           a19,
           a20,
           a21,
           a22,
           a23,
           a24,
           a25,
           a26,
           a27);
}
