enum gsub_lookup_type : __int32
{
GSUB_LOOKUP_SINGLE = 0x1,
GSUB_LOOKUP_MULTIPLE = 0x2,
GSUB_LOOKUP_ALTERNATE = 0x3,
GSUB_LOOKUP_LIGATURE = 0x4,
GSUB_LOOKUP_CONTEXT = 0x5,
GSUB_LOOKUP_CONTEXT_CHAINED = 0x6,
GSUB_LOOKUP_EXTENSION = 0x7,
GSUB_LOOKUP_CONTEXT_CHAINED_REVERSE = 0x8,
};
