0xA26DF0: mov     ecx, offset list
0xA26DF5: mov     list, offset ??_7?$NiTPointerListBase@V?$NiTPointerAllocator@I@@PAVNiDX9AdditionalDepthStencilBufferData@@@@6B@; const NiTPointerListBase<NiTPointerAllocator<uint>,NiDX9AdditionalDepthStencilBufferData *>::`vftable' ...
0xA26DFF: call    NiTPointerList__FreeAllNodes; Free every active NiTPointerList node through the list's FreeNode virtual and clear head/tail/count. The generic list helper does not destroy payload objects; owner code must do that separately when required.
0xA26E04: mov     list, offset ??_7?$NiTListBase@V?$NiTPointerAllocator@I@@PAVNiDX9AdditionalDepthStencilBufferData@@@@6B@; const NiTListBase<NiTPointerAllocator<uint>,NiDX9AdditionalDepthStencilBufferData *>::`vftable' ...
0xA26E0E: retn
