0xA26DF0: mov     ecx, offset off_B294F0
0xA26DF5: mov     off_B294F0, offset ??_7?$NiTPointerListBase@V?$NiTPointerAllocator@I@@PAVNiDX9AdditionalDepthStencilBufferData@@@@6B@; const NiTPointerListBase<NiTPointerAllocator<uint>,NiDX9AdditionalDepthStencilBufferData *>::`vftable' ...
0xA26DFF: call    NiTPointerList__FreeAllNodes
0xA26E04: mov     off_B294F0, offset ??_7?$NiTListBase@V?$NiTPointerAllocator@I@@PAVNiDX9AdditionalDepthStencilBufferData@@@@6B@; const NiTListBase<NiTPointerAllocator<uint>,NiDX9AdditionalDepthStencilBufferData *>::`vftable' ...
0xA26E0E: retn
