struct tagPROVFUNCS
{
BOOL (*pCPAcquireContext)(HCRYPTPROV *, LPSTR, DWORD, PVTableProvStruc);
BOOL (*pCPCreateHash)(HCRYPTPROV, ALG_ID, HCRYPTKEY, DWORD, HCRYPTHASH *);
BOOL (*pCPDecrypt)(HCRYPTPROV, HCRYPTKEY, HCRYPTHASH, BOOL, DWORD, BYTE *, DWORD *);
BOOL (*pCPDeriveKey)(HCRYPTPROV, ALG_ID, HCRYPTHASH, DWORD, HCRYPTKEY *);
BOOL (*pCPDestroyHash)(HCRYPTPROV, HCRYPTHASH);
BOOL (*pCPDestroyKey)(HCRYPTPROV, HCRYPTKEY);
BOOL (*pCPDuplicateHash)(HCRYPTPROV, HCRYPTHASH, DWORD *, DWORD, HCRYPTHASH *);
BOOL (*pCPDuplicateKey)(HCRYPTPROV, HCRYPTKEY, DWORD *, DWORD, HCRYPTKEY *);
BOOL (*pCPEncrypt)(HCRYPTPROV, HCRYPTKEY, HCRYPTHASH, BOOL, DWORD, BYTE *, DWORD *, DWORD);
BOOL (*pCPExportKey)(HCRYPTPROV, HCRYPTKEY, HCRYPTKEY, DWORD, DWORD, BYTE *, DWORD *);
BOOL (*pCPGenKey)(HCRYPTPROV, ALG_ID, DWORD, HCRYPTKEY *);
BOOL (*pCPGenRandom)(HCRYPTPROV, DWORD, BYTE *);
BOOL (*pCPGetHashParam)(HCRYPTPROV, HCRYPTHASH, DWORD, BYTE *, DWORD *, DWORD);
BOOL (*pCPGetKeyParam)(HCRYPTPROV, HCRYPTKEY, DWORD, BYTE *, DWORD *, DWORD);
BOOL (*pCPGetProvParam)(HCRYPTPROV, DWORD, BYTE *, DWORD *, DWORD);
BOOL (*pCPGetUserKey)(HCRYPTPROV, DWORD, HCRYPTKEY *);
BOOL (*pCPHashData)(HCRYPTPROV, HCRYPTHASH, const BYTE *, DWORD, DWORD);
BOOL (*pCPHashSessionKey)(HCRYPTPROV, HCRYPTHASH, HCRYPTKEY, DWORD);
BOOL (*pCPImportKey)(HCRYPTPROV, const BYTE *, DWORD, HCRYPTKEY, DWORD, HCRYPTKEY *);
BOOL (*pCPReleaseContext)(HCRYPTPROV, DWORD);
BOOL (*pCPSetHashParam)(HCRYPTPROV, HCRYPTHASH, DWORD, const BYTE *, DWORD);
BOOL (*pCPSetKeyParam)(HCRYPTPROV, HCRYPTKEY, DWORD, const BYTE *, DWORD);
BOOL (*pCPSetProvParam)(HCRYPTPROV, DWORD, const BYTE *, DWORD);
BOOL (*pCPSignHash)(HCRYPTPROV, HCRYPTHASH, DWORD, LPCWSTR, DWORD, BYTE *, DWORD *);
BOOL (*pCPVerifySignature)(HCRYPTPROV, HCRYPTHASH, const BYTE *, DWORD, HCRYPTKEY, LPCWSTR, DWORD);
};
