enum D3DSWAPEFFECT : __int32
{
D3DSWAPEFFECT_DISCARD = 0x1,
D3DSWAPEFFECT_FLIP = 0x2,
D3DSWAPEFFECT_COPY = 0x3,
D3DSWAPEFFECT_OVERLAY = 0x4,
D3DSWAPEFFECT_FLIPEX = 0x5,
D3DSWAPEFFECT_FORCE_DWORD = 0x7FFFFFFF,
};
