enum SkillActorValue
{
kSkillAV_Armorer = 0xC,
kSkillAV_Athletics = 0xD,
kSkillAV_Blade = 0xE,
kSkillAV_Block = 0xF,
kSkillAV_Blunt = 0x10,
kSkillAV_HandToHand = 0x11,
kSkillAV_HeavyArmor = 0x12,
kSkillAV_Alchemy = 0x13,
kSkillAV_Alteration = 0x14,
kSkillAV_Conjuration = 0x15,
kSkillAV_Destruction = 0x16,
kSkillAV_Illusion = 0x17,
kSkillAV_Mysticism = 0x18,
kSkillAV_Restoration = 0x19,
kSkillAV_Acrobatics = 0x1A,
kSkillAV_LightArmor = 0x1B,
kSkillAV_Marksman = 0x1C,
kSkillAV_Mercantile = 0x1D,
kSkillAV_Security = 0x1E,
kSkillAV_Sneak = 0x1F,
kSkillAV_Speechcraft = 0x20,
};
