struct __declspec(align(4)) NiRendererVtbl
{
_BYTE gap0[76];
bool (__thiscall *Unk_13)(NiRenderer *this, UInt32 arg);
const char *(__thiscall *GetRendererDesc)(NiRenderer *this);
UInt32 (__thiscall *GetFlags)(NiRenderer *this);
void (__thiscall *SetClearDepth)(NiRenderer *this, float arg);
float (__thiscall *GetClearDepth)(NiRenderer *this);
void (__thiscall *SetClearColor4)(NiRenderer *this, NiRenderer *this, float *src);
void (__thiscall *SetClearColor3)(NiRenderer *this, NiRenderer *this, float *src);
void (__thiscall *GetClearColor)(NiRenderer *this, NiRenderer *this, float *dst);
void (__thiscall *SetClearStencil)(NiRenderer *this, UInt32 src);
UInt32 (__thiscall *GetClearStencil)(NiRenderer *this);
bool (__thiscall *ValidateRenderTargetGroup)(NiRenderer *this, NiRenderTargetGroup *renderTarget);
void (__thiscall *IsDepthBufferCompatible)(NiRenderer *this, Ni2DBuffer *buffer, NiDepthStencilBuffer *dsBuffer);
NiRenderTargetGroup *(__thiscall *GetDefaultRTGroup)(NiRenderer *this);
NiRenderTargetGroup *(__thiscall *GetCurrentRTGroup)(NiRenderer *this);
UInt8 (__thiscall *Unk_21)(NiRenderer *this);
void (__thiscall *Unk_22)(NiRenderer *this);
void (__thiscall *Unk_23)(NiRenderer *this);
void (__thiscall *Unk_24)(NiRenderer *this, UInt32 arg);
void *(__thiscall *Unk_25)(NiRenderer *this, void *arg0, UInt32 arg1, UInt32 arg2);
void *(__thiscall *Unk_26)(NiRenderer *this, void *arg);
UInt32 (__thiscall *Unk_27)(NiRenderer *this);
UInt32 (__thiscall *Unk_28)(NiRenderer *this);
void (__thiscall *Unk_29)(NiRenderer *this);
bool (__thiscall *SetMipmapSkipLevel)(NiRenderer *this, UInt32 arg);
UInt32 (__thiscall *GetMipmapSkipLevel)(NiRenderer *this);
bool (__thiscall *NiRenderer::PrecacheGeometryData)(NiRenderer *this, UInt32 arg0, UInt32 arg1, UInt32 arg2, UInt32 arg3);
void (__thiscall *PurgeGeometryData)(NiRenderer *this, NiGeometryData *geo);
void (__thiscall *PurgeMaterial)(NiRenderer *this, NiMaterialProperty *material);
void (__thiscall *PurgeEffect)(NiRenderer *this, NiDynamicEffect *effect);
void (__thiscall *PurgeScreenTexture)(NiRenderer *this);
void (__thiscall *PurgeSkinPartition)(NiRenderer *this, NiSkinPartition *skinPartition);
void (__thiscall *PurgeSkinInstance)(NiRenderer *this, NiSkinInstance *skinInstance);
void (__thiscall *Unk_33)(NiRenderer *this, void *unk);
bool (__thiscall *Unk_34)(NiRenderer *this);
void (__thiscall *Unk_35)(NiRenderer *this);
bool (__thiscall *FastCopy)(NiRenderer *this, void *src, void *dst, RECT *srcRect, SInt32 xOffset, SInt32 yOffset);
bool (__thiscall *Copy)(NiRenderer *this, void *src, void *dst, RECT *srcRect, RECT *dstRect, UInt32 filterMode);
void (__thiscall *Unk_38)(NiRenderer *this);
bool (__thiscall *Unk_39)(NiRenderer *this, void *arg);
void (__thiscall *Unk_3A)(NiRenderer *this);
void (__thiscall *Unk_3B)(NiRenderer *this, float arg);
void *(__thiscall *Unk_3C)(NiRenderer *this, UInt32 size);
void (__thiscall *Unk_3D)(NiRenderer *this, UInt32 arg0, UInt32 arg1);
void (__thiscall *Unk_3E)(NiRenderer *this, UInt32 arg0, UInt32 arg1);
void (__thiscall *Unk_3F)(NiRenderer *this, void *buf);
bool (__thiscall *Unk_40)(NiRenderer *this, UInt32 arg0);
void (__thiscall *CreateSourceTexture)(NiRenderer *this, NiSourceTexture *texture);
bool (__thiscall *CreateRenderedTexture)(NiRenderer *this, NiRenderedTexture *arg);
bool (__thiscall *CreateSourceCubeMap)(NiRenderer *this, NiSourceCubeMap *arg);
bool (__thiscall *CreateRenderedCubeMap)(NiRenderer *this, NiRenderedCubeMap *arg);
bool (__thiscall *CreateDynamicTexture)(NiRenderer *this, void *arg);
void (__thiscall *CreatePalette)(NiRenderer *this, void *arg);
bool (__thiscall *CreateDepthStencil)(NiRenderer *this, NiDepthStencilBuffer *arg, void *textureFormat);
void (__thiscall *LockDynamicTexture)(NiRenderer *this, void *arg0, void *arg1);
void (__thiscall *UnLockDynamicTexture)(NiRenderer *this, void *arg);
void (__thiscall *LockRenderer)(NiRenderer *this);
void (__thiscall *UnlockRenderer)(NiRenderer *this);
bool (__thiscall *BeginScene)(NiRenderer *this);
bool (__thiscall *EndScene)(NiRenderer *this);
void (__thiscall *DisplayScene)(NiRenderer *this);
void (__thiscall *Clear)(NiRenderer *this, float *rect, UInt32 flags);
void (__thiscall *SetupCamera)(NiRenderer *this, NiPoint3 *pos, NiPoint3 *at, NiPoint3 *up, NiPoint3 *right, NiFrustum *frustum, float *viewport);
void (__thiscall *SetupScreenSpaceCamera)(NiRenderer *this, NiViewport *viewport);
bool (__thiscall *BeginUsingRenderTargetGroup)(NiRenderer *this, NiRenderTargetGroup *renderTarget, ClearFlags clearFlags);
bool (__thiscall *EndUsingRenderTargetGroup)(NiRenderer *this);
void (__thiscall *BeginBatch)(NiRenderer *this, UInt32 arg0, UInt32 arg1);
void (__thiscall *EndBatch)(NiRenderer *this);
void (__thiscall *BatchRenderShape)(NiRenderer *this, void *arg);
void (__thiscall *BatchRenderStrips)(NiRenderer *this, void *arg);
void (__thiscall *RenderTriShape)(NiRenderer *this, NiTriShape *obj);
void (__thiscall *RenderTriStrips)(NiRenderer *this, NiTriStrips *obj);
void (__thiscall *RenderTriShape2)(NiRenderer *this, NiTriShape *obj);
void (__thiscall *RenderTriStrips2)(NiRenderer *this, NiTriStrips *obj);
void (__thiscall *RenderParticles)(NiRenderer *this, NiParticles *obj);
void (__thiscall *RenderLines)(NiRenderer *this, NiLines *obj);
void (__thiscall *RenderScreenTexture)(NiRenderer *this);
};
