int __usercall MagicCaster_ApplyActiveMagicItem_::GetVFXInfo@<eax>(
        char *a1@<esi>,
        TESObjectREFR *ebx0@<ebx>,
        int a3,
        int a4,
        int a5,
        int a6,
        int a7,
        TESObjectREFR *a8,
        int a9,
        int a10,
        int a11,
        int a12,
        int a13,
        int a14,
        int a15,
        int a16,
        int a17,
        double a18,
        float a19,
        int a20,
        float a21,
        float a22,
        float a23,
        int a24,
        int a25,
        int a26,
        int a27,
        int a28,
        int a29,
        int a30,
        int a31,
        int a32,
        int a33)
{
  _DWORD *v33; // eax
  int StrongestItem; // eax
  int FXEffect; // [esp+74h] [ebp+74h]

  v33 = (_DWORD *)(*(int (__thiscall **)(char *))(*(_DWORD *)a1 + 0x30))(a1);
  FXEffect = MagicItem_GetFXEffect(v33, 0);
  (*(void (__thiscall **)(char *))(*(_DWORD *)a1 + 0x30))(a1);
  StrongestItem = EffectItemList_GetStrongestItem(1, 1);
  return MagicCaster_ApplyActiveMagicItem_::GetVFXInfo_Target(
           ebx0,
           a1,
           a3,
           a4,
           a5,
           a6,
           a7,
           a8,
           a9,
           a10,
           a11,
           a12,
           a13,
           a14,
           a15,
           a16,
           a17,
           a18,
           a19,
           a20,
           a21,
           a22,
           a23,
           a24,
           a25,
           a26,
           a27,
           a28,
           a29,
           FXEffect,
           a31,
           StrongestItem,
           a33);
}
