enum ACTCTX_COMPATIBILITY_ELEMENT_TYPE : __int32
{
ACTCTX_COMPATIBILITY_ELEMENT_TYPE_UNKNOWN = 0x0,
ACTCTX_COMPATIBILITY_ELEMENT_TYPE_OS = 0x1,
ACTCTX_COMPATIBILITY_ELEMENT_TYPE_MITIGATION = 0x2,
ACTCTX_COMPATIBILITY_ELEMENT_TYPE_MAXVERSIONTESTED = 0x3,
};
