enum parameter_key : __int32
{
COLORS_KEY = 0x0,
DESKTOP_KEY = 0x1,
KEYBOARD_KEY = 0x2,
MOUSE_KEY = 0x3,
METRICS_KEY = 0x4,
SOUND_KEY = 0x5,
VERSION_KEY = 0x6,
SHOWSOUNDS_KEY = 0x7,
KEYBOARDPREF_KEY = 0x8,
SCREENREADER_KEY = 0x9,
AUDIODESC_KEY = 0xA,
NB_PARAM_KEYS = 0xB,
};
