struct __declspec(align(8)) _DSPROPERTY_DIRECTSOUNDDEVICE_DESCRIPTION_A_DATA
{
DIRECTSOUNDDEVICE_TYPE Type;
DIRECTSOUNDDEVICE_DATAFLOW DataFlow;
GUID DeviceId;
LPSTR Description;
LPSTR Module;
LPSTR Interface;
ULONG WaveDeviceId;
};
