enum TABPARTS : __int32
{
TABP_TABITEM = 0x1,
TABP_TABITEMLEFTEDGE = 0x2,
TABP_TABITEMRIGHTEDGE = 0x3,
TABP_TABITEMBOTHEDGE = 0x4,
TABP_TOPTABITEM = 0x5,
TABP_TOPTABITEMLEFTEDGE = 0x6,
TABP_TOPTABITEMRIGHTEDGE = 0x7,
TABP_TOPTABITEMBOTHEDGE = 0x8,
TABP_PANE = 0x9,
TABP_BODY = 0xA,
TABP_AEROWIZARDBODY = 0xB,
};
