enum HEADERPARTS_0 : __int32
{
HP_HEADERITEM_0 = 0x1,
HP_HEADERITEMLEFT_0 = 0x2,
HP_HEADERITEMRIGHT_0 = 0x3,
HP_HEADERSORTARROW_0 = 0x4,
HP_HEADERDROPDOWN = 0x5,
HP_HEADERDROPDOWNFILTER = 0x6,
HP_HEADEROVERFLOW = 0x7,
};
