enum _TP_CALLBACK_PRIORITY : __int32
{
TP_CALLBACK_PRIORITY_HIGH = 0x0,
TP_CALLBACK_PRIORITY_NORMAL = 0x1,
TP_CALLBACK_PRIORITY_LOW = 0x2,
TP_CALLBACK_PRIORITY_INVALID = 0x3,
TP_CALLBACK_PRIORITY_COUNT = 0x3,
};
