struct _SYSTEM_TIMEOFDAY_INFORMATION
{
LARGE_INTEGER_0 BootTime;
LARGE_INTEGER_0 SystemTime;
LARGE_INTEGER_0 TimeZoneBias;
ULONG TimeZoneId;
ULONG Reserved;
ULONGLONG BootTimeBias;
ULONGLONG SleepTimeBias;
};
