// local variable allocation has failed, the output may be wrong!
int __usercall Magic_ShowDebugText_::Check_MagicTarget@<eax>(
        signed int a1@<ebx>,
        char a2@<bpl>,
        _DWORD *a3@<edi>,
        int a4@<esi>,
        double a5@<st2>,
        double a6@<st1>,
        double a7@<st0>,
        int a8,
        int a9,
        int a10,
        int a11,
        int a12,
        int a13,
        void *a14,
        int a15,
        int a16,
        int a17,
        int *a18,
        int *a19,
        int a20,
        int a21,
        int a22,
        int a23,
        int a24,
        void *a25,
        int a26,
        int a27,
        int a28,
        int a29,
        int a30,
        int a31,
        int a32,
        int a33,
        int a34,
        int a35,
        int a36,
        int a37,
        int a38,
        int a39,
        int a40,
        int a41,
        int a42,
        int a43,
        int a44,
        int a45,
        int a46,
        int a47)
{
  void *v47; // eax

  v47 = OblivionDynamicCast( /*0x41cea6*/
          a3,
          0,
          (struct _s_RTTICompleteObjectLocator *)&TESObjectREFR `RTTI Type Descriptor',
          &MagicTarget `RTTI Type Descriptor',
          0);
  if ( !v47 || (a3[2] & 0x800) != 0 ) /*0x41cebf*/
    return Magic_ShowDebugText_::NotMagicTarget( /*0x41ceb0*/
             a2,
             a6,
             a7,
             a8,
             a9,
             a10,
             a11,
             a12,
             a1,
             (int)a14,
             a15,
             a16,
             a17,
             (int)a18,
             (int)a19,
             a20,
             a21,
             a22,
             a23,
             a24,
             (int)a25);
  else
    return Magic_ShowDebugText_::MagicTarget( /*0x41cec0*/
             (int)v47,
             a1,
             a2,
             a4,
             a5,
             a6,
             a7,
             a8,
             a9,
             a10,
             a11,
             a12,
             a1,
             a14,
             a15,
             a16,
             a17,
             a18,
             a19,
             *(float *)&a20,
             *(__int128 *)&a21,
             a25,
             a26,
             a27,
             a28,
             a29,
             a30,
             a31,
             a32,
             a33,
             a34,
             a35,
             a36,
             a37,
             a38,
             a39,
             a40,
             a41,
             a42,
             a43,
             a44,
             a45,
             a46,
             a47);
}
