int __usercall Magic_ShowDebugText_::Check_MagicTarget@<eax>(
        signed int a1@<ebx>,
        char a2@<bpl>,
        _DWORD *a3@<edi>,
        int a4@<esi>,
        double a5@<st2>,
        double a6@<st1>,
        int a7,
        int a8,
        int a9,
        int a10,
        int a11,
        int a12,
        void *a13,
        int a14,
        int a15,
        int a16,
        int *a17,
        int a18,
        int a19,
        int a20,
        int a21,
        int a22,
        int a23,
        void *a24,
        int a25,
        int a26,
        int a27,
        int a28,
        int a29,
        int a30,
        int a31,
        int a32,
        int a33,
        int a34,
        int a35,
        int a36,
        int a37,
        int a38,
        int a39,
        int a40,
        int a41,
        int a42,
        int a43,
        int a44,
        int a45,
        int a46,
        int a47,
        int a48,
        int a49,
        int a50,
        int a51,
        int a52,
        int a53,
        int a54,
        int a55,
        int a56,
        int a57,
        int a58,
        int a59,
        int a60,
        int a61,
        int a62,
        int a63)
{
  int a64; // [esp+E8h] [ebp+E8h]
  int a65; // [esp+ECh] [ebp+ECh]
  int a66; // [esp+F0h] [ebp+F0h]
  void *v66; // eax

  v66 = OblivionDynamicCast(
          a3,
          0,
          (struct _s_RTTICompleteObjectLocator *)&TESObjectREFR `RTTI Type Descriptor',
          &MagicTarget `RTTI Type Descriptor',
          0);
  if ( !v66 || (a3[2] & 0x800) != 0 )
    return Magic_ShowDebugText_::NotMagicTarget(
             a2,
             a5,
             a6,
             a7,
             a8,
             a9,
             a10,
             a11,
             a1,
             (int)a13,
             a14,
             a15,
             a16,
             (int)a17,
             a18,
             a19,
             a20,
             a21,
             a22,
             a23,
             (int)a24,
             a25,
             a26,
             a27,
             a28,
             a29,
             a30,
             a31,
             a32,
             a33,
             a34,
             a35,
             a36,
             a37,
             a38,
             a39,
             a40,
             a41,
             a42,
             a43,
             a44,
             a45,
             a46,
             a47,
             a48,
             a49,
             a50,
             a51,
             a52,
             a53,
             a54,
             a55,
             a56,
             a57,
             a58,
             a59,
             a60,
             a61,
             a62,
             a63,
             a64,
             a65,
             a66);
  else
    return Magic_ShowDebugText_::MagicTarget(
             (int)v66,
             a1,
             a2,
             a4,
             a5,
             a6,
             a7,
             a8,
             a9,
             a10,
             a11,
             a1,
             a13,
             a14,
             a15,
             a16,
             a17,
             a18,
             *(float *)&a19,
             a20,
             a21,
             a22,
             a23,
             a24,
             a25,
             a26,
             a27,
             a28,
             a29,
             a30,
             a31,
             a32,
             a33,
             a34,
             a35,
             a36,
             a37,
             a38,
             a39,
             a40,
             a41,
             a42,
             a43,
             a44,
             a45,
             a46,
             a47,
             a48,
             a49,
             a50,
             a51,
             a52,
             a53,
             a54,
             a55,
             a56,
             a57,
             a58,
             a59,
             a60,
             a61,
             a62,
             a63);
}
