enum context_sections : __int32
{
WINDOWCLASS_SECTION = 0x1,
DLLREDIRECT_SECTION = 0x2,
TLIBREDIRECT_SECTION = 0x4,
SERVERREDIRECT_SECTION = 0x8,
IFACEREDIRECT_SECTION = 0x10,
CLRSURROGATES_SECTION = 0x20,
PROGIDREDIRECT_SECTION = 0x40,
};
