struct AVCollectionIndex
{
AVCollectionEntry *health; ///< Verified: slot 0 / offset 0x0 stores actor-value ID 0x8. Same mapping in AddToArray 65C710, GetNode 65C010 and RemoveArrayNode 65BE70; identity resolved through ActorValue_GetName 565CC0 and local setting registration/string table.
AVCollectionEntry *encumbrance; ///< Verified: slot 1 / offset 0x4 stores actor-value ID 0xb. Same mapping in AddToArray 65C710, GetNode 65C010 and RemoveArrayNode 65BE70; identity resolved through ActorValue_GetName 565CC0 and local setting registration/string table.
AVCollectionEntry *magickaMultiplier; ///< Verified: slot 2 / offset 0x8 stores actor-value ID 0x28. Same mapping in AddToArray 65C710, GetNode 65C010 and RemoveArrayNode 65BE70; identity resolved through ActorValue_GetName 565CC0 and local setting registration/string table.
AVCollectionEntry *paralysis; ///< Verified: slot 3 / offset 0xc stores actor-value ID 0x30. Same mapping in AddToArray 65C710, GetNode 65C010 and RemoveArrayNode 65BE70; identity resolved through ActorValue_GetName 565CC0 and local setting registration/string table.
AVCollectionEntry *responsibility; ///< Verified: slot 4 / offset 0x10 stores actor-value ID 0x24. Same mapping in AddToArray 65C710, GetNode 65C010 and RemoveArrayNode 65BE70; identity resolved through ActorValue_GetName 565CC0 and local setting registration/string table.
AVCollectionEntry *silence; ///< Verified: slot 5 / offset 0x14 stores actor-value ID 0x31. Same mapping in AddToArray 65C710, GetNode 65C010 and RemoveArrayNode 65BE70; identity resolved through ActorValue_GetName 565CC0 and local setting registration/string table.
AVCollectionEntry *personality; ///< Verified: slot 6 / offset 0x18 stores actor-value ID 0x6. Same mapping in AddToArray 65C710, GetNode 65C010 and RemoveArrayNode 65BE70; identity resolved through ActorValue_GetName 565CC0 and local setting registration/string table.
AVCollectionEntry *waterWalking; ///< Verified: slot 7 / offset 0x1c stores actor-value ID 0x38. Same mapping in AddToArray 65C710, GetNode 65C010 and RemoveArrayNode 65BE70; identity resolved through ActorValue_GetName 565CC0 and local setting registration/string table.
AVCollectionEntry *chameleon; ///< Verified: slot 8 / offset 0x20 stores actor-value ID 0x2e. Same mapping in AddToArray 65C710, GetNode 65C010 and RemoveArrayNode 65BE70; identity resolved through ActorValue_GetName 565CC0 and local setting registration/string table.
AVCollectionEntry *invisibility; ///< Verified: slot 9 / offset 0x24 stores actor-value ID 0x2f. Same mapping in AddToArray 65C710, GetNode 65C010 and RemoveArrayNode 65BE70; identity resolved through ActorValue_GetName 565CC0 and local setting registration/string table.
AVCollectionEntry *nightEyeBonus; ///< Verified: slot 10 / offset 0x28 stores actor-value ID 0x29. Same mapping in AddToArray 65C710, GetNode 65C010 and RemoveArrayNode 65BE70; identity resolved through ActorValue_GetName 565CC0 and local setting registration/string table.
AVCollectionEntry *aggression; ///< Verified: slot 11 / offset 0x2c stores actor-value ID 0x21. Same mapping in AddToArray 65C710, GetNode 65C010 and RemoveArrayNode 65BE70; identity resolved through ActorValue_GetName 565CC0 and local setting registration/string table.
AVCollectionEntry *acrobatics; ///< Verified: slot 12 / offset 0x30 stores actor-value ID 0x1a. Same mapping in AddToArray 65C710, GetNode 65C010 and RemoveArrayNode 65BE70; identity resolved through ActorValue_GetName 565CC0 and local setting registration/string table.
AVCollectionEntry *endurance; ///< Verified: slot 13 / offset 0x34 stores actor-value ID 0x5. Same mapping in AddToArray 65C710, GetNode 65C010 and RemoveArrayNode 65BE70; identity resolved through ActorValue_GetName 565CC0 and local setting registration/string table.
AVCollectionEntry *luck; ///< Verified: slot 14 / offset 0x38 stores actor-value ID 0x7. Same mapping in AddToArray 65C710, GetNode 65C010 and RemoveArrayNode 65BE70; identity resolved through ActorValue_GetName 565CC0 and local setting registration/string table.
AVCollectionEntry *strength; ///< Verified: slot 15 / offset 0x3c stores actor-value ID 0x0. Same mapping in AddToArray 65C710, GetNode 65C010 and RemoveArrayNode 65BE70; identity resolved through ActorValue_GetName 565CC0 and local setting registration/string table.
AVCollectionEntry *speed; ///< Verified: slot 16 / offset 0x40 stores actor-value ID 0x4. Same mapping in AddToArray 65C710, GetNode 65C010 and RemoveArrayNode 65BE70; identity resolved through ActorValue_GetName 565CC0 and local setting registration/string table.
AVCollectionEntry *athletics; ///< Verified: slot 17 / offset 0x44 stores actor-value ID 0xd. Same mapping in AddToArray 65C710, GetNode 65C010 and RemoveArrayNode 65BE70; identity resolved through ActorValue_GetName 565CC0 and local setting registration/string table.
};
