int __usercall Actor_AttackHandling_::RunProjectileOnHitScript_@<eax>(
        int ebp0@<ebp>,
        int a1@<edi>,
        int a2@<esi>,
        int a3,
        int a4,
        int a5,
        int a6,
        int a7,
        int a8,
        int a9,
        int a10,
        int a11,
        int a12,
        int a13,
        int a14,
        int a15,
        int a16,
        int a17,
        int a18,
        int a19,
        int a20,
        int a21,
        float a22,
        int a24,
        int a25,
        int a26)
{
  if ( ebp0 )
    return Actor_AttackHandling_::RunProjectileOnHitScript(
             a3,
             a4,
             a5,
             a6,
             a7,
             a8,
             a9,
             a10,
             a11,
             a12,
             a13,
             a14,
             a15,
             a16,
             a17,
             a18,
             a19,
             a20,
             a21,
             LODWORD(a22),
             a24,
             a25,
             a26);
  else
    return Actor_AttackHandling_::RunOnHitByScript(
             a1,
             a2,
             a3,
             a4,
             a5,
             a6,
             a7,
             a8,
             a9,
             a10,
             a11,
             a12,
             a13,
             a14,
             a15,
             a16,
             a17,
             a18,
             a19,
             a20,
             a21,
             a22);
}
