void __thiscall WaterShader::AddConstants(WaterShader *this)
{
  NiD3DShaderConstantMap **p_PixelConstantMap; // esi
  NiD3DShaderConstantMap *v3; // eax
  NiD3DShaderConstantMap *v4; // eax
  NiD3DShaderConstantMap **p_VertexConstantMap; // esi
  NiD3DShaderConstantMap *v6; // eax
  NiD3DShaderConstantMap *v7; // eax

  p_PixelConstantMap = &this->super.member.super.PixelConstantMap;
  if ( !this->super.member.super.PixelConstantMap )
  {
    v3 = (NiD3DShaderConstantMap *)FormHeapAlloc(0x34u);
    if ( v3 )
      v4 = NiD3DShaderCostantMapPixel::Construct(v3, (int)this->super.member.super.super.D3DRenderer);
    else
      v4 = 0;
    NiSmartPointer_Set__((Ni2DBuffer **)p_PixelConstantMap, (Ni2DBuffer *)v4);
    (*p_PixelConstantMap)->_vtbl->NiD3DShaderConstantMap__AddConstant(
      *p_PixelConstantMap,
      "Scroll",
      0x10000007,
      0,
      0,
      1,
      EmptyString,
      0x10,
      4,
      &flt_B45E64,
      0);
    (*p_PixelConstantMap)->_vtbl->NiD3DShaderConstantMap__AddConstant(
      *p_PixelConstantMap,
      "EyePos",
      0x10000007,
      0,
      1,
      1,
      EmptyString,
      0x10,
      4,
      &dword_B45DD4,
      0);
    (*p_PixelConstantMap)->_vtbl->NiD3DShaderConstantMap__AddConstant(
      *p_PixelConstantMap,
      "SunDir",
      0x10000007,
      0,
      2,
      1,
      EmptyString,
      0x10,
      4,
      &flt_B45DF4,
      0);
    (*p_PixelConstantMap)->_vtbl->NiD3DShaderConstantMap__AddConstant(
      *p_PixelConstantMap,
      "SunColor",
      0x10000007,
      0,
      3,
      1,
      EmptyString,
      0x10,
      4,
      &flt_B45E04,
      0);
    (*p_PixelConstantMap)->_vtbl->NiD3DShaderConstantMap__AddConstant(
      *p_PixelConstantMap,
      "NormalOffset",
      0x10000007,
      0,
      4,
      1,
      EmptyString,
      0x10,
      4,
      &dword_B45EC4,
      0);
    (*p_PixelConstantMap)->_vtbl->NiD3DShaderConstantMap__AddConstant(
      *p_PixelConstantMap,
      "ShallowColor",
      0x10000007,
      0,
      5,
      1,
      EmptyString,
      0x10,
      4,
      &dword_B45E14,
      0);
    (*p_PixelConstantMap)->_vtbl->NiD3DShaderConstantMap__AddConstant(
      *p_PixelConstantMap,
      "DeepColor",
      0x10000007,
      0,
      6,
      1,
      EmptyString,
      0x10,
      4,
      &dword_B45E24,
      0);
    (*p_PixelConstantMap)->_vtbl->NiD3DShaderConstantMap__AddConstant(
      *p_PixelConstantMap,
      "ReflectionColor",
      0x10000007,
      0,
      7,
      1,
      EmptyString,
      0x10,
      4,
      &dword_B45E34,
      0);
    (*p_PixelConstantMap)->_vtbl->NiD3DShaderConstantMap__AddConstant(
      *p_PixelConstantMap,
      "VarAmounts",
      0x10000007,
      0,
      8,
      1,
      EmptyString,
      0x10,
      4,
      &flt_B45E44,
      0);
    (*p_PixelConstantMap)->_vtbl->NiD3DShaderConstantMap__AddConstant(
      *p_PixelConstantMap,
      "FogParam",
      0x10000007,
      0,
      9,
      1,
      EmptyString,
      0x10,
      4,
      &dword_B45E74,
      0);
    (*p_PixelConstantMap)->_vtbl->NiD3DShaderConstantMap__AddConstant(
      *p_PixelConstantMap,
      "FogColor",
      0x10000007,
      0,
      0xA,
      1,
      EmptyString,
      0x10,
      4,
      &dword_B45E84,
      0);
    (*p_PixelConstantMap)->_vtbl->NiD3DShaderConstantMap__AddConstant(
      *p_PixelConstantMap,
      "FresnelRI",
      0x10000007,
      0,
      0xB,
      1,
      EmptyString,
      0x10,
      4,
      &flt_B45E94,
      0);
    (*p_PixelConstantMap)->_vtbl->NiD3DShaderConstantMap__AddConstant(
      *p_PixelConstantMap,
      "BlendRadius",
      0x10000007,
      0,
      0xC,
      1,
      EmptyString,
      0x10,
      4,
      &flt_B45EB4,
      0);
  }
  p_VertexConstantMap = &this->super.member.super.VertexConstantMap;
  if ( !this->super.member.super.VertexConstantMap )
  {
    v6 = (NiD3DShaderConstantMap *)FormHeapAlloc(0x34u);
    if ( v6 )
      v7 = NiD3DShaderCostantMapVertex::Construct(v6, (int)this->super.member.super.super.D3DRenderer);
    else
      v7 = 0;
    NiSmartPointer_Set__((Ni2DBuffer **)&this->super.member.super.VertexConstantMap, (Ni2DBuffer *)v7);
    (*p_VertexConstantMap)->_vtbl->NiD3DShaderConstantMap__AddConstant(
      *p_VertexConstantMap,
      "WorldViewProjTranspose",
      0x20000009,
      0,
      0,
      4,
      0,
      0,
      0,
      0,
      0);
    ((void (__thiscall *)(NiD3DShaderConstantMap *, const char *, int, int, CHAR *))(*p_VertexConstantMap)->_vtbl->sub_9A8800)(
      *p_VertexConstantMap,
      "WorldTranspose",
      0x20000009,
      4,
      EmptyString);
    (*p_VertexConstantMap)->_vtbl->NiD3DShaderConstantMap__AddConstant(
      *p_VertexConstantMap,
      "Tile",
      0x10000007,
      0,
      8,
      1,
      EmptyString,
      0x10,
      4,
      &flt_B45EA4,
      0);
    (*p_VertexConstantMap)->_vtbl->NiD3DShaderConstantMap__AddConstant(
      *p_VertexConstantMap,
      "QPosAdjust",
      0x10000007,
      0,
      9,
      1,
      EmptyString,
      0x10,
      4,
      &flt_B45ED4,
      0);
    (*p_VertexConstantMap)->_vtbl->NiD3DShaderConstantMap__AddConstant(
      *p_VertexConstantMap,
      "DepthOffset",
      0x10000007,
      0,
      0xA,
      1,
      EmptyString,
      0x10,
      4,
      &dword_B45EE4,
      0);
  }
}
