int __cdecl ValueModifierEffect_AttributeWarning(
        int a1,
        int a2,
        int a3,
        int a4,
        int a5,
        int a6,
        int a7,
        int a8,
        int a9,
        int a10,
        int a11,
        int a12,
        int a13,
        int a14,
        int a15,
        int a16,
        int a17,
        int a18,
        int a19,
        int a20,
        int a21,
        int a22,
        int a23,
        int a24,
        int a25,
        int a26,
        int a27,
        int a28,
        int a29,
        int a30,
        int a31,
        int a32,
        int a33,
        int a34,
        int a35,
        int a36,
        int a37,
        int a38,
        int a39,
        int a40,
        int a41,
        int a42,
        int a43,
        int a44,
        int a45,
        int a46,
        int a47,
        int a48,
        int a49,
        int a50,
        int a51)
{
  int v0; // ecx MAPDST
  MagicTarget *p_magicTarget; // eax
  _DWORD *v56; // ecx
  unsigned int v57; // eax
  int v58; // ecx
  int v59; // ecx
  unsigned int v60; // eax
  const char *v61; // esi
  const char *Name; // eax
  const char *duration; // [esp+0h] [ebp-D4h]
  char string[200]; // [esp+8h] [ebp-CCh] BYREF

  if ( TESDataHandler_g_PlayerRef )
    p_magicTarget = &TESDataHandler_g_PlayerRef->super.super.magicTarget;
  else
    p_magicTarget = 0;
  if ( *(MagicTarget **)(v0 + 0x20) != p_magicTarget )
    return ValueModifierEffect_AttributeWarning_::Wrapup(
             a1,
             a2,
             a3,
             a4,
             a5,
             a6,
             a7,
             a8,
             a9,
             a10,
             a11,
             a12,
             a13,
             a14,
             a15,
             a16,
             a17,
             a18,
             a19,
             a20,
             a21,
             a22,
             a23,
             a24,
             a25,
             a26,
             a27,
             a28,
             a29,
             a30,
             a31,
             a32,
             a33,
             a34,
             a35,
             a36,
             a37,
             a38,
             a39,
             a40,
             a41,
             a42,
             a43,
             a44,
             a45,
             a46,
             a47,
             a48,
             a49,
             a50,
             a51);
  v56 = *(_DWORD **)(v0 + 0xC);
  v57 = v56[5];
  if ( v57 > 7 && v57 - 0xC > 0x14 )
    return ValueModifierEffect_AttributeWarning_::Wrapup(
             a1,
             a2,
             a3,
             a4,
             a5,
             a6,
             a7,
             a8,
             a9,
             a10,
             a11,
             a12,
             a13,
             a14,
             a15,
             a16,
             a17,
             a18,
             a19,
             a20,
             a21,
             a22,
             a23,
             a24,
             a25,
             a26,
             a27,
             a28,
             a29,
             a30,
             a31,
             a32,
             a33,
             a34,
             a35,
             a36,
             a37,
             a38,
             a39,
             a40,
             a41,
             a42,
             a43,
             a44,
             a45,
             a46,
             a47,
             a48,
             a49,
             a50,
             a51);
  if ( !EffectItem_IsHostile(v56) )
    return ValueModifierEffect_AttributeWarning_::Wrapup(
             a1,
             a2,
             a3,
             a4,
             a5,
             a6,
             a7,
             a8,
             a9,
             a10,
             a11,
             a12,
             a13,
             a14,
             a15,
             a16,
             a17,
             a18,
             a19,
             a20,
             a21,
             a22,
             a23,
             a24,
             a25,
             a26,
             a27,
             a28,
             a29,
             a30,
             a31,
             a32,
             a33,
             a34,
             a35,
             a36,
             a37,
             a38,
             a39,
             a40,
             a41,
             a42,
             a43,
             a44,
             a45,
             a46,
             a47,
             a48,
             a49,
             a50,
             a51);
  if ( (*(int (__thiscall **)(_DWORD))(**(_DWORD **)(v0 + 8) + 0x18))(*(_DWORD *)(v0 + 8)) == 4 )
    return ValueModifierEffect_AttributeWarning_::Wrapup(
             a1,
             a2,
             a3,
             a4,
             a5,
             a6,
             a7,
             a8,
             a9,
             a10,
             a11,
             a12,
             a13,
             a14,
             a15,
             a16,
             a17,
             a18,
             a19,
             a20,
             a21,
             a22,
             a23,
             a24,
             a25,
             a26,
             a27,
             a28,
             a29,
             a30,
             a31,
             a32,
             a33,
             a34,
             a35,
             a36,
             a37,
             a38,
             a39,
             a40,
             a41,
             a42,
             a43,
             a44,
             a45,
             a46,
             a47,
             a48,
             a49,
             a50,
             a51);
  v58 = *(_DWORD *)(*(_DWORD *)(v0 + 0xC) + 0x1C);
  if ( (*(_DWORD *)(v58 + 0x58) & 4) == 0 )
    return ValueModifierEffect_AttributeWarning_::Wrapup(
             a1,
             a2,
             a3,
             a4,
             a5,
             a6,
             a7,
             a8,
             a9,
             a10,
             a11,
             a12,
             a13,
             a14,
             a15,
             a16,
             a17,
             a18,
             a19,
             a20,
             a21,
             a22,
             a23,
             a24,
             a25,
             a26,
             a27,
             a28,
             a29,
             a30,
             a31,
             a32,
             a33,
             a34,
             a35,
             a36,
             a37,
             a38,
             a39,
             a40,
             a41,
             a42,
             a43,
             a44,
             a45,
             a46,
             a47,
             a48,
             a49,
             a50,
             a51);
  if ( (*(_DWORD *)(v58 + 0x58) & 2) != 0 || (unsigned __int8)ActiveEffect_Base_IsBoundObjWearable((_DWORD *)v0) )
    v59 = sAttributeDrained;
  else
    v59 = sAttributeDamaged;
  v60 = *(_DWORD *)(*(_DWORD *)(v0 + 0xC) + 0x14);
  v61 = (const char *)sYour;
  duration = (const char *)v59;
  Name = (const char *)ActorValue_GetName(v60);
  _sprintf(string, "%s %s %s", v61, Name, duration);
  GameUI_QueueMessage(string, 0, 1u, *(float *)&dword_A46C30);
  return ValueModifierEffect_AttributeWarning_::Wrapup(
           a1,
           a2,
           a3,
           a4,
           a5,
           a6,
           a7,
           a8,
           a9,
           a10,
           a11,
           a12,
           a13,
           a14,
           a15,
           a16,
           a17,
           a18,
           a19,
           a20,
           a21,
           a22,
           a23,
           a24,
           a25,
           a26,
           a27,
           a28,
           a29,
           a30,
           a31,
           a32,
           a33,
           a34,
           a35,
           a36,
           a37,
           a38,
           a39,
           a40,
           a41,
           a42,
           a43,
           a44,
           a45,
           a46,
           a47,
           a48,
           a49,
           a50,
           a51);
}
