int __usercall Actor_AttackHandling_::WeaponDamage@<eax>(
        char a1@<bl>,
        Actor *a2@<edi>,
        int a3@<esi>,
        int a4,
        int a5,
        int a6,
        int a7,
        int a8,
        int a9,
        int a10,
        int a11,
        float *a12,
        int a13,
        int a14,
        EntryData *a15,
        int damageOffset,
        int a17,
        float a18,
        int a19,
        int a20,
        int a21,
        int a22,
        int a23,
        int a24,
        int a25,
        int a26,
        int a27)
{
  if ( !a12 ) /*0x5ff48c*/
    JUMPOUT(0x5FF499); /*0x5ff499*/
  return Actor_AttackHandling_::WeaponDamage_(
           a1,
           a2,
           a3,
           a4,
           a5,
           a6,
           a7,
           a8,
           a9,
           a10,
           a11,
           a12,
           a13,
           a14,
           a15,
           damageOffset,
           a17,
           a18,
           a19,
           a20,
           a21,
           a22,
           a23,
           a24,
           a25,
           a26,
           a27);
}
