int __usercall TESLeveledList_CalcLeveledForm_::FindMaxLevelLoop_next@<eax>(
        unsigned __int16 **a1@<edx>,
        unsigned __int16 a2@<cx>,
        unsigned __int16 *a3@<ebx>,
        int a4@<ebp>,
        unsigned int a5@<edi>,
        unsigned __int16 si0@<si>,
        int a7,
        int a8,
        int a9,
        int a10,
        int a11,
        int a12,
        int a13,
        char a14,
        int a15,
        int a16,
        int a17,
        int a18,
        int a19,
        int a20)
{
  if ( a1 != (unsigned __int16 **)a3 )
    return TESLeveledList_CalcLeveledForm_::FindMaxLevelLoop(
             a1,
             a2,
             a3,
             a4,
             a5,
             si0,
             a7,
             a8,
             a9,
             a10,
             a11,
             a12,
             a13,
             a14,
             a15,
             a16,
             a17,
             a18,
             a19,
             a20);
  if ( a2 >= a5 )
    return TESLeveledList_CalcLeveledForm_::InitContainer(
             (int)a3,
             a4,
             si0,
             a7,
             a8,
             a9,
             a10,
             a11,
             a12,
             a13,
             a14,
             a15,
             a16,
             a17,
             a18,
             a19,
             a20);
  return TESLeveledList_CalcLeveledForm_::InitContainer(
           (int)a3,
           a4,
           si0,
           a7,
           a8,
           a9,
           a10,
           a2,
           a12,
           a13,
           a14,
           a15,
           a16,
           a17,
           a18,
           a19,
           a20);
}
