int __usercall MagicCaster_ApplyActiveMagicItem_::EffectLoop_ApplyOnTouch_NoTargetAOE@<eax>(
        char a1@<cl>,
        _DWORD *a2@<ebp>,
        TESObjectREFR *a3@<ebx>,
        void (__thiscall ***a4)(_DWORD, int)@<edi>,
        char *a5@<esi>,
        int a6,
        int a7,
        int a8,
        int a9,
        int a10,
        TESObjectREFR *a11,
        int a12,
        int a13,
        int a14,
        int a15,
        int a16,
        int a17,
        int a18,
        int a19,
        int a20,
        __int64 a21,
        int a22,
        int a23,
        int a24,
        int a25,
        int a26,
        int a27,
        int a28,
        int a29,
        int a30,
        int a31,
        int a32,
        int a33,
        int a34,
        int a35,
        int a36)
{
  if ( a1 || !a16 || *(char *)(a16 + 0x40) >= 0 || EffectItem_GetArea(a2) <= 0 || !a11 ) /*0x69b573*/
    return MagicCaster_ApplyActiveMagicItem_::EffectLoop_DestroyActvEff( /*0x69b54b*/
             a3,
             a4,
             (int)a5,
             a6,
             a7,
             a8,
             a9,
             a10,
             (int)a11,
             a12,
             a13,
             a14,
             a15,
             a16,
             a17,
             a18,
             a19,
             a20,
             a21,
             a22,
             a23,
             a24,
             a25,
             a26,
             a27,
             a28,
             a29,
             a30,
             a31,
             a32,
             a33,
             a34,
             a35,
             a36);
  BYTE2(a10) = 0; /*0x69b580*/
  a11->vtbl->GetPos(a11); /*0x69b585*/
  return MagicCaster_ApplyActiveMagicItem_::EffectLoop_ApplyOnTouch_AOE(
           a11,
           (int)a4,
           a5,
           a6,
           a7,
           a8,
           a9,
           a10,
           (int)a11,
           a12,
           a13,
           a14,
           a15,
           a16,
           a17);
}
