int __usercall MagicCaster_ApplyActiveMagicItem_::GetVFXInfo_Target@<eax>(
        TESObjectREFR *a1@<ebx>,
        char *a2@<esi>,
        int a3,
        int a4,
        int a5,
        int a6,
        int a7,
        TESObjectREFR *a8,
        int a9,
        int a10,
        int a11,
        int a12,
        int a13,
        int a14,
        int a15,
        int a16,
        int a17,
        double a18,
        int a19,
        int a20,
        int a21,
        int a22,
        int a23,
        int a24,
        int a25,
        int a26,
        int a27,
        int a28,
        int a29,
        int a30,
        int a31,
        int a32)
{
  bool v32; // al

  v32 = a13 && *(char *)(a13 + 0x40) < 0;
  if ( a1 || a8 && v32 )
    return MagicCaster_ApplyActiveMagicItem_::GetVFXInfo_Position_(
             a3,
             a4,
             a5,
             a6,
             a7,
             a8,
             a9,
             a10,
             a11,
             a12,
             a13,
             a14,
             a15,
             a16,
             a17,
             LODWORD(a18),
             HIDWORD(a18),
             a19,
             a20,
             a21,
             a22,
             a23,
             a24,
             a25,
             a26,
             a27,
             a28,
             a29,
             a30,
             a31,
             a32);
  else
    return MagicCaster_ApplyActiveMagicItem_::AfterVFX(
             a2,
             a3,
             a4,
             a5,
             a6,
             a7,
             (int)a8,
             a9,
             a10,
             a11,
             a12,
             a13,
             a14,
             a15,
             a16,
             a17,
             SLODWORD(a18),
             SHIDWORD(a18),
             a19,
             a20,
             a21,
             a22,
             a23,
             a24,
             a25,
             a26,
             a27,
             a28,
             a29,
             a30,
             a31);
}
