struct _WINE_ACMDRIVERID
{
WINE_ACMOBJ obj;
LPWSTR pszDriverAlias;
LPWSTR pszFileName;
PWINE_ACMLOCALDRIVER pLocalDriver;
PWINE_ACMDRIVER pACMDriverList;
PWINE_ACMDRIVERID pNextACMDriverID;
PWINE_ACMDRIVERID pPrevACMDriverID;
DWORD cFilterTags;
DWORD cFormatTags;
DWORD fdwSupport;
$D6B09942CCC7C698F65367F486EBB050 *aFormatTag;
};
