struct IDirect3DSurface9Vtbl
{
HRESULT (__stdcall *QueryInterface)(IDirect3DSurface9 *This, const IID *const riid, void **ppvObj); ///<
                                                                                                    ///<
                                                                                                    ///< 2026-10-03 stage-texture-com-contract host evidence: texture2D/cube/volume root plus2aliases report shared count3 across all4tested pools, retaining parent identity through GetContainer after parent release. Private data is per endpoint, not shared. Managed ROOT priority stores values; surface aliases always read/set0. Root QI supports IUnknown/Resource9/BaseTexture9/specific interface; surface QI supports IUnknown/Surface9 but rejects Resource9 despite C++ inheritance. Volume QI supports IUnknown/Volume9. Alias GetContainer(Device9) rejects; standalone surface GetContainer(IUnknown/Device9) returns device. Private-data IUNKNOWN retains on set/get and releases on removal. Zero-byte SetPrivateData returns E_OUTOFMEMORY; missing key stays missing, existing key becomes size0. Failed Reset on managed2D returns levels/type/priority0; GetLevelDesc/GetDesc reject and preserve descriptor output; GetSurfaceLevel lost failure leaves output unchanged, whereas bad-level failure while operational writesnull. QI/GetDevice/GetContainer/private data remain available. Software/HW-VP metadata comparison is archived. Owned D3D9TextureInterfaces frontend implements these contracts, aggregate retirement/inventory and required backend data callbacks; tests pass but real Store/data callbacks and live factory activation remain unfinished. No native resource allocation by this frontend; no deployment.
ULONG (__stdcall *AddRef)(IDirect3DSurface9 *This); ///<
                                                    ///<
                                                    ///< 2026-10-03 stage-texture-com-contract host evidence: texture2D/cube/volume root plus2aliases report shared count3 across all4tested pools, retaining parent identity through GetContainer after parent release. Private data is per endpoint, not shared. Managed ROOT priority stores values; surface aliases always read/set0. Root QI supports IUnknown/Resource9/BaseTexture9/specific interface; surface QI supports IUnknown/Surface9 but rejects Resource9 despite C++ inheritance. Volume QI supports IUnknown/Volume9. Alias GetContainer(Device9) rejects; standalone surface GetContainer(IUnknown/Device9) returns device. Private-data IUNKNOWN retains on set/get and releases on removal. Zero-byte SetPrivateData returns E_OUTOFMEMORY; missing key stays missing, existing key becomes size0. Failed Reset on managed2D returns levels/type/priority0; GetLevelDesc/GetDesc reject and preserve descriptor output; GetSurfaceLevel lost failure leaves output unchanged, whereas bad-level failure while operational writesnull. QI/GetDevice/GetContainer/private data remain available. Software/HW-VP metadata comparison is archived. Owned D3D9TextureInterfaces frontend implements these contracts, aggregate retirement/inventory and required backend data callbacks; tests pass but real Store/data callbacks and live factory activation remain unfinished. No native resource allocation by this frontend; no deployment.
ULONG (__stdcall *Release)(IDirect3DSurface9 *This); ///<
                                                     ///<
                                                     ///< 2026-10-03 stage-texture-com-contract host evidence: texture2D/cube/volume root plus2aliases report shared count3 across all4tested pools, retaining parent identity through GetContainer after parent release. Private data is per endpoint, not shared. Managed ROOT priority stores values; surface aliases always read/set0. Root QI supports IUnknown/Resource9/BaseTexture9/specific interface; surface QI supports IUnknown/Surface9 but rejects Resource9 despite C++ inheritance. Volume QI supports IUnknown/Volume9. Alias GetContainer(Device9) rejects; standalone surface GetContainer(IUnknown/Device9) returns device. Private-data IUNKNOWN retains on set/get and releases on removal. Zero-byte SetPrivateData returns E_OUTOFMEMORY; missing key stays missing, existing key becomes size0. Failed Reset on managed2D returns levels/type/priority0; GetLevelDesc/GetDesc reject and preserve descriptor output; GetSurfaceLevel lost failure leaves output unchanged, whereas bad-level failure while operational writesnull. QI/GetDevice/GetContainer/private data remain available. Software/HW-VP metadata comparison is archived. Owned D3D9TextureInterfaces frontend implements these contracts, aggregate retirement/inventory and required backend data callbacks; tests pass but real Store/data callbacks and live factory activation remain unfinished. No native resource allocation by this frontend; no deployment.
HRESULT (__stdcall *GetDevice)(IDirect3DSurface9 *This, IDirect3DDevice9 **ppDevice);
HRESULT (__stdcall *SetPrivateData)(IDirect3DSurface9 *This, const GUID *const refguid, const void *pData, DWORD SizeOfData, DWORD Flags); ///<
                                                                                                                                           ///<
                                                                                                                                           ///< 2026-10-03 stage-texture-com-contract host evidence: texture2D/cube/volume root plus2aliases report shared count3 across all4tested pools, retaining parent identity through GetContainer after parent release. Private data is per endpoint, not shared. Managed ROOT priority stores values; surface aliases always read/set0. Root QI supports IUnknown/Resource9/BaseTexture9/specific interface; surface QI supports IUnknown/Surface9 but rejects Resource9 despite C++ inheritance. Volume QI supports IUnknown/Volume9. Alias GetContainer(Device9) rejects; standalone surface GetContainer(IUnknown/Device9) returns device. Private-data IUNKNOWN retains on set/get and releases on removal. Zero-byte SetPrivateData returns E_OUTOFMEMORY; missing key stays missing, existing key becomes size0. Failed Reset on managed2D returns levels/type/priority0; GetLevelDesc/GetDesc reject and preserve descriptor output; GetSurfaceLevel lost failure leaves output unchanged, whereas bad-level failure while operational writesnull. QI/GetDevice/GetContainer/private data remain available. Software/HW-VP metadata comparison is archived. Owned D3D9TextureInterfaces frontend implements these contracts, aggregate retirement/inventory and required backend data callbacks; tests pass but real Store/data callbacks and live factory activation remain unfinished. No native resource allocation by this frontend; no deployment.
HRESULT (__stdcall *GetPrivateData)(IDirect3DSurface9 *This, const GUID *const refguid, void *pData, DWORD *pSizeOfData);
HRESULT (__stdcall *FreePrivateData)(IDirect3DSurface9 *This, const GUID *const refguid);
DWORD (__stdcall *SetPriority)(IDirect3DSurface9 *This, DWORD PriorityNew); ///<
                                                                            ///<
                                                                            ///< 2026-10-03 stage-texture-com-contract host evidence: texture2D/cube/volume root plus2aliases report shared count3 across all4tested pools, retaining parent identity through GetContainer after parent release. Private data is per endpoint, not shared. Managed ROOT priority stores values; surface aliases always read/set0. Root QI supports IUnknown/Resource9/BaseTexture9/specific interface; surface QI supports IUnknown/Surface9 but rejects Resource9 despite C++ inheritance. Volume QI supports IUnknown/Volume9. Alias GetContainer(Device9) rejects; standalone surface GetContainer(IUnknown/Device9) returns device. Private-data IUNKNOWN retains on set/get and releases on removal. Zero-byte SetPrivateData returns E_OUTOFMEMORY; missing key stays missing, existing key becomes size0. Failed Reset on managed2D returns levels/type/priority0; GetLevelDesc/GetDesc reject and preserve descriptor output; GetSurfaceLevel lost failure leaves output unchanged, whereas bad-level failure while operational writesnull. QI/GetDevice/GetContainer/private data remain available. Software/HW-VP metadata comparison is archived. Owned D3D9TextureInterfaces frontend implements these contracts, aggregate retirement/inventory and required backend data callbacks; tests pass but real Store/data callbacks and live factory activation remain unfinished. No native resource allocation by this frontend; no deployment.
DWORD (__stdcall *GetPriority)(IDirect3DSurface9 *This); ///<
                                                         ///<
                                                         ///< 2026-10-03 stage-texture-com-contract host evidence: texture2D/cube/volume root plus2aliases report shared count3 across all4tested pools, retaining parent identity through GetContainer after parent release. Private data is per endpoint, not shared. Managed ROOT priority stores values; surface aliases always read/set0. Root QI supports IUnknown/Resource9/BaseTexture9/specific interface; surface QI supports IUnknown/Surface9 but rejects Resource9 despite C++ inheritance. Volume QI supports IUnknown/Volume9. Alias GetContainer(Device9) rejects; standalone surface GetContainer(IUnknown/Device9) returns device. Private-data IUNKNOWN retains on set/get and releases on removal. Zero-byte SetPrivateData returns E_OUTOFMEMORY; missing key stays missing, existing key becomes size0. Failed Reset on managed2D returns levels/type/priority0; GetLevelDesc/GetDesc reject and preserve descriptor output; GetSurfaceLevel lost failure leaves output unchanged, whereas bad-level failure while operational writesnull. QI/GetDevice/GetContainer/private data remain available. Software/HW-VP metadata comparison is archived. Owned D3D9TextureInterfaces frontend implements these contracts, aggregate retirement/inventory and required backend data callbacks; tests pass but real Store/data callbacks and live factory activation remain unfinished. No native resource allocation by this frontend; no deployment.
void (__stdcall *PreLoad)(IDirect3DSurface9 *This);
D3DRESOURCETYPE (__stdcall *GetType)(IDirect3DSurface9 *This);
HRESULT (__stdcall *GetContainer)(IDirect3DSurface9 *This, const IID *const riid, void **ppContainer); ///<
                                                                                                       ///<
                                                                                                       ///< 2026-10-03 stage-texture-com-contract host evidence: texture2D/cube/volume root plus2aliases report shared count3 across all4tested pools, retaining parent identity through GetContainer after parent release. Private data is per endpoint, not shared. Managed ROOT priority stores values; surface aliases always read/set0. Root QI supports IUnknown/Resource9/BaseTexture9/specific interface; surface QI supports IUnknown/Surface9 but rejects Resource9 despite C++ inheritance. Volume QI supports IUnknown/Volume9. Alias GetContainer(Device9) rejects; standalone surface GetContainer(IUnknown/Device9) returns device. Private-data IUNKNOWN retains on set/get and releases on removal. Zero-byte SetPrivateData returns E_OUTOFMEMORY; missing key stays missing, existing key becomes size0. Failed Reset on managed2D returns levels/type/priority0; GetLevelDesc/GetDesc reject and preserve descriptor output; GetSurfaceLevel lost failure leaves output unchanged, whereas bad-level failure while operational writesnull. QI/GetDevice/GetContainer/private data remain available. Software/HW-VP metadata comparison is archived. Owned D3D9TextureInterfaces frontend implements these contracts, aggregate retirement/inventory and required backend data callbacks; tests pass but real Store/data callbacks and live factory activation remain unfinished. No native resource allocation by this frontend; no deployment.
HRESULT (__stdcall *GetDesc)(IDirect3DSurface9 *This, D3DSURFACE_DESC *pDesc); ///<
                                                                               ///<
                                                                               ///< 2026-10-03 stage-texture-com-contract host evidence: texture2D/cube/volume root plus2aliases report shared count3 across all4tested pools, retaining parent identity through GetContainer after parent release. Private data is per endpoint, not shared. Managed ROOT priority stores values; surface aliases always read/set0. Root QI supports IUnknown/Resource9/BaseTexture9/specific interface; surface QI supports IUnknown/Surface9 but rejects Resource9 despite C++ inheritance. Volume QI supports IUnknown/Volume9. Alias GetContainer(Device9) rejects; standalone surface GetContainer(IUnknown/Device9) returns device. Private-data IUNKNOWN retains on set/get and releases on removal. Zero-byte SetPrivateData returns E_OUTOFMEMORY; missing key stays missing, existing key becomes size0. Failed Reset on managed2D returns levels/type/priority0; GetLevelDesc/GetDesc reject and preserve descriptor output; GetSurfaceLevel lost failure leaves output unchanged, whereas bad-level failure while operational writesnull. QI/GetDevice/GetContainer/private data remain available. Software/HW-VP metadata comparison is archived. Owned D3D9TextureInterfaces frontend implements these contracts, aggregate retirement/inventory and required backend data callbacks; tests pass but real Store/data callbacks and live factory activation remain unfinished. No native resource allocation by this frontend; no deployment.
HRESULT (__stdcall *LockRect)(IDirect3DSurface9 *This, D3DLOCKED_RECT *pLockedRect, const RECT *pRect, DWORD Flags); ///<
                                                                                                                     ///<
                                                                                                                     ///< 2026-10-03 stage-owned-texture-mapping:1980native texture/cube/volume map cases and459surface cases. CPU2D/cube paths accept ignored hints incl tested unknown bit1, READONLY|DISCARD and bounded empty/unaligned-BC rectangles; volume and DEFAULT paths validate flags/ranges. DEFAULT ordinary textures reject locks; DYNAMIC accepts qualified maps. DEFAULT cube DISCARD rejects; dynamic2D/volume null top-level DISCARD succeeds; lower2D/cube DEFAULT DISCARD rejects. Duplicate same-subresource locks reject without breaking first Unlock; separate mips can lock together. Failed operational locks zero mapping outputs. DEFAULT standalone DONOTWAIT is valid but observed WASSTILLDRAWING while pending. RT row pitch has provider padding (64 vs owned minimum32 in8x8ARGB case), not portable fixed ABI. OwnedTextureMapping now uses Store sessions/owned row buffers, exact upload regions, CPU flag normalization, owner-supplied busy status, worker/race exclusion and reset replay; WARP pixels and legacy native-lock CPU regression pass. BeginOwnedLock rejects overlap before poisoning a lease; legacy native BeginLock remains unchanged. Empty CPU map has no write authority; out-of-bounds/reversed inputs reject. Component is not wired to live COM/factory callbacks yet. No renderer DLL build/deployment.
HRESULT (__stdcall *UnlockRect)(IDirect3DSurface9 *This); ///<
                                                          ///<
                                                          ///< 2026-10-03 stage-owned-texture-mapping:1980native texture/cube/volume map cases and459surface cases. CPU2D/cube paths accept ignored hints incl tested unknown bit1, READONLY|DISCARD and bounded empty/unaligned-BC rectangles; volume and DEFAULT paths validate flags/ranges. DEFAULT ordinary textures reject locks; DYNAMIC accepts qualified maps. DEFAULT cube DISCARD rejects; dynamic2D/volume null top-level DISCARD succeeds; lower2D/cube DEFAULT DISCARD rejects. Duplicate same-subresource locks reject without breaking first Unlock; separate mips can lock together. Failed operational locks zero mapping outputs. DEFAULT standalone DONOTWAIT is valid but observed WASSTILLDRAWING while pending. RT row pitch has provider padding (64 vs owned minimum32 in8x8ARGB case), not portable fixed ABI. OwnedTextureMapping now uses Store sessions/owned row buffers, exact upload regions, CPU flag normalization, owner-supplied busy status, worker/race exclusion and reset replay; WARP pixels and legacy native-lock CPU regression pass. BeginOwnedLock rejects overlap before poisoning a lease; legacy native BeginLock remains unchanged. Empty CPU map has no write authority; out-of-bounds/reversed inputs reject. Component is not wired to live COM/factory callbacks yet. No renderer DLL build/deployment.
HRESULT (__stdcall *GetDC)(IDirect3DSurface9 *This, HDC *phdc); ///<
                                                                ///<
                                                                ///< 2026-10-02 native GDI contract stage-owned-gdi-contract:360creation cases/170successes/63GetDC successes on tested host. Accepted formatsX8R8G8B8,A8R8G8B8,R5G6B5,X1R5G5B5,A1R5G5B5; scratch surfaces and non-lockable DEFAULT resources rejectINVALIDCALL. DEFAULT texture/cube DYNAMIC supports these formats; managed/SYSTEMMEM supported cases accepted; lockable RT accepted, non-lockable RT rejected. Actual DIBSECTION is positive-height bottom-up:32bpp BI_RGB,16bpp BI_BITFIELDS with565(F800/07E0/001F) or555(7C00/03E0/001F). SetPixelV RGB200,100,50 yieldsraw00C86432/CB26/6586; touched alpha/high bits clear, untouchedA5bits remain. OwnedGdiBitmap component passes360checks including five pixel/mask/DC contracts and170admission results. It is NOT hooked into production yet: family DC transaction, owned input freshness, Reset and retirement still must be integrated. Backbuffer-specific admission was not in this probe. No new native renderer algorithm inferred; provider-scoped ABI/behavior evidence only. No deployment.
                                                                ///<
                                                                ///< 2026-10-02 additional native GDI lifecycle evidence, stage-owned-gdi-transaction/native-lifecycle.log: active managed texture DC and SYSTEMMEM surface DC survive successful native Reset; ReleaseDC/reacquisition remainS_OK. DEFAULT surface causes ResetINVALIDCALL, retains handle type10, and ReleaseDC/GetDC rejectINVALIDCALL until resource release/device recovery. Additional backbuffer GetDC rejects without LOCKABLE_BACKBUFFER and accepts with flag1. Native SYSTEMMEM HDC stays valid after creating worker exits; main-thread GetPixel/ReleaseDC succeeds. Owned bitmap thread-survival test matches. New OwnedTextureGdi Session implements owned-snapshot/family reservation, Win32 pixel copy, storage commit, stale/retired handle rejection and replay patch after modern recreation; focused WARP test passes actual pixels and valid-view exclusion. Public Manager/GetDC routing is NOT switched yet: creation/backbuffer provenance, pristine initial content and failed-native-Reset boundaries still need integration. Host-scoped evidence; no new Oblivion engine algorithm inferred. No deployment.
                                                                ///<
                                                                ///< 2026-10-02 stage-owned-gdi-live source completed and validated: public owned GetDC/ReleaseDC use Win32 owned bitmaps and Store family transactions, not native DC/release or private input/output locks. DEFAULT uses current DX11 readback or exact pristine revision1/empty-range snapshot (same predicate as former writable synchronization); later incomplete pixels reject. CPU pre-existing resource bootstrap import remains explicit. RT lockability comes from exact recorded creation; backbuffer flag from retained validated presentation parameters. Failed native Reset rejects DC calls while retaining surviving managed handle. Prune releases GDI objects outside gates. Release build and6affected checks pass: public GDI bridge zero native DC/lock/readback traps, manager, owned transaction, legacy GDI reset, buffer live and shader live. Public test includes native Reset failure/recovery and hooks remaining installed; earlier module checks reused after only main Reset code changed. Source artifacts archived, NOT deployed; texture COM factories/bootstrap and full backend/GPU-bucket replacement remain unfinished.
HRESULT (__stdcall *ReleaseDC)(IDirect3DSurface9 *This, HDC hdc); ///<
                                                                  ///<
                                                                  ///< 2026-10-02 native GDI contract stage-owned-gdi-contract:360creation cases/170successes/63GetDC successes on tested host. Accepted formatsX8R8G8B8,A8R8G8B8,R5G6B5,X1R5G5B5,A1R5G5B5; scratch surfaces and non-lockable DEFAULT resources rejectINVALIDCALL. DEFAULT texture/cube DYNAMIC supports these formats; managed/SYSTEMMEM supported cases accepted; lockable RT accepted, non-lockable RT rejected. Actual DIBSECTION is positive-height bottom-up:32bpp BI_RGB,16bpp BI_BITFIELDS with565(F800/07E0/001F) or555(7C00/03E0/001F). SetPixelV RGB200,100,50 yieldsraw00C86432/CB26/6586; touched alpha/high bits clear, untouchedA5bits remain. OwnedGdiBitmap component passes360checks including five pixel/mask/DC contracts and170admission results. It is NOT hooked into production yet: family DC transaction, owned input freshness, Reset and retirement still must be integrated. Backbuffer-specific admission was not in this probe. No new native renderer algorithm inferred; provider-scoped ABI/behavior evidence only. No deployment.
                                                                  ///<
                                                                  ///< 2026-10-02 additional native GDI lifecycle evidence, stage-owned-gdi-transaction/native-lifecycle.log: active managed texture DC and SYSTEMMEM surface DC survive successful native Reset; ReleaseDC/reacquisition remainS_OK. DEFAULT surface causes ResetINVALIDCALL, retains handle type10, and ReleaseDC/GetDC rejectINVALIDCALL until resource release/device recovery. Additional backbuffer GetDC rejects without LOCKABLE_BACKBUFFER and accepts with flag1. Native SYSTEMMEM HDC stays valid after creating worker exits; main-thread GetPixel/ReleaseDC succeeds. Owned bitmap thread-survival test matches. New OwnedTextureGdi Session implements owned-snapshot/family reservation, Win32 pixel copy, storage commit, stale/retired handle rejection and replay patch after modern recreation; focused WARP test passes actual pixels and valid-view exclusion. Public Manager/GetDC routing is NOT switched yet: creation/backbuffer provenance, pristine initial content and failed-native-Reset boundaries still need integration. Host-scoped evidence; no new Oblivion engine algorithm inferred. No deployment.
                                                                  ///<
                                                                  ///< 2026-10-02 stage-owned-gdi-live source completed and validated: public owned GetDC/ReleaseDC use Win32 owned bitmaps and Store family transactions, not native DC/release or private input/output locks. DEFAULT uses current DX11 readback or exact pristine revision1/empty-range snapshot (same predicate as former writable synchronization); later incomplete pixels reject. CPU pre-existing resource bootstrap import remains explicit. RT lockability comes from exact recorded creation; backbuffer flag from retained validated presentation parameters. Failed native Reset rejects DC calls while retaining surviving managed handle. Prune releases GDI objects outside gates. Release build and6affected checks pass: public GDI bridge zero native DC/lock/readback traps, manager, owned transaction, legacy GDI reset, buffer live and shader live. Public test includes native Reset failure/recovery and hooks remaining installed; earlier module checks reused after only main Reset code changed. Source artifacts archived, NOT deployed; texture COM factories/bootstrap and full backend/GPU-bucket replacement remain unfinished.
};
